import { StyleSheet } from 'react-native';

import { elevationForScheme } from '../../theme/designTokens';
import type { ThemePalette, ResolvedTheme } from '../../theme';

/**
 * The shared shell stylesheet (S8/P18-049): the one `createStyles` that the
 * AppShell and the extracted shell screens/chrome compose from. It moved
 * verbatim out of AppShell.tsx; screens keep spreading it until their
 * successors adopt the shared primitives.
 */

export function createStyles(palette: ThemePalette, scheme: ResolvedTheme = 'light') {
  // P18-023: the hero surfaces use the per-scheme elevation so raised cards
  // stay visibly raised on the near-black dark background.
  const elevation = elevationForScheme(scheme, palette.shadow);
  return StyleSheet.create({
    safeArea: { flex: 1, backgroundColor: palette.background },
    app: { flex: 1 },
    screen: { flex: 1 },
    screenContent: { paddingHorizontal: 18, paddingTop: 12, paddingBottom: 28, gap: 14 },
    screenContentTablet: { width: '100%', maxWidth: 980, alignSelf: 'center', paddingHorizontal: 28, paddingTop: 18, paddingBottom: 44, gap: 18 },
    homeScreenContent: { paddingTop: 8, paddingBottom: 14, gap: 9 },
    setupScroll: { flex: 1, minHeight: 0 },
    setupScreenContent: { paddingBottom: 24 },
    setupActionBar: { gap: 7, paddingHorizontal: 18, paddingTop: 11, paddingBottom: 10, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: palette.border, backgroundColor: palette.background },
    setupActionBarTablet: { width: '100%', maxWidth: 980, alignSelf: 'center', gap: 10, paddingHorizontal: 28, paddingTop: 14, paddingBottom: 16 },
    header: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 2 },
    headerCopy: { flex: 1, minWidth: 0 },
    eyebrow: { color: palette.primary, fontSize: 11, fontWeight: '700', letterSpacing: 1.1, textTransform: 'uppercase' },
    title: { flexShrink: 1, color: palette.text, fontSize: 28, lineHeight: 33, fontWeight: '700', letterSpacing: -0.8, marginTop: 3 },
    sessionCard: { minHeight: 246, padding: 20, borderRadius: 23, borderWidth: 1, borderColor: palette.border, backgroundColor: palette.surfaceRaised, justifyContent: 'space-between', overflow: 'hidden', ...elevation.level2 },
    homeSessionCard: { minHeight: 0, padding: 15 },
    orb: { position: 'absolute', width: 148, height: 148, borderRadius: 74, right: -48, top: -58, backgroundColor: palette.accentSoft },
    sessionCopy: { maxWidth: 280, gap: 7 },
    homeSessionCopy: { maxWidth: '100%', gap: 5 },
    homeGoalLabel: { alignSelf: 'flex-start', color: palette.primary, fontSize: 8, lineHeight: 11, fontWeight: '800', letterSpacing: 0.45, textTransform: 'uppercase' },
    homeSessionTitleRow: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 10 },
    homeSessionMeta: { flexDirection: 'row', alignItems: 'center', flexShrink: 0, gap: 7 },
    homeSessionTitle: { flex: 1, minWidth: 0, fontSize: 18, lineHeight: 23 },
    timePill: { alignSelf: 'flex-start', flexDirection: 'row', alignItems: 'center', gap: 5, paddingHorizontal: 9, paddingVertical: 5, borderRadius: 9, backgroundColor: palette.aquaSoft },
    timeText: { color: palette.aquaText, fontSize: 11, fontWeight: '700' },
    sessionTitle: { color: palette.text, fontSize: 21, lineHeight: 27, fontWeight: '700', letterSpacing: -0.35 },
    bodyText: { color: palette.muted, fontSize: 13, lineHeight: 19 },
    homeProgressHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 10, marginTop: 3 },
    homeProgressLabel: { color: palette.muted, fontSize: 9, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.5 },
    homeProgressValue: { color: palette.aquaText, fontSize: 10, fontWeight: '800' },
    homeProgressTrack: { marginTop: 5 },
    homeSectionTitle: { color: palette.text, fontSize: 14, fontWeight: '800', marginTop: 1, paddingHorizontal: 2 },
    playGroup: { gap: 8 },
    playGroupHeader: { minHeight: 44, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 2, gap: 10 },
    playGroupLabel: { flexShrink: 1, color: palette.text, fontSize: 14, fontWeight: '800' },
    quickGameCard: { borderRadius: 20, borderWidth: 1, borderColor: palette.border, backgroundColor: palette.surface, paddingHorizontal: 14 },
    quickGameHead: { minHeight: 72, flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 12 },
    quickGameIcon: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center', borderRadius: 15, backgroundColor: palette.primary },
    quickGameCopy: { flex: 1, gap: 2 },
    quickGameTitle: { color: palette.text, fontSize: 19, lineHeight: 24, fontWeight: '800', letterSpacing: -0.4 },
    quickGameDescription: { color: palette.muted, fontSize: 12, lineHeight: 17 },
    quickGameSeatSection: { gap: 8, paddingTop: 10, paddingBottom: 12, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: palette.border },
    quickGameSeatLabel: { color: palette.muted, fontSize: 12, fontWeight: '800' },
    quickGameSeatRow: { flexDirection: 'row', gap: 8 },
    quickGameSeatChip: { flexGrow: 1, flexBasis: 0, minHeight: 48, alignItems: 'center', justifyContent: 'center', borderRadius: 14, borderWidth: 1, borderColor: palette.border, backgroundColor: palette.soft },
    quickGameSeatChipText: { color: palette.text, fontSize: 18, fontWeight: '800' },
    quickGameSeatNote: { color: palette.muted, fontSize: 11, lineHeight: 15 },
    homeMenuList: { paddingHorizontal: 11, borderRadius: 17, borderWidth: 1, borderColor: palette.border, backgroundColor: palette.surface, overflow: 'hidden' },
    primaryButton: { minHeight: 48, alignItems: 'center', justifyContent: 'center', borderRadius: 13, backgroundColor: palette.primary, paddingHorizontal: 16, ...elevation.level1 },
    primaryButtonLabel: { color: palette.primaryText, fontSize: 14, fontWeight: '700' },
    surface: { padding: 15, borderRadius: 18, borderWidth: 1, borderColor: palette.border, backgroundColor: palette.surface },
    surfaceTitle: { color: palette.text, fontSize: 15, fontWeight: '700' },
    secondaryText: { color: palette.muted, fontSize: 12, lineHeight: 17, marginTop: 3 },
    setupSurfaceTablet: { padding: 22, borderRadius: 22 },
    setupSurfaceTitleTablet: { fontSize: 19, lineHeight: 25 },
    setupSecondaryTextTablet: { fontSize: 15, lineHeight: 21, marginTop: 4 },
    profileSurfaceTablet: { padding: 22, borderRadius: 22 },
    profileSurfaceTitleTablet: { fontSize: 19, lineHeight: 25 },
    profileSecondaryTextTablet: { fontSize: 14, lineHeight: 20, marginTop: 4 },
    preferenceSectionLabel: { color: palette.muted, fontSize: 11, lineHeight: 15, fontWeight: '800', marginTop: 14 },
    preferenceSectionLabelTablet: { fontSize: 14, lineHeight: 19, marginTop: 18 },
    preferenceDivider: { height: StyleSheet.hairlineWidth, marginVertical: 12, backgroundColor: palette.border },
    preferenceDividerTablet: { marginVertical: 17 },
    playerNamePicker: { marginTop: 13 },
    playerNamePickerTablet: { marginTop: 17 },
    nameInputRow: { marginTop: 13, flexDirection: 'row', gap: 10 },
    nameInputRowTablet: { marginTop: 17, gap: 12 },
    nameInput: {
      flex: 1,
      minHeight: 46,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.surface,
      paddingHorizontal: 12,
      paddingVertical: 10,
      color: palette.text,
      fontSize: 15,
    },
    nameInputTablet: { fontSize: 17 },
    saveNameButton: {
      borderRadius: 12,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.primary,
      paddingVertical: 11,
      paddingHorizontal: 16,
      justifyContent: 'center',
      shadowColor: palette.shadow,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.12,
      shadowRadius: 10,
      elevation: 2,
    },
    saveNameButtonTablet: { paddingVertical: 13, paddingHorizontal: 20 },
    saveNameButtonPressed: { opacity: 0.74 },
    saveNameButtonText: { color: palette.primaryText, fontSize: 14, fontWeight: '700' },
    nameErrorText: { color: palette.danger, fontSize: 12, lineHeight: 16, marginTop: 6, fontWeight: '600' },
    spaceBetween: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 12 },
    flexShrink: { flex: 1 },
    progressTrack: { height: 5, backgroundColor: palette.soft, borderRadius: 4, overflow: 'hidden', marginTop: 12 },
    progressFill: { height: '100%', backgroundColor: palette.aqua },
    flatList: { borderRadius: 18, backgroundColor: palette.surface, borderWidth: 1, borderColor: palette.border, paddingHorizontal: 12 },
    profileFlatListTablet: { borderRadius: 22, paddingHorizontal: 16 },
    menuRow: { minHeight: 68, flexDirection: 'row', alignItems: 'center', gap: 12 },
    menuRowLarge: { minHeight: 82, gap: 15 },
    menuRowCompact: { minHeight: 54, gap: 9 },
    menuRowFlat: { borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: palette.border, paddingVertical: 11 },
    menuRowFlatLarge: { paddingVertical: 14 },
    menuIcon: { width: 38, height: 38, alignItems: 'center', justifyContent: 'center', borderRadius: 12, backgroundColor: palette.soft },
    menuIconLarge: { width: 46, height: 46, borderRadius: 14 },
    menuIconCompact: { width: 32, height: 32, borderRadius: 10 },
    menuIconAqua: { backgroundColor: palette.aquaSoft },
    menuIconDanger: { backgroundColor: `${palette.danger}18` },
    menuCopy: { flex: 1 },
    menuLabelRow: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 6 },
    menuLabel: { flexShrink: 1, color: palette.text, fontSize: 14, fontWeight: '700' },
    menuLabelDanger: { color: palette.danger },
    menuBadge: { flexShrink: 1, color: palette.muted, fontSize: 11, lineHeight: 14, fontWeight: '800', paddingHorizontal: 6, paddingVertical: 2, borderRadius: 7, backgroundColor: palette.soft, overflow: 'hidden' },
    menuLabelLarge: { fontSize: 16.5, lineHeight: 22 },
    menuLabelCompact: { fontSize: 12.5 },
    secondaryTextCompact: { fontSize: 9.5, lineHeight: 13, marginTop: 1 },
    secondaryTextLarge: { fontSize: 13.5, lineHeight: 19, marginTop: 3 },
    tournamentGroup: { gap: 10, paddingVertical: 12, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: palette.border },
    tournamentHeader: { flexDirection: 'row', alignItems: 'center', gap: 12 },
    tournamentChoices: { flexDirection: 'row', gap: 8 },
    tournamentChoice: { flex: 1, minHeight: 60, flexDirection: 'row', alignItems: 'center', gap: 5, paddingHorizontal: 10, borderRadius: 13, borderWidth: 1, borderColor: palette.border, backgroundColor: palette.soft },
    tournamentChoiceTablet: { minHeight: 76, gap: 9, paddingHorizontal: 15, borderRadius: 16 },
    tournamentChoiceSaved: { borderColor: palette.aqua, backgroundColor: palette.aquaSoft },
    tournamentChoiceCopy: { flex: 1, gap: 2 },
    tournamentChoiceLabel: { color: palette.text, fontSize: 12, fontWeight: '800' },
    tournamentChoiceLabelTablet: { fontSize: 16, lineHeight: 21 },
    tournamentChoiceCaption: { color: palette.muted, fontSize: 9, lineHeight: 12 },
    tournamentChoiceCaptionTablet: { fontSize: 13, lineHeight: 18 },
    backHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 4 },
    backHeaderLarge: { minHeight: 52, marginBottom: 8 },
    backButton: { width: 44, height: 44, borderRadius: 13, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: palette.border, backgroundColor: palette.surface },
    backButtonLarge: { width: 48, height: 48, borderRadius: 15 },
    backTitle: { flex: 1, minWidth: 0, color: palette.text, fontSize: 16, lineHeight: 21, fontWeight: '700', textAlign: 'center' },
    backTitleLarge: { fontSize: 21, lineHeight: 27 },
    backSpacer: { width: 44 },
    backSpacerLarge: { width: 48 },
    identityHeader: { flexDirection: 'row', alignItems: 'center', gap: 13, paddingHorizontal: 14, paddingVertical: 13, borderRadius: 20, borderWidth: 1, borderColor: palette.border, backgroundColor: palette.surface },
    identityHeaderTablet: { gap: 18, paddingHorizontal: 20, paddingVertical: 18 },
    identityCopy: { flex: 1, gap: 2 },
    identityName: { color: palette.text, fontSize: 19, lineHeight: 24, fontWeight: '800', letterSpacing: 0.2 },
    identityNameTablet: { fontSize: 23, lineHeight: 29 },
    identityEdit: { minWidth: 46, minHeight: 46, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 5, paddingHorizontal: 11, paddingVertical: 9, borderRadius: 13, borderWidth: 1, borderColor: palette.border, backgroundColor: palette.soft },
    identityEditLabel: { color: palette.primary, fontSize: 12, fontWeight: '800' },
    cancelNameButton: { alignSelf: 'flex-start', minHeight: 44, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 14, marginTop: 10 },
    cancelNameButtonText: { color: palette.muted, fontSize: 13, fontWeight: '700' },
    appearanceRow: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 8, marginTop: 14 },
    // The appearance picker is a segmented control rather than a section of its
    // own, so the label and the choice sit on one line and wrap together on the
    // narrowest phones instead of stacking into three tall tiles.
    appearanceSegment: { flex: 1, minWidth: 200, flexDirection: 'row', gap: 3, padding: 3, borderRadius: 13, borderWidth: 1, borderColor: palette.border, backgroundColor: palette.soft },
    profileAppearanceOptionsTablet: { gap: 6, padding: 4, borderRadius: 16 },
    appearanceOption: { flex: 1, minHeight: 42, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 5, borderRadius: 10 },
    profileAppearanceOptionTablet: { minHeight: 52, gap: 7, borderRadius: 12 },
    appearanceOptionSelected: { backgroundColor: palette.primary, borderColor: palette.primary },
    appearanceLabel: { color: palette.muted, fontSize: 12, fontWeight: '700' },
    profileAppearanceLabelTablet: { fontSize: 15 },
    appearanceLabelSelected: { color: palette.primaryText },
    feedbackPreferenceList: { marginTop: 0 },
    feedbackPreferenceRow: { minHeight: 68, flexDirection: 'row', alignItems: 'center', gap: 11 },
    feedbackPreferenceRowTablet: { minHeight: 86, gap: 15 },
    feedbackPreferenceIcon: { width: 38, height: 38, alignItems: 'center', justifyContent: 'center', borderRadius: 12, backgroundColor: palette.accentSoft },
    feedbackPreferenceIconTablet: { width: 48, height: 48, borderRadius: 15 },
    feedbackPreferenceLabel: { color: palette.text, fontSize: 14, lineHeight: 19, fontWeight: '800' },
    feedbackPreferenceLabelTablet: { fontSize: 17, lineHeight: 23 },
    feedbackPreferenceDescription: { color: palette.muted, fontSize: 11, lineHeight: 15, marginTop: 2, paddingRight: 6 },
    feedbackPreferenceDescriptionTablet: { fontSize: 14, lineHeight: 20, marginTop: 3, paddingRight: 12 },
    languageSelector: { minHeight: 62, marginTop: 13, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', gap: 11, borderRadius: 14, borderWidth: 1, borderColor: palette.border, backgroundColor: palette.soft },
    profileLanguageSelectorTablet: { minHeight: 78, marginTop: 17, paddingHorizontal: 16, gap: 14, borderRadius: 17 },
    preferenceLanguageSelector: { marginTop: 0 },
    languageSelectorIcon: { width: 36, height: 36, alignItems: 'center', justifyContent: 'center', borderRadius: 11, backgroundColor: palette.accentSoft },
    profileLanguageSelectorIconTablet: { width: 46, height: 46, borderRadius: 14 },
    languageModalRoot: { flex: 1, justifyContent: 'flex-end', padding: 14, backgroundColor: palette.scrim },
    languageModalRootLarge: { alignItems: 'center', padding: 24 },
    languageSheet: { gap: 14, paddingHorizontal: 16, paddingTop: 10, paddingBottom: 18, borderRadius: 22, borderWidth: 1, borderColor: palette.border, backgroundColor: palette.surfaceRaised, shadowColor: palette.shadow, shadowOffset: { width: 0, height: 12 }, shadowOpacity: 0.18, shadowRadius: 28, elevation: 8 },
    languageSheetLarge: { width: '100%', maxWidth: 620, gap: 18, paddingHorizontal: 22, paddingTop: 14, paddingBottom: 24, borderRadius: 26 },
    languageSheetHandle: { alignSelf: 'center', width: 38, height: 4, borderRadius: 3, backgroundColor: palette.border },
    languageSheetTitle: { color: palette.text, fontSize: 18, fontWeight: '800', letterSpacing: -0.3 },
    languageSheetTitleLarge: { fontSize: 22, lineHeight: 28 },
    languageOptions: { gap: 7 },
    languageOption: { minHeight: 58, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', gap: 11, borderRadius: 14, borderWidth: 1, borderColor: palette.border, backgroundColor: palette.surface },
    languageOptionLarge: { minHeight: 72, paddingHorizontal: 16, gap: 14, borderRadius: 17 },
    languageOptionSelected: { borderColor: palette.primary, backgroundColor: palette.accentSoft },
    languageOptionLabel: { color: palette.text, fontSize: 14, fontWeight: '700' },
    languageOptionLabelLarge: { fontSize: 17, lineHeight: 22 },
    languageRadio: { width: 20, height: 20, alignItems: 'center', justifyContent: 'center', borderRadius: 10, borderWidth: 2, borderColor: palette.border },
    languageRadioLarge: { width: 24, height: 24, borderRadius: 12 },
    languageRadioSelected: { borderColor: palette.primary },
    languageRadioDot: { width: 9, height: 9, borderRadius: 5, backgroundColor: palette.primary },
    fieldLabel: { color: palette.muted, fontSize: 12, fontWeight: '600', marginBottom: 9 },
    setupGroup: { gap: 18 },
    difficultyOptions: { flexDirection: 'row', gap: 7 },
    difficultyOptionsTablet: { gap: 12 },
    difficultyOption: { flex: 1, minHeight: 44, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 5, paddingVertical: 7, borderRadius: 12, borderWidth: 1, borderColor: palette.border, backgroundColor: palette.soft },
    difficultyOptionTablet: { minHeight: 56, paddingHorizontal: 10, paddingVertical: 10, borderRadius: 15 },
    difficultyOptionSelected: { borderColor: palette.primary, backgroundColor: palette.primary },
    difficultyLabel: { color: palette.text, fontSize: 12, lineHeight: 16, fontWeight: '700', textAlign: 'center' },
    setupDifficultyLabelTablet: { fontSize: 15, lineHeight: 20 },
    difficultyLabelSelected: { color: palette.primaryText },
    setupNotice: { color: palette.muted, fontSize: 12, lineHeight: 17, marginTop: 10 },
    setupFieldLabelTablet: { fontSize: 15, lineHeight: 20, marginBottom: 12 },
    setupNoticeTablet: { fontSize: 14, lineHeight: 20, marginTop: 12 },
    tabs: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-around', borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: palette.border, backgroundColor: palette.surface, paddingHorizontal: 34 },
    tab: { flex: 1, height: 58, alignItems: 'center', justifyContent: 'center', gap: 3 },
    tabLabel: { color: palette.muted, fontSize: 10, fontWeight: '600' },
    tabLabelSelected: { color: palette.primary },
    pressed: { opacity: 0.74, transform: [{ scale: 0.99 }] },
    disabled: { opacity: 0.42 },
  });
}
