// GENERATED by scripts/sync-locale-catalog.mjs from the JSON translation
// memory under translation-memory/es-419/. Edit the JSON sources and
// re-run the sync script; hand edits here will be overwritten.
// DRAFT: awaiting qualified native es-419 poker-language review.
import type { LearningContentCatalog } from '../learningContentChinese';

export const spanishLearningContent: LearningContentCatalog = {
  "cheatSheets": {
    "sheet-hand-rankings": {
      "groups": [
        {
          "title": "De la más fuerte a la más débil",
          "rows": [
            {
              "label": "Escalera de color",
              "detail": "Cinco cartas consecutivas del mismo palo"
            },
            {
              "label": "Póker",
              "detail": "Cuatro cartas del mismo valor"
            },
            {
              "label": "Full",
              "detail": "Trío más una pareja"
            },
            {
              "label": "Color",
              "detail": "Cinco cartas del mismo palo, no consecutivas"
            },
            {
              "label": "Escalera",
              "detail": "Cinco valores consecutivos en palos mixtos"
            },
            {
              "label": "Trío",
              "detail": "Tres cartas del mismo valor"
            },
            {
              "label": "Dos pares",
              "detail": "Dos parejas distintas"
            },
            {
              "label": "Un par",
              "detail": "Dos cartas del mismo valor"
            },
            {
              "label": "Carta más alta",
              "detail": "Ninguna combinación hecha de las anteriores"
            }
          ]
        },
        {
          "title": "Desempates",
          "rows": [
            {
              "label": "Misma categoría",
              "detail": "Compara primero la parte hecha y luego los kickers"
            },
            {
              "label": "El tablero juega",
              "detail": "Si ambos usan las mismas cinco cartas, el bote se divide"
            }
          ]
        }
      ],
      "note": "Los porcentajes son categorías finales aproximadas entre todas las manos aleatorias de Hold’em con siete cartas. No son tu probabilidad de formar la mano desde una mano inicial concreta, y no son tu probabilidad de ganar."
    },
    "sheet-position": {
      "groups": [
        {
          "title": "Antes del flop",
          "rows": [
            {
              "label": "Botón / ciega pequeña",
              "detail": "Pone la ciega pequeña y actúa primero"
            },
            {
              "label": "Ciega grande",
              "detail": "Pone la ciega grande y actúa en segundo lugar"
            }
          ]
        },
        {
          "title": "Después del flop",
          "rows": [
            {
              "label": "Ciega grande",
              "detail": "Actúa primero en el flop, el turn y el river"
            },
            {
              "label": "Botón",
              "detail": "Actúa último y tiene la ventaja de información"
            }
          ]
        }
      ]
    },
    "sheet-percentages": {
      "groups": [
        {
          "title": "Outs limpios",
          "rows": [
            {
              "label": "Outs: 4",
              "detail": "≈ 9% en la siguiente carta · 17% al river"
            },
            {
              "label": "Outs: 8",
              "detail": "≈ 17% en la siguiente carta · 32% al river"
            },
            {
              "label": "Outs: 9",
              "detail": "≈ 19% en la siguiente carta · 35% al river"
            },
            {
              "label": "Outs: 15",
              "detail": "≈ 32% en la siguiente carta · 54% al river"
            }
          ]
        },
        {
          "title": "Ante una apuesta",
          "rows": [
            {
              "label": "Medio bote",
              "detail": "25% de equidad de igualada requerida"
            },
            {
              "label": "Dos tercios del bote",
              "detail": "≈ 29% de equidad de igualada requerida"
            },
            {
              "label": "Tres cuartos del bote",
              "detail": "30% de equidad de igualada requerida"
            },
            {
              "label": "Bote completo",
              "detail": "33% de equidad de igualada requerida"
            }
          ]
        }
      ],
      "note": "Estas cifras asumen outs limpios y ninguna apuesta futura. Descuenta los outs que pueden formar una mano más fuerte para el rival."
    },
    "sheet-preflop": {
      "groups": [
        {
          "title": "Cómo leer la tabla",
          "rows": [
            {
              "label": "Parejas",
              "detail": "La diagonal de AA a 22"
            },
            {
              "label": "Del mismo palo",
              "detail": "Por encima de la diagonal; ambas cartas comparten palo"
            },
            {
              "label": "De distinto palo",
              "detail": "Por debajo de la diagonal; las cartas tienen palos distintos"
            }
          ]
        },
        {
          "title": "Ajusta antes de actuar",
          "rows": [
            {
              "label": "Asiento más temprano = más ajustado",
              "detail": "Más jugadores pueden despertar con una mano fuerte detrás de ti."
            },
            {
              "label": "La ciega grande defiende más amplio",
              "detail": "Ya invertiste 1 ciega grande, así que una subida pequeña ofrece un mejor precio."
            },
            {
              "label": "Los stacks profundos favorecen las manos del mismo palo",
              "detail": "Las manos conectadas del mismo palo ganan valor cuando se pueden ganar más fichas después del flop."
            }
          ]
        }
      ],
      "note": "Esta es una referencia inicial explicable para principiantes, no una tabla de solver. Las tendencias del rival y el tamaño de subida siguen importando."
    },
    "sheet-advanced-math": {
      "groups": [
        {
          "title": "Verificaciones de valor futuro",
          "rows": [
            {
              "label": "Probabilidades implícitas",
              "detail": "Añade solo fichas futuras realistas ganadas tras mejorar."
            },
            {
              "label": "Probabilidades inversas implícitas",
              "detail": "Descuenta las mejoras que pueden formar una costosa segunda mejor mano."
            },
            {
              "label": "Stack efectivo",
              "detail": "El valor futuro no puede exceder el stack vivo más pequeño."
            }
          ]
        },
        {
          "title": "Retiros necesarios para un farol puro",
          "rows": [
            {
              "label": "Medio bote",
              "detail": "Arriesga 0.5 del bote para ganar 1 · alrededor de 33%"
            },
            {
              "label": "Dos tercios del bote",
              "detail": "Arriesga 0.67 del bote para ganar 1 · alrededor de 40%"
            },
            {
              "label": "Bote completo",
              "detail": "Arriesga 1 bote para ganar 1 · 50%"
            }
          ]
        }
      ],
      "note": "Los umbrales de farol puro asumen equidad cero al ser igualados y ninguna acción futura. Los semifaroles necesitan menos retiros, pero solo cuando su equidad de mejora es limpia y realizable."
    }
  },
  "lessons": {
    "lesson-hand-rankings": {
      "sections": [
        {
          "heading": "Usa las mejores cinco cartas",
          "body": "Texas Hold’em te da siete cartas disponibles: dos cartas de mano y cinco cartas comunitarias. Tu resultado siempre es la combinación de cinco cartas más fuerte. Puedes usar ambas cartas de mano, una sola o ninguna.",
          "takeaway": "No agregues una sexta carta para desempatar. Solo cuentan las mejores cinco cartas.",
          "example": {
            "title": "Ejemplo · escalera real",
            "detail": "A♠ K♠ más Q♠ J♠ 10♠ forman la escalera de color con as alto de cinco cartas. El par de doses no importa."
          }
        },
        {
          "heading": "Ordena las manos de la más rara a la más común",
          "body": "Escalera de color, póker, full house, color, escalera, trío, dos pares, un par y, al final, carta más alta.",
          "bullets": [
            "El color vence a la escalera.",
            "El full house vence al color.",
            "El as puede ser la carta más alta en A-K-Q-J-10 o la más baja en A-2-3-4-5, pero no puede conectar los dos extremos."
          ]
        },
        {
          "heading": "Desempata en orden",
          "body": "Compara primero la parte que forma la mano y luego los kickers restantes, del más alto al más bajo. Si las mismas cinco cartas juegan para ambos jugadores, el bote se divide.",
          "takeaway": "Con un par, compara el par, luego el kicker más alto y después los otros dos kickers."
        }
      ]
    },
    "lesson-position-blinds": {
      "sections": [
        {
          "heading": "Las ciegas crean acción",
          "body": "La ciega pequeña y la ciega grande son apuestas obligatorias que se pagan antes de repartir las cartas. En el juego cara a cara, el botón paga la ciega pequeña y actúa primero antes del flop.",
          "example": {
            "title": "Ejemplo · mano en el botón",
            "detail": "Con A♠ J♠ en el botón cara a cara, pagas la ciega pequeña y actúas primero preflop, pero actúas al final en el turn y el river."
          }
        },
        {
          "heading": "El orden se invierte después del flop",
          "body": "Después del flop, la ciega grande actúa primero y el botón actúa al final. Actuar al final vale mucho porque ves la decisión del otro jugador antes de tomar la tuya.",
          "takeaway": "La posición es información. Normalmente puedes jugar más manos en el botón que fuera de posición."
        },
        {
          "heading": "El botón rota en cada mano",
          "body": "El botón se alterna en el juego cara a cara, así que los dos jugadores se turnan para pagar cada ciega y recibir la ventaja posicional."
        }
      ]
    },
    "lesson-actions-order": {
      "sections": [
        {
          "heading": "Cuando nadie ha apostado",
          "body": "Puedes pasar y ceder la acción sin agregar fichas, o apostar y fijar un precio. Una ronda termina cuando todos los jugadores activos igualan la misma apuesta y no queda acción por hacer."
        },
        {
          "heading": "Cuando enfrentas una apuesta",
          "body": "Puedes retirarte, igualar la cantidad necesaria para cubrir la apuesta o subir a un total mayor. Una subida normal en no limit debe ser al menos tan grande como la apuesta o subida completa anterior.",
          "bullets": [
            "Retirarse renuncia a tu derecho al bote.",
            "Igualar paga el precio actual.",
            "Subir aumenta el precio para el rival."
          ],
          "example": {
            "title": "Ejemplo · par más proyecto",
            "detail": "Q♥ J♥ en J♠ 8♥ 2♥ tiene el par superior y un proyecto de color. Ante una apuesta, compara retirarte, igualar y una subida legal, no solo las cartas."
          }
        },
        {
          "heading": "All-in es un límite de fichas, no una mano especial",
          "body": "Un jugador puede apostar todas las fichas que le quedan. Un all-in corto puede ser menor que una subida completa y puede que no reabra el derecho a subir. RiverMind calcula los límites legales por ti.",
          "takeaway": "Antes de elegir una acción, identifica el precio de igualar, el tamaño del bote y quién actúa después."
        }
      ]
    },
    "lesson-starting-hands": {
      "sections": [
        {
          "heading": "Empieza por la calidad de las cartas",
          "body": "Los pares pueden formar manos fuertes de un par o tríos ocultos. Las cartas altas forman pares superiores más fuertes. Las cartas del mismo palo y conectadas ganan maneras de completar colores y escaleras, pero esas ventajas son menores de lo que muchos principiantes esperan.",
          "example": {
            "title": "Ejemplo · estructura premium",
            "detail": "A♠ K♠ combina dos cartas altas, el mismo palo y conexión de escalera. Cada característica agrega maneras útiles de continuar después del flop."
          }
        },
        {
          "heading": "La posición cambia el umbral",
          "body": "En el botón cara a cara actúas al final después del flop, así que puedes entrar de forma rentable con más manos. Desde la ciega grande ya tienes fichas invertidas, pero actuarás primero postflop.",
          "takeaway": "Una mano puede ser una subida en el botón y una retirada ante mucha presión fuera de posición."
        },
        {
          "heading": "Sube con un propósito",
          "body": "Una subida preflop puede ganar las ciegas, construir valor con manos más fuertes y evitar revelar tu fuerza exacta. Usa la tabla inicial como referencia de aprendizaje y luego ajústala al comportamiento del rival."
        }
      ]
    },
    "lesson-outs-equity-odds": {
      "sections": [
        {
          "heading": "Cuenta los outs limpios",
          "body": "Un out es una carta sin ver que probablemente mejore tu mano hasta la ganadora. No cuentes una carta como limpia cuando también puede completar una mano más fuerte del rival.",
          "example": {
            "title": "Ejemplo · proyecto del mejor color",
            "detail": "A♥ 5♥ en K♥ 8♣ 2♥ deja cuatro corazones visibles, así que quedan nueve corazones sin ver que completan un color con as alto."
          }
        },
        {
          "heading": "Haz una estimación rápida",
          "body": "Con una carta por venir, multiplica los outs limpios por 2. Desde el flop con dos cartas por venir, multiplica por 4. La regla del 4 pierde precisión con muchos outs, así que úsala como cálculo de mesa, no como calculadora exacta.",
          "bullets": [
            "9 outs de color: alrededor de 19% en la siguiente carta.",
            "9 outs de color: alrededor de 35% para el river.",
            "8 outs de escalera: alrededor de 17% en la siguiente carta."
          ]
        },
        {
          "heading": "Compara la equidad con el precio",
          "body": "La equidad necesaria para igualar es la cantidad que igualas dividida entre el bote final después de tu igualada. Igualar 50 en un bote que queda en 200 requiere 25% de equidad antes de considerar la acción futura.",
          "takeaway": "Iguala cuando tu equidad realista supere el punto de equilibrio con margen suficiente para cubrir la incertidumbre y las decisiones futuras."
        }
      ]
    },
    "lesson-value-bluffs": {
      "sections": [
        {
          "heading": "Las apuestas por valor las igualan manos peores",
          "body": "Una apuesta por valor funciona cuando suficientes manos peores pueden igualar. El mejor tamaño no es automáticamente el más grande; elige un tamaño contra el que esas manos peores puedan continuar de forma realista.",
          "example": {
            "title": "Ejemplo · candidata a apuesta por valor",
            "detail": "A♠ Q♦ en Q♣ 7♥ 3♠ puede ser igualada por damas más débiles, sietes, pares y algunos proyectos. Nombra esas manos antes de elegir un tamaño."
          }
        },
        {
          "heading": "Los faroles hacen retirarse a mejores manos",
          "body": "Un farol necesita fold equity. Prefiere candidatas que bloqueen las igualadas fuertes, no bloqueen las retiradas y tengan poco valor en el showdown. Haz menos faroles contra jugadores que igualan demasiado.",
          "example": {
            "title": "Ejemplo · proyecto fallado",
            "detail": "Q♣ 5♣ falla en K♠ 9♣ 4♣ 2♦ 2♥. Fallar por sí solo no basta; esto se vuelve un farol solo cuando suficientes manos mejores pueden retirarse."
          }
        },
        {
          "heading": "Muchos buenos momentos para pasar no son ni valor ni farol",
          "body": "Pasar puede proteger una mano de fuerza media, materializar la equidad del proyecto o evitar que todas las manos peores se retiren. La agresión es útil solo cuando su propósito encaja con el rango y el tablero.",
          "takeaway": "Antes de apostar, nombra las manos peores que igualan o las manos mejores que se retiran."
        }
      ]
    },
    "lesson-preflop-opening-position": {
      "sections": [
        {
          "heading": "Primero identifica quién falta por actuar",
          "body": "Un bote sin abrir significa que nadie ha igualado ni subido antes que tú. La posición temprana exige manos más fuertes porque varios jugadores todavía pueden encontrar una mano premium. La posición tardía te permite abrir más manos porque quedan menos rangos y es más probable que actúes al final después del flop.",
          "takeaway": "Usa un rango de entrada más cerrado cuando más jugadores todavía esperan para actuar."
        },
        {
          "heading": "Sube en lugar de entrar solo pagando la ciega",
          "body": "Una subida puede ganar las ciegas de inmediato, construir valor con manos más fuertes y reducir la probabilidad de un bote lleno de jugadores. Como referencia simple de juego en efectivo, usa alrededor de 2.5 ciegas grandes cuando entras primero y mantén el mismo tamaño en todo tu rango de apertura.",
          "bullets": [
            "Posición temprana: prioriza pares, ases fuertes y cartas broadway fuertes.",
            "Cutoff y botón: agrega más ases del mismo palo, conectores del mismo palo y cartas altas jugables.",
            "Evita cambiar el tamaño solo porque tus cartas son fuertes o débiles."
          ]
        },
        {
          "heading": "Deja que la posición decida las manos límite",
          "body": "Una mano límite puede ser una retirada clara en posición temprana y una subida razonable en el botón. La posición no hace jugables todas las manos, pero mejora la frecuencia con la que robas las ciegas y lo bien que puedes materializar la equidad después del flop.",
          "takeaway": "Antes de mirar una tabla, pregúntate: ¿cuántos jugadores quedan? ¿Tendrás posición más adelante?",
          "example": {
            "title": "Ejemplo · la misma mano cambia",
            "detail": "A♠ 8♠ suele ser demasiado amplio para abrir primero desde posición temprana en una mesa de seis jugadores, pero se convierte en una subida práctica desde el botón después de que todos se retiran."
          }
        }
      ]
    },
    "lesson-preflop-limpers": {
      "sections": [
        {
          "heading": "Entrar pagando la ciega cambia el bote, no tu objetivo",
          "body": "El jugador que entra pagando la ciega iguala una ciega grande sin subir. Su rango suele estar limitado o ser desigual, pero los jugadores detrás aún pueden aparecer con manos fuertes. Empieza preguntándote si tu mano busca valor, un flop barato con varios jugadores o ninguna inversión."
        },
        {
          "heading": "Aísla con fuerza y posición",
          "body": "Sube manos que estén adelante del rango probable del jugador que entró pagando y que jueguen bien si las igualan. Agrega alrededor de una ciega grande a tu tamaño normal de apertura por cada jugador que entró pagando, y añade un poco más cuando quedes fuera de posición.",
          "bullets": [
            "Un jugador que entró pagando delante: alrededor de 4 a 5 ciegas grandes es una referencia útil para principiantes.",
            "Elige manos que formen pares fuertes o proyectos robustos, no manos débiles de distinto palo.",
            "Más jugadores que entran pagando crean una recompensa mayor, pero también hacen que el aislamiento sea menos probable."
          ]
        },
        {
          "heading": "Igualar detrás es una decisión selectiva",
          "body": "Algunos pares pequeños y manos conectadas del mismo palo pueden igualar detrás cuando las pilas son profundas y es probable que varios jugadores vean el flop. No entres pagando con manos débiles solo porque el precio parece barato; las situaciones difíciles de dominación inversa pueden costarte mucho más después.",
          "takeaway": "Sube para aislar con una ventaja clara; iguala detrás solo con una mano y una profundidad de pila que se beneficien de un bote con varios jugadores.",
          "example": {
            "title": "Ejemplo · aislamiento por valor",
            "detail": "K♠ Q♠ en el botón después de que el cutoff entró pagando la ciega es lo bastante fuerte para subir por valor y tratar de jugar cara a cara en posición."
          }
        }
      ]
    },
    "lesson-preflop-facing-raise": {
      "sections": [
        {
          "heading": "La posición del que abre define su rango",
          "body": "Una subida desde posición temprana suele representar un rango más fuerte que una subida desde el botón. Continúa más cerrado contra aperturas tempranas y más amplio contra aperturas tardías. Tu propia posición también importa: igualar en el botón es más fácil de materializar que igualar desde la ciega pequeña.",
          "takeaway": "Nunca juzgues tus dos cartas por separado; compáralas con la posición del que abre y con los jugadores de atrás."
        },
        {
          "heading": "Dale a cada respuesta una función",
          "body": "Retírate con manos dominadas o que no pueden materializar suficiente equidad. Iguala manos que jueguen bien al precio ofrecido, sobre todo en posición. Vuelve a subir con manos premium por valor y usa solo un conjunto pequeño y deliberado de faroles con buenos blockers.",
          "bullets": [
            "Las resubidas por valor buscan que manos fuertes peores continúen.",
            "Las igualadas necesitan suficiente equidad, jugabilidad y protección frente a los jugadores de atrás.",
            "Un as débil no es automáticamente una igualada; puede formar un par superior caro que queda como segunda mejor mano."
          ]
        },
        {
          "heading": "La presión crece con cada subida",
          "body": "Cuando enfrentas un 3-bet, el bote es más grande y los rangos son más fuertes. Continúa con la parte más alta de tu rango de apertura, considerando la posición y la profundidad de pila. Evita igualar solo para defender las fichas que ya invertiste.",
          "takeaway": "Cuando la acción se vuelve más fuerte, continúa con manos que siguen siendo robustas, no con manos que solo se ven atractivas por separado.",
          "example": {
            "title": "Ejemplo · evita la dominación",
            "detail": "A♦ J♣ en la ciega grande normalmente debería retirarse contra una apertura sólida desde posición temprana, mientras que la misma mano puede continuar con mucha más comodidad contra una subida pequeña desde el botón."
          }
        }
      ]
    },
    "lesson-preflop-blind-defense": {
      "sections": [
        {
          "heading": "Las fichas puestas mejoran el precio, no las cartas",
          "body": "Desde la ciega grande, igualas solo la diferencia entre tu ciega puesta y la subida. Ese descuento permite un rango de continuación más amplio, sobre todo contra aperturas pequeñas desde posición tardía. La ciega puesta ya está en el bote, así que no defiendas solo para evitar “perderla”."
        },
        {
          "heading": "El tamaño y la posición cambian la respuesta",
          "body": "Defiende más amplio contra una apertura pequeña del botón y más cerrado contra una apertura grande desde posición temprana. Las manos del mismo palo y conectadas materializan mejor la equidad que las manos de distinto palo sin conexión. Desde la ciega pequeña, cierra aún más porque la ciega grande todavía puede actuar y normalmente quedarás fuera de posición.",
          "bullets": [
            "Apertura más pequeña + posición más tardía = defensa más amplia.",
            "Apertura más grande + posición más temprana = defensa más cerrada.",
            "Prefiere manos que puedan formar pares fuertes, escaleras o colores."
          ]
        },
        {
          "heading": "Vuelve a subir por valor o presión útil",
          "body": "Haz 3-bet con tus manos más fuertes por valor. Algunos ases del mismo palo funcionan como manos de presión ocasionales porque bloquean los ases premium y conservan jugabilidad si los igualan. Evita hacer faroles con manos débiles aleatorias que no tienen blockers ni potencial postflop.",
          "takeaway": "Defiende porque el precio, los rangos y la jugabilidad funcionan juntos, no porque la ciega se sienta tuya.",
          "example": {
            "title": "Ejemplo · defensa sensible al precio",
            "detail": "8♠ 7♠ puede igualar una subida pequeña del botón desde la ciega grande, pero la misma mano suele retirarse cuando un jugador de posición temprana usa un tamaño grande."
          }
        }
      ]
    },
    "lesson-preflop-three-bet-plan": {
      "sections": [
        {
          "heading": "Empieza con las manos que quieren acción",
          "body": "Un 3-bet por valor debería alegrarse cuando el que abre continúa con un rango más débil. El límite exacto cambia con la posición: las damas y el as-rey son valor claro contra una apertura tardía, mientras que una apertura temprana cerrada exige una referencia más fuerte.",
          "takeaway": "Construye primero el núcleo de valor; no empieces buscando manos de farol."
        },
        {
          "heading": "Agrega manos de presión por razones estructurales",
          "body": "Los mejores 3-bets de farol ocasionales bloquean las continuaciones premium y conservan equidad útil si los igualan. Los ases bajos del mismo palo son candidatos comunes porque un as elimina combinaciones de ases, as-rey y as-dama, mientras que la carta baja puede formar escaleras y colores.",
          "bullets": [
            "Prefiere blockers contra las continuaciones más fuertes del que abre.",
            "Prefiere cartas del mismo palo o conectadas que puedan mejorar de más de una manera.",
            "Evita manos débiles de distinto palo al azar que formen pares dominados si las igualan."
          ],
          "example": {
            "title": "Ejemplo · blocker más jugabilidad",
            "detail": "A♠ 5♠ en la ciega grande puede hacer 3-bet de vez en cuando a una apertura del botón. Bloquea los ases premium y aún puede formar escaleras de as bajo o el mejor color."
          }
        },
        {
          "heading": "Usa la posición para elegir el tamaño",
          "body": "Fuera de posición, usa un tamaño mayor porque el que abrió materializará la equidad más fácilmente si iguala. Contra una apertura de 2.5 ciegas grandes con 100 ciegas grandes, alrededor de 8 ciegas grandes en posición y de 9 a 11 ciegas grandes fuera de posición son referencias prácticas de aprendizaje. Agrega más cuando un igualador crea una situación de squeeze.",
          "takeaway": "Antes de subir, ten claro si la mano es por valor o de presión, el tamaño que usarás y cómo responderás a un 4-bet."
        }
      ]
    },
    "lesson-preflop-facing-three-bet": {
      "sections": [
        {
          "heading": "Reinicia la decisión después de la resubida",
          "body": "Un 3-bet crea un precio nuevo contra un rango más cerrado. Las fichas de tu subida de apertura ya no te pertenecen. Compara la mano, las posiciones, el tamaño y la pila efectiva desde la decisión actual, en lugar de igualar para defender la inversión anterior.",
          "takeaway": "Trata la subida de apertura como un costo hundido y evalúa el bote nuevo con honestidad."
        },
        {
          "heading": "Las igualadas necesitan posición y jugabilidad robusta",
          "body": "Las broadways del mismo palo en posición y algunos pares pueden igualar un 3-bet normal porque materializan equidad y forman combinaciones fuertes. Fuera de posición, cierra el rango de igualada: las cartas altas de distinto palo dominadas suelen formar pares caros de segunda mejor mano en un bote inflado.",
          "bullets": [
            "Iguala más a menudo en posición y contra un tamaño razonable.",
            "Retírate más a menudo fuera de posición o contra un rango que abrió desde posición temprana.",
            "No uses una igualada solo para que no te hagan un farol."
          ],
          "example": {
            "title": "Ejemplo · la posición protege la equidad",
            "detail": "K♠ Q♠ en el botón puede igualar un 3-bet normal de la ciega grande con más comodidad de la que K♦ Q♣ tiene para igualar un 3-bet de la ciega pequeña fuera de posición."
          }
        },
        {
          "heading": "Haz 4-bet con un plan para la última subida",
          "body": "Haz 4-bet con la parte más alta del rango por valor y usa solo un componente pequeño de faroles basados en blockers. La profundidad de pila determina el compromiso: con 100 ciegas grandes un 4-bet compacto puede dejar espacio para retirar faroles seleccionados, mientras que las pilas más cortas llevan las manos fuertes al compromiso directo.",
          "takeaway": "Elige retirarte, igualar o hacer 4-bet antes de que la emoción entre en el bote grande, y ten claro qué significaría un 5-bet."
        }
      ]
    },
    "lesson-postflop-board-texture": {
      "sections": [
        {
          "heading": "Empieza por la conexión y los palos",
          "body": "Los tableros secos contienen pocos proyectos de escalera o color inmediatos. Los tableros húmedos conectan muchos valores o comparten palos, así que más manos pueden mejorar o ya ser fuertes. La textura describe cómo interactúan los rangos con el tablero, no si las cartas se ven altas o bajas.",
          "bullets": [
            "Seco: valores sin conexión con tres palos.",
            "Húmedo: valores conectados, proyectos emparejados o dos cartas del mismo palo.",
            "Los tableros emparejados reducen algunas combinaciones y pueden hacer posible un trío."
          ]
        },
        {
          "heading": "Compara ambos rangos con el tablero",
          "body": "El que subió preflop suele tener más combinaciones de carta alta, mientras que un igualador puede tener más conectores del mismo palo y pares pequeños. Un tablero seco y alto puede favorecer al que subió; un tablero bajo y conectado puede interactuar fuertemente con el igualador.",
          "example": {
            "title": "Ejemplo · par superior estable",
            "detail": "A♠ Q♦ en Q♣ 7♥ 2♠ es el par superior en un tablero seco. Pocas cartas del turn completan un proyecto evidente, así que muchos pares más débiles pueden continuar."
          }
        },
        {
          "heading": "Nombra las cartas que cambian el plan",
          "body": "Antes de actuar, identifica turns o rivers que completen proyectos, creen una overcard, emparejen el tablero o dejen la textura casi sin cambios. Planificar por clases de cartas es más útil que intentar predecir una carta exacta.",
          "takeaway": "Lee primero la textura y luego pregúntate qué rango conecta mejor y qué cartas futuras cambian esa ventaja."
        }
      ]
    },
    "lesson-postflop-continuation-bets": {
      "sections": [
        {
          "heading": "Una subida preflop no obliga a apostar en el flop",
          "body": "Una apuesta de continuación es simplemente una apuesta en el flop del agresor preflop. Funciona mejor cuando tu rango tiene ventaja, el tablero es estable y un rival debe defender. Pasar es parte de una estrategia completa, no una admisión de que fallaste."
        },
        {
          "heading": "Usa apuestas pequeñas donde muchas manos se benefician",
          "body": "En tableros secos y altos, una apuesta pequeña puede ganar retiradas de manos sin par arriesgando poco. Las manos fuertes también usan este tamaño para que la apuesta no revele si conectaste.",
          "example": {
            "title": "Ejemplo · apuesta de rango pequeña",
            "detail": "Después de subir preflop, A♠ K♦ suele poder apostar pequeño cuando le pasan en Q♣ 7♥ 2♠ cara a cara. Tu rango contiene muchas damas fuertes y overpairs, y el tablero ofrece pocos proyectos poderosos."
          }
        },
        {
          "heading": "Pasa más en tableros húmedos o con varios jugadores",
          "body": "Los tableros conectados crean más igualadas y subidas fuertes. Los rivales extra hacen más probable que alguien haya conectado. Pasa más a menudo con manos que fallaron y de fuerza media cuando el tablero favorece los rangos de igualada o quedan varios jugadores.",
          "takeaway": "Apuesta de continuación porque el rango y el tablero lo respaldan, no simplemente porque subiste preflop."
        }
      ]
    },
    "lesson-postflop-value-sizing": {
      "sections": [
        {
          "heading": "El valor empieza con un rango de igualada",
          "body": "Una apuesta por valor gana dinero cuando suficientes manos más débiles pueden igualar. Antes de elegir un tamaño, nombra esas manos: pares superiores más débiles, segundos pares, pares en mano o proyectos. Si no puedes nombrar igualadores débiles realistas, pasar puede proteger tu valor en el showdown."
        },
        {
          "heading": "Deja que la textura y el rango definan el tamaño",
          "body": "Las apuestas pequeñas mantienen involucrado un rango débil amplio en tableros secos. Las apuestas más grandes pueden cobrar a los proyectos o apuntar a un rango fuerte más cerrado en tableros húmedos. No apuestes más grande automáticamente solo porque tu propia mano es fuerte.",
          "example": {
            "title": "Ejemplo · objetivo de valor en el turn",
            "detail": "A♠ Q♦ en Q♣ 8♥ 3♠ 6♦ puede apostar alrededor de medio bote después de que el rival vuelve a pasar. Damas más débiles, ochos, pares en mano y proyectos disponibles todavía pueden continuar."
          }
        },
        {
          "heading": "Reevalúa con cada carta nueva",
          "body": "Una carta del turn puede agregar proyectos o fortalecer al igualador. El river elimina toda la equidad futura y suele reducir las manos que pueden igualar. Reconstruye el objetivo de valor en lugar de repetir por costumbre el tamaño de la ronda anterior.",
          "takeaway": "Primero nombra las manos más débiles que igualan; luego elige el tamaño que esas manos pueden pagar de forma realista."
        }
      ]
    },
    "lesson-postflop-playing-draws": {
      "sections": [
        {
          "heading": "Cuenta solo los outs limpios",
          "body": "Un out limpio normalmente te mejora hasta la mano ganadora. Una carta de color que también empareja el tablero, o una carta de escalera que completa una escalera más alta, puede descontarse. Empieza con el proyecto visible y luego quita las mejoras dudosas.",
          "example": {
            "title": "Ejemplo · proyecto de color fuerte",
            "detail": "9♥ 8♥ en Q♥ 7♣ 2♥ tiene nueve outs de color aparentes más un potencial de escalera útil. El valor exacto sigue dependiendo de si un rival puede tener un proyecto de corazones más alto."
          }
        },
        {
          "heading": "Compara la equidad con el bote final",
          "body": "Para una igualada, divide la cantidad que igualas entre el bote después de tu igualada. Una apuesta de medio bote en el flop ofrece un precio de equilibrio de 25%. Nueve outs limpios de color llegan al river alrededor de 35% de las veces, antes de considerar apuestas futuras u outs sucios."
        },
        {
          "heading": "Haz semi-farol cuando ambos caminos importan",
          "body": "Un semi-farol puede ganar de inmediato por retiradas o más tarde completando el proyecto. Prefiere proyectos robustos, blockers útiles y rivales capaces de retirarse. Igualar suele ser más limpio cuando el precio es bueno y el fold equity es incierto.",
          "takeaway": "No subas solo porque tienes un proyecto; sube cuando la equidad de mejora y un fold equity creíble funcionan juntos."
        }
      ]
    },
    "lesson-postflop-river-decisions": {
      "sections": [
        {
          "heading": "El river no tiene equidad futura",
          "body": "No quedan cartas, así que los proyectos se completaron o fallaron. Cada apuesta debe tener un propósito en presente: que manos peores igualen o que manos mejores se retiren. Las manos de fuerza media suelen preferir pasar y llegar al showdown."
        },
        {
          "heading": "Apuesta por valor tan fino como el rango permita",
          "body": "Las manos fuertes de un par todavía pueden apostar por valor en rivers seguros cuando varios pares más débiles igualan. Elige el tamaño según el objetivo. Una apuesta más pequeña puede ganar más de un rango atrapa-faroles amplio que una apuesta grande que solo igualan manos fuertes.",
          "example": {
            "title": "Ejemplo · umbral de la carta atrapa-faroles",
            "detail": "K♠ Q♠ en K♦ 8♣ 6♥ 3♠ 2♦ sigue siendo el par superior, pero ante una apuesta grande y polarizada en el river puede que solo le gane a faroles. La igualada depende del precio y de la frecuencia de farol esperada."
          }
        },
        {
          "heading": "Atrapa faroles con evidencia, no con curiosidad",
          "body": "Una carta atrapa-faroles pierde con todas las manos de valor y solo les gana a los faroles. Compara el precio de igualar con una estimación realista de faroles y luego considera los blockers y las tendencias del rival. Retirar una mano que se ve fuerte puede ser correcto contra un rango con demasiado valor.",
          "takeaway": "En el river, nombra las manos peores que igualan, las mejores que se retiran o los faroles que vences antes de comprometer más fichas."
        }
      ]
    },
    "lesson-postflop-range-advantage": {
      "sections": [
        {
          "heading": "La ventaja de rango no es tu mano exacta",
          "body": "Un rango tiene ventaja cuando todas sus manos probables promedian más equidad que el rango del rival en este tablero. Quien sube preflop suele tener más ases fuertes y overpairs en flops altos y desconectados, incluso cuando las dos cartas que tienes no conectaron.",
          "takeaway": "Pregunta qué rango completo conecta mejor antes de preguntar si tu mano exacta quiere apostar."
        },
        {
          "heading": "La ventaja de nuts controla los botes más grandes",
          "body": "La ventaja de nuts pertenece al rango con más combinaciones cerca de la cima de las manos posibles. Quien iguala puede tener más dos pares y escaleras en tableros bajos y conectados incluso cuando quien subió conserva una pequeña ventaja de equidad promedio. El rango sin la ventaja de nuts debe usar menos apuestas grandes.",
          "example": {
            "title": "Ejemplo · quien iguala tiene más manos fuertes",
            "detail": "En 8♠ 7♥ 6♠, la ciega grande puede tener más dos pares, tríos y escaleras hechas que una apertura del cutoff. Quien abrió debería pasar a menudo en lugar de forzar una continuación grande."
          }
        },
        {
          "heading": "Cada jugador extra fortalece el campo que continúa",
          "body": "En botes de varios jugadores, al menos un rival conecta más a menudo y cada jugador debe continuar contra varios rangos. Farolea menos, apuesta por valor de forma más selectiva y evita asumir que una subida preflop te da permiso para presionar a toda la mesa.",
          "takeaway": "A medida que sube el número de jugadores, exige un respaldo de rango más fuerte y un objetivo más claro antes de apostar."
        }
      ]
    },
    "lesson-postflop-three-bet-pots": {
      "sections": [
        {
          "heading": "La acción preflop estrecha ambos rangos",
          "body": "Un bote de 3-bet comienza con más parejas premium, ases fuertes y cartas broadway que un bote subido una vez. El bote inicial más grande también baja el SPR, así que una o dos apuestas posflop pueden comprometer una parte significativa del stack.",
          "takeaway": "No copies las frecuencias de un bote subido una vez en un bote de 3-bet sin reconstruir ambos rangos."
        },
        {
          "heading": "Los tableros altos y secos suelen admitir presión pequeña",
          "body": "Quien hace 3-bet suele tener más A-K, A-Q y overpairs. En un flop con as o rey alto y desconectado, una apuesta pequeña puede funcionar con gran parte de ese rango porque quien iguala tiene menos manos muy fuertes y pocos proyectos urgentes.",
          "example": {
            "title": "Ejemplo · apuesta pequeña favorable al rango",
            "detail": "Tras hacer 3-bet en el botón y ser igualado, K♠ Q♣ puede apostar poco en A♦ 7♣ 2♥. La ventaja de rango aporta presión aunque la mano exacta falló."
          }
        },
        {
          "heading": "Los tableros conectados exigen contención",
          "body": "Los tableros bajos conectados y de dos palos le dan a quien iguala más tríos, dos pares y proyectos fuertes. Pasa más a menudo, sobre todo con cartas altas sin pareja. Al apostar, usa un tamaño y una selección de manos que resistan subidas y turns difíciles.",
          "takeaway": "Un bote preflop más grande aumenta el costo de la agresión automática; deja que la conexión con el tablero elija el plan del flop."
        }
      ]
    },
    "lesson-postflop-turn-barrels": {
      "sections": [
        {
          "heading": "Clasifica lo que cambió el turn",
          "body": "Un turn puede favorecer al agresor, favorecer a quien igualó, completar un proyecto, añadir proyectos nuevos o cambiar casi nada. Reconstruye la comparación de rangos antes de repetir la acción del flop. Una carta que parece inofensiva puede mejorar las parejas y los proyectos de quien igualó."
        },
        {
          "heading": "Encadena cuando quedan dos caminos para ganar",
          "body": "Las manos fuertes de valor pueden cobrar a manos hechas más débiles y a proyectos. Los semifaroles funcionan mejor cuando pueden mejorar y también hacer retirar manos mejores. Cartas altas, proyectos de color, proyectos de escalera y bloqueadores útiles pueden combinarse en una segunda apuesta creíble.",
          "example": {
            "title": "Ejemplo · equidad más presión",
            "detail": "A♥ 5♥ en K♥ 7♣ 2♥ Q♠ conserva el proyecto de color asalto y bloquea continuaciones fuertes de as alto. Tras una apuesta de flop igualada, puede usar una segunda apuesta controlada contra un rango con muchas manos de una pareja."
          }
        },
        {
          "heading": "Abandona cuando la historia y la equidad desaparecen",
          "body": "Una apuesta de flop igualada elimina muchos retiros automáticos. Si el turn fortalece a quien igualó, tu mano tiene poca equidad de mejora y tus bloqueadores quitan retiros en lugar de sumar igualadas, pasar es disciplina, no pasividad. Guarda fichas para un mejor candidato.",
          "takeaway": "Antes de encadenar, nombra las igualadas más débiles, las manos mejores que se retirarían y las cartas que aún pueden mejorar tu mano."
        }
      ]
    },
    "lesson-postflop-river-polarization": {
      "sections": [
        {
          "heading": "Empieza por el objetivo, no por el botón",
          "body": "Sin cartas por venir, una apuesta de river debe ser igualada por manos peores o hacer retirar manos mejores. Nombra esas manos antes de elegir un tamaño. Si ninguno de los dos grupos es realista, pasar suele ser la referencia disciplinada.",
          "takeaway": "Un tamaño de river solo es útil cuando su rango objetivo está claro."
        },
        {
          "heading": "Mantén invitante el valor fino",
          "body": "Las manos fuertes de una pareja pueden apostar por valor en rivers seguros cuando parejas más débiles aún igualan. Los tamaños pequeños mantienen interesados a esos atrapa-faroles. Apostar demasiado puede hacer retirar las manos que vences y aislar contra manos más fuertes.",
          "example": {
            "title": "Ejemplo · da precio a los reyes más débiles",
            "detail": "K♠ Q♣ en K♦ 9♣ 5♥ 3♠ 2♦ puede usar una apuesta de river pequeña tras tres pases de la ciega grande. Reyes peores y algunas parejas pueden igualar; una sobreapuesta atacaría un rango mucho más estrecho."
          }
        },
        {
          "heading": "Polariza cuando el rango lo sostiene",
          "body": "Las apuestas grandes representan valor muy fuerte o faroles, y dejan las manos de fuerza media en el rango de pase. Elige faroles que bloqueen las igualadas probables y que no bloqueen los retiros probables. El tamaño y la selección de manos deben contar la misma historia.",
          "takeaway": "Las apuestas grandes de river necesitan un rango polarizado, no solo confianza en una mano."
        }
      ]
    },
    "lesson-postflop-river-bluff-catchers": {
      "sections": [
        {
          "heading": "Un atrapa-faroles solo vence faroles",
          "body": "Cuando tu mano pierde contra toda apuesta de valor, su fuerza absoluta importa menos que la mezcla de valor y faroles del rival. Cuenta los proyectos fallidos plausibles y las combinaciones de valor a partir de toda la acción, no solo de la carta del river.",
          "takeaway": "No iguales porque la mano parezca fuerte; iguala porque quedan suficientes faroles."
        },
        {
          "heading": "Deja que el precio fije el umbral",
          "body": "Divide la igualada entre el bote final tras igualar. Igualar 8 ciegas grandes para ganar un bote final de 40 necesita 20% de equidad, mientras que igualar 30 para ganar 84 necesita alrededor de 36%. Una apuesta más grande exige una lectura de farol mucho más fuerte.",
          "example": {
            "title": "Ejemplo · la misma mano, un precio distinto",
            "detail": "A♣ J♣ en J♦ 8♠ 6♥ 3♣ 2♠ puede igualar una apuesta de river pequeña contra proyectos fallidos, pero retirarse ante una sobreapuesta grande de una línea cargada de valor. La mano no cambió; la frecuencia de farol requerida sí."
          }
        },
        {
          "heading": "Usa los bloqueadores como evidencia de apoyo",
          "body": "Un atrapa-faroles útil puede bloquear valor dejando disponibles los proyectos fallidos. El perfil de bloqueadores opuesto puede empeorar una igualada tentadora. Los bloqueadores afinan una estimación realista del rango; no rescatan una línea con demasiado pocos faroles naturales.",
          "takeaway": "Combina precio, acción y bloqueadores; nunca uses una sola pista de forma aislada."
        }
      ]
    },
    "lesson-tournament-stack-zones": {
      "sections": [
        {
          "heading": "Las ciegas grandes hacen comparables los stacks",
          "body": "Un conteo de fichas solo tiene sentido junto a las ciegas actuales. Divide el stack efectivo entre la ciega grande antes de cada decisión importante. Cuarenta ciegas grandes dejan espacio para varias fases; doce ciegas grandes pueden hacer que una subida preflop comprometa gran parte del stack.",
          "takeaway": "Recalcula el stack efectivo en ciegas grandes cuando suban las ciegas o cuando entre al bote un jugador más corto."
        },
        {
          "heading": "Usa las zonas como recordatorios de planificación",
          "body": "Por encima de unas 30 ciegas grandes siguen disponibles las subidas normales y los planes posflop. Entre 16 y 30 ciegas grandes, usa tamaños eficientes y planifica la respuesta a un all-in. Con 15 ciegas grandes o menos, muchas decisiones de primero en actuar se simplifican hacia all-in o retiro, porque una subida pequeña puede crear un bote comprometido incómodo.",
          "bullets": [
            "Profundo: conserva espacio posflop y evita all-ins innecesarios.",
            "Medio: sube con eficiencia y conoce la respuesta a un all-in.",
            "Corto: prioriza el fold equity y evita igualadas especulativas que consumen el stack."
          ]
        },
        {
          "heading": "El stack activo más corto define la decisión",
          "body": "El stack efectivo es lo máximo que cualquiera de los dos puede perder en la mano. Si tienes 40 ciegas grandes y el rival tiene 12, la decisión cara a cara se comporta como un bote de 12 ciegas grandes. Las fichas extra detrás no crean probabilidades implícitas adicionales contra ese jugador.",
          "takeaway": "Usa el stack vivo más pequeño —no tu propio conteo de fichas— para elegir el plan de compromiso.",
          "example": {
            "title": "Ejemplo · el stack efectivo, no el mostrado",
            "detail": "Tienes 38 ciegas grandes en el botón con A♠ 9♠, pero la ciega grande tiene 13. Planifica el enfrentamiento alrededor de 13 ciegas grandes."
          }
        }
      ]
    },
    "lesson-tournament-short-stack-opens": {
      "sections": [
        {
          "heading": "La posición sigue controlando el rango de entrada",
          "body": "Los stacks cortos no convierten toda mano en un all-in. La posición temprana debe pasar por varios rangos vivos, mientras que el botón o la ciega pequeña pueden presionar a menos jugadores. Reduce las manos de distinto palo débiles en posición temprana y ataca con más selección cuando solo queden las ciegas.",
          "takeaway": "La urgencia del stack corto cambia el tamaño de la decisión, no el valor de la posición."
        },
        {
          "heading": "Usa la subida más pequeña que mantenga el plan claro",
          "body": "Con unas 18 a 30 ciegas grandes, una apertura de 2 a 2.25 ciegas grandes arriesga menos mientras aplica presión similar a un tamaño más grande de juego en efectivo. Antes de subir, decide qué manos igualarán, se retirarán o continuarán contra un all-in de cada jugador detrás.",
          "example": {
            "title": "Ejemplo · apertura eficiente con stack medio",
            "detail": "A♥ 10♥ en el botón de seis jugadores con 24 ciegas grandes puede abrir a unas 2.2 ciegas grandes y aún tomar una decisión deliberada contra cualquiera de las ciegas."
          }
        },
        {
          "heading": "Ve all-in cuando la subida pequeña no crea una rama útil",
          "body": "Con unas 15 ciegas grandes o menos, un all-in directo puede combinar fold equity inmediato con toda la equidad de la mano al ser igualado. Prefiere manos y posiciones que rindan razonablemente contra los rangos de igualada. Retira las manos que dependen de que varios rivales no despierten con fuerza.",
          "takeaway": "Un all-in es útil cuando elimina una incómoda decisión de subir y retirarse, no solo porque el stack se sienta incómodo."
        }
      ]
    },
    "lesson-tournament-reshoves-calls": {
      "sections": [
        {
          "heading": "Resube all-in contra el rango real de quien abrió",
          "body": "Una apertura de posición tardía suele comenzar más amplia que una de posición temprana. Con un stack corto, los ases fuertes y las parejas pueden resubir all-in por valor contra un rango amplio del botón, mientras que las mismas manos pueden necesitar cautela contra una apertura temprana disciplinada.",
          "takeaway": "No etiquetes una mano como “resubida all-in” sin nombrar la posición de quien abrió y su rango probable."
        },
        {
          "heading": "El dinero muerto ayuda solo después de la fuerza del rango",
          "body": "Las ciegas, los antes y una subida de apertura crean fichas que puedes ganar de inmediato. Esa recompensa puede respaldar un all-in, pero no hace rentables las manos dominadas contra un rango de continuación ajustado. Estima quién se retira, quién iguala y cómo rinde tu mano al ser igualada.",
          "example": {
            "title": "Ejemplo · resubida all-in de valor",
            "detail": "A♣ Q♣ con 16 ciegas grandes en la ciega grande puede resubir all-in sobre una apertura amplia del botón. Tiene una equidad fuerte al ser igualada y puede ganarse la apertura más las ciegas de inmediato."
          }
        },
        {
          "heading": "Igualar un all-in necesita evidencia más fuerte",
          "body": "Quien iguala no tiene fold equity, así que la mano debe vencer suficiente parte del rango de all-in al precio ofrecido. Iguala más amplio contra un all-in corto desde posición tardía y más ajustado contra uno desde posición temprana. Las fichas ya puestas mejoran el precio pero no borran el dominio.",
          "takeaway": "Para las igualadas, quita el fold equity de la historia y compara la mano directamente con el rango de all-in y el precio."
        }
      ]
    },
    "lesson-tournament-risk-premium": {
      "sections": [
        {
          "heading": "Ganancias iguales de fichas no siempre valen lo mismo en el torneo",
          "body": "En un juego en efectivo, ganar 10 fichas compensa perder 10 fichas. Cerca de la burbuja de un torneo, perder puede terminar el evento mientras que ganar la misma cantidad solo puede mejorar un stack que ya era seguro. Esa asimetría crea una prima de riesgo: un stack cubierto suele necesitar más equidad para igualar un all-in de lo que sugieren solas las probabilidades del bote.",
          "takeaway": "Usa las probabilidades en fichas como punto de partida y pregunta luego qué cuesta la eliminación en el estado actual del torneo."
        },
        {
          "heading": "La prima de riesgo cambia las igualadas más que la presión de primero en actuar",
          "body": "Igualar un all-in no tiene fold equity y puede terminar el torneo. Abrir o ir all-in primero todavía puede ganar sin oposición, así que un jugador puede presionar más manos e igualar menos. Evita el error común de volverse uniformemente ajustado en la burbuja.",
          "bullets": [
            "Los stacks medios cubiertos deben evitar igualadas de all-in marginales.",
            "Los líderes en fichas pueden presionar a stacks que no pueden igualar con comodidad.",
            "Los stacks cortos aún deben aprovechar las oportunidades rentables de primero en actuar."
          ]
        },
        {
          "heading": "Trata la guía de ICM de RiverMind como una referencia práctica",
          "body": "El ICM exacto depende de cada stack y de la estructura de pagos. RiverMind usa ajustes de riesgo acotados y explicables, no tablas de solver. Cuando los detalles de pagos o los rangos rivales sean inciertos, mantén la conclusión direccional: igualar más ajustado, presionar más amplio o casi ningún cambio significativo.",
          "takeaway": "Nunca presentes un ajuste de ICM simplificado como una tabla exacta del torneo.",
          "example": {
            "title": "Ejemplo · mismo bote, costo distinto",
            "detail": "Quedan tres jugadores y dos avanzan. Con A♠ 10♦, un stack medio cubierto por el líder debería rechazar una igualada de all-in marginal que podría ser razonable lejos de la burbuja."
          }
        }
      ]
    },
    "lesson-tournament-stack-coverage": {
      "sections": [
        {
          "heading": "La cobertura determina la amenaza de eliminación",
          "body": "Un jugador cubre a otro cuando puede ganar todo su stack. Si el líder en fichas va all-in contra ti, igualar y perder puede eliminarte. Si tú cubres a un stack corto, perder el mismo bote duele pero no necesariamente termina el evento. Esa diferencia cambia la interacción de rangos antes de considerar las cartas.",
          "takeaway": "Antes de una decisión de all-in, identifica quién cubre a quién y qué stacks sobreviven a una pérdida."
        },
        {
          "heading": "Los líderes presionan; los stacks medios evitan colisiones",
          "body": "Un líder puede abrir más a menudo cuando los rivales cubiertos deben proteger la supervivencia. Un stack medio debe ser especialmente cauto al jugar un bote enorme contra el líder mientras un stack más corto está cerca de la eliminación. Esto no significa retirar manos premium ni atacar a ciegas: cambia las ventajas marginales.",
          "example": {
            "title": "Ejemplo · el stack más corto importa",
            "detail": "Con stacks de 42, 21 y 6 ciegas grandes y dos plazas que avanzan, el stack de 21 ciegas grandes debería evitar una igualada ajustada contra el líder mientras el stack de 6 siga vivo."
          }
        },
        {
          "heading": "Los stacks cortos no pueden esperar para siempre",
          "body": "El stack más corto tiene menos valor de supervivencia que proteger y menos manos futuras antes de que las ciegas lo consuman. Su fold equity de primero en actuar suele ser su mejor activo. Aun así considera la posición y los rangos de igualada: “el más corto” no es permiso para pasar all-in con cualquier par de cartas por toda la mesa.",
          "takeaway": "La cobertura cambia el precio del fracaso, pero la calidad de la mano, la posición y el fold equity siguen determinando la acción."
        }
      ]
    },
    "lesson-tournament-bubble-decisions": {
      "sections": [
        {
          "heading": "Lee el estado del torneo antes de las cartas",
          "body": "Cuenta los jugadores restantes, identifica las plazas que pagan o clasifican, ordena los stacks vivos y anota la cobertura. Luego convierte el stack efectivo a ciegas grandes. Esto evita que un hábito familiar del juego en efectivo anule los incentivos reales del torneo.",
          "bullets": [
            "¿Cuántos jugadores quedan y cuántos avanzan?",
            "¿Quién es el más corto y quién te cubre?",
            "¿Es una igualada sin fold equity o una acción de primero en actuar?"
          ]
        },
        {
          "heading": "Cambia las decisiones marginales, no las obvias",
          "body": "La presión de la burbuja debe mover las decisiones cerradas hacia el retiro y la presión rentable de primero en actuar hacia la acción. No debe convertir una mano dominada en una igualada ni una mano premium en un retiro automático. Si la referencia del juego en efectivo está lejos del límite, el ajuste de torneo suele ser pequeño.",
          "takeaway": "Aplica la prima de riesgo en el borde del rango, no como razón para abandonar los fundamentos del póquer."
        },
        {
          "heading": "Enuncia el supuesto detrás de la recomendación",
          "body": "Una explicación útil de torneo nombra la relación de stacks y el supuesto de rango: “más ajustado porque el líder te cubre y queda un stack de seis ciegas grandes”, o “más amplio de primero en actuar porque solo quedan dos stacks limitados por el riesgo”. Si esa frase no se puede completar, el ajuste probablemente es demasiado vago.",
          "takeaway": "Un buen consejo de torneo nombra la fuente de presión en lugar de decir simplemente “ICM”.",
          "example": {
            "title": "Ejemplo · presión explicable",
            "detail": "Como líder con 35 ciegas grandes en el botón, K♣ 9♣ puede abrir con eficiencia contra dos stacks de 14 ciegas grandes que enfrentan la eliminación si continúan."
          }
        }
      ]
    },
    "lesson-opponents-evidence": {
      "sections": [
        {
          "heading": "Observa decisiones, no resultados",
          "body": "Un farol mostrado es un punto de datos, no la prueba de que alguien siempre farolea. Registra la situación pública: posición, precio, fase y si el jugador apostó, igualó, subió o se retiró. Un bote perdido puede contener una decisión fuerte, y un bote ganado puede contener un error.",
          "bullets": [
            "Los estilos paciente y pegajoso se separan por entradas repetidas y frecuencias de igualada.",
            "Los estilos de presión y engaño se separan por agresión repetida y por su momento.",
            "Contra un estilo equilibrado sin una fuga unidireccional repetida, mantén la referencia intacta."
          ],
          "takeaway": "Describe lo que ocurrió repetidamente antes de asignar una etiqueta al jugador."
        },
        {
          "heading": "Exige una muestra relevante",
          "body": "Dos manos son una pista; no son una lectura estable. Busca al menos tres decisiones similares y prefiere ocho o más manos observadas antes de hacer un ajuste significativo. Una lectura de soltura preflop no prueba automáticamente que el mismo jugador farolea demasiado en el river.",
          "bullets": [
            "Empareja la evidencia con el mismo tipo de situación.",
            "Reduce el ajuste cuando la muestra sea pequeña.",
            "Actualiza la lectura cuando las acciones nuevas discrepen."
          ]
        },
        {
          "heading": "Conserva la estrategia base debajo",
          "body": "Una explotación debe ser un cambio medido desde una base sólida. Con evidencia débil, elige la decisión normal de rango y precio. Con evidencia repetida, cambia la frecuencia o el tamaño gradualmente en lugar de saltar a un extremo.",
          "takeaway": "La confianza determina el tamaño del ajuste, no solo la dirección.",
          "example": {
            "title": "Ejemplo · pista temprana, acción normal",
            "detail": "Tras solo dos igualadas sueltas observadas, A♠ 5♠ no debería lanzar un farol de river sin equidad solo porque el rival “parece pegajoso”. Usa la prueba normal de bloqueadores y objetivos de retiro."
          }
        }
      ]
    },
    "lesson-opponents-callers-folders": {
      "sections": [
        {
          "heading": "Contra igualadores frecuentes, apuesta por valor de forma más directa",
          "body": "Cuando la evidencia repetida muestra demasiadas igualadas, amplía con moderación el valor fino y elige tamaños que el rango más débil aún pueda pagar. Reduce los faroles de baja equidad porque los retiros requeridos son menos probables. No confundas “iguala a menudo” con “nunca se retira”: la presión fuerte y los precios malos siguen importando.",
          "takeaway": "Los rangos pegajosos premian el valor y castigan los faroles sin apoyo."
        },
        {
          "heading": "Contra los que se retiran a menudo, presiona los rangos con tope",
          "body": "Cuando un jugador se retira repetidamente ante apuestas razonables, añade faroles seleccionados con bloqueadores o con potencial de mejora. Evita farolear en exceso contra rangos claramente fuertes; un jugador que retira muchas manos débiles aún puede continuar correctamente con las fuertes.",
          "example": {
            "title": "Ejemplo · presión respaldada por evidencia",
            "detail": "Tras doce manos y cinco retiros en botes subidos una vez comparables, Q♣ J♣ puede encadenar un proyecto fuerte más a menudo que contra un rival desconocido."
          }
        },
        {
          "heading": "Ajusta una palanca a la vez",
          "body": "Empieza con la frecuencia: farolea un poco menos o apuesta por valor un poco más. Cambia el tamaño solo cuando puedas nombrar el rango objetivo. Ampliar el rango y usar tamaños extremos al mismo tiempo dificulta saber si la lectura o la ejecución causó el resultado.",
          "takeaway": "Una explotación pequeña y explicable enseña más que un ajuste de todo o nada."
        }
      ]
    },
    "lesson-opponents-aggression-traps": {
      "sections": [
        {
          "heading": "La agresión más amplia crea más valor de atrapa-faroles",
          "body": "Un jugador que apuesta y sube en muchos puntos creíbles llega con más combinaciones débiles que uno paciente. Con una muestra suficiente y un precio justo, defiende más atrapa-faroles. Sigue respetando la textura del tablero y los bloqueadores; la agresión sola no hace rentable cada igualada.",
          "takeaway": "Amplía la defensa solo donde la agresión observada puede contener faroles realistas."
        },
        {
          "heading": "La agresión paciente representa más fuerza",
          "body": "Un rival selectivo que sube de repente tras muchas manos pasivas suele merecer más crédito. Retira con más facilidad los atrapa-faroles marginales y las manos hechas débiles, sobre todo cuando la línea tiene pocos proyectos fallidos naturales.",
          "example": {
            "title": "Ejemplo · respeta una subida poco frecuente",
            "detail": "Tras dieciséis manos observadas con poca agresión, K♠ Q♦ en K♥ 9♣ 4♠ 4♦ 2♣ puede retirarse con más comodidad ante una subida de river grande."
          }
        },
        {
          "heading": "El engaño exige protección de rango, no adivinación",
          "body": "Un jugador engañoso puede retrasar la agresión o jugar lento las manos fuertes. Mantén algunas manos fuertes en tus rangos de pase e igualada para que la acción posterior esté protegida. No intentes identificar la trampa exacta; compara el rango completo de valor y faroles con tu precio.",
          "takeaway": "Contra las trampas, protege rangos y precios de decisión en lugar de intentar leer mentes."
        }
      ]
    },
    "lesson-math-implied-odds": {
      "sections": [
        {
          "heading": "Las probabilidades directas se detienen en el bote actual",
          "body": "Las probabilidades directas del bote comparan la igualada con el bote final si no entran más fichas. Las probabilidades implícitas añaden las fichas futuras que esperas ganar tras mejorar. Importan más para manos fuertes discretas, stacks profundos, posición y rivales con probabilidad de pagar otra apuesta.",
          "takeaway": "Las fichas futuras cuentan solo cuando la mejora y el pago son realistas."
        },
        {
          "heading": "Estima el valor futuro que falta",
          "body": "Primero calcula el umbral directo de la igualada. Si tu equidad se queda corta, estima cuántas ciegas grandes extra debes ganar después para cerrar la brecha. Compara ese objetivo con el stack efectivo y una apuesta futura realista, no con todo el stack restante del rival.",
          "example": {
            "title": "Ejemplo · pareja pequeña con espacio detrás",
            "detail": "Igualar 2 ciegas grandes con 6♠ 6♦ puede ser razonable cuando quedan más de 60 ciegas grandes y es probable que un overpair fuerte pague una apuesta significativa después de que formes un trío en el flop."
          }
        },
        {
          "heading": "La posición mejora la realización",
          "body": "Actuar último facilita cobrar valor tras mejorar y evitar pagar extra cuando fallas. Los botes de varios jugadores pueden aumentar el pago potencial pero también crean proyectos rivales más fuertes. Mantén la estimación conservadora.",
          "takeaway": "Las probabilidades implícitas son un ajuste basado en evidencia, no permiso para igualar cualquier proyecto."
        }
      ]
    },
    "lesson-math-reverse-implied-odds": {
      "sections": [
        {
          "heading": "No todo out crea un ganador limpio",
          "body": "Las probabilidades inversas implícitas son pérdidas futuras tras formar una segunda mejor mano. Un proyecto de color bajo puede completarse y perder contra un color más alto; un as dominado puede formar pareja y perder contra un mejor kicker. Estos resultados hacen que la mano valga menos de lo que sugiere un conteo simple de outs.",
          "takeaway": "Descuenta los outs que mejoran tu mano sin convertirla confiablemente en la mejor."
        },
        {
          "heading": "El potencial de nuts importa más con stacks profundos",
          "body": "Los stacks profundos aumentan tanto las ganancias implícitas como las pérdidas inversas implícitas. Las cartas pequeñas del mismo palo parecen atractivas, pero un bote grande en un tablero con cuatro cartas del mismo palo suele concentrar la acción alrededor de colores más altos. Favorece los proyectos que pueden formar los nuts o que son fáciles de soltar.",
          "example": {
            "title": "Ejemplo · riesgo de color dominado",
            "detail": "7♥ 5♥ en K♥ J♥ 2♣ tiene un proyecto de color, pero una acción fuerte desde un rango de posición temprana puede incluir muchos corazones más altos. Trata como cartas limpias de valor menos de los nueve corazones."
          }
        },
        {
          "heading": "Usa un margen de equidad conservador",
          "body": "Cuando los outs están sucios o la acción futura será difícil, exige más que el umbral básico de igualada. Retirar un proyecto cerrado no es “ignorar las probabilidades”: es contabilizar la calidad de la equidad y el costo de los errores posteriores.",
          "takeaway": "Compara con el precio la equidad de victorias limpias, no solo la probabilidad de formar una mano con nombre."
        }
      ]
    },
    "lesson-math-break-even-bluffs": {
      "sections": [
        {
          "heading": "Riesgo dividido entre riesgo más recompensa",
          "body": "Para un farol puro sin equidad de showdown, los retiros requeridos = apuesta ÷ (apuesta + bote antes de la apuesta). Apostar 10 sobre 20 arriesga 10 para ganar 20, así que necesita retiros por encima de 10 ÷ 30, o alrededor de 33%, antes de considerar la comisión o la acción futura.",
          "bullets": [
            "Farol de medio bote: necesita alrededor de 33% de retiros.",
            "Farol de dos tercios del bote: necesita alrededor de 40% de retiros.",
            "Farol del tamaño del bote: necesita 50% de retiros."
          ],
          "takeaway": "Memoriza los umbrales comunes y verifica que el rango del rival realmente pueda retirarse con esa frecuencia."
        },
        {
          "heading": "La equidad del semifarol reduce el requisito de retiros",
          "body": "Un proyecto todavía puede ganar al ser igualado, así que necesita menos retiros inmediatos que un farol puro. El valor exacto depende de la equidad, la realización y la acción futura. Usa el porcentaje del farol puro como techo conservador y confirma que el proyecto tiene caminos limpios de mejora.",
          "takeaway": "La equidad al ser igualado ayuda solo cuando el proyecto es limpio y probablemente realice su valor.",
          "example": {
            "title": "Ejemplo · dos caminos para ganar",
            "detail": "A♣ 5♣ en K♦ 8♣ 3♣ puede ganar cuando una apuesta de medio bote provoca retiros y puede mejorar al color asalto al ser igualada."
          }
        },
        {
          "heading": "Las matemáticas no inventan objetivos de retiro",
          "body": "Tras encontrar el porcentaje de retiros requerido, nombra las manos mejores que realmente se retiran. Los bloqueadores, la ventaja de rango y la evidencia del rival determinan si la estimación es plausible. Contra un rango que iguala mucho, incluso un umbral matemáticamente modesto puede ser poco realista.",
          "takeaway": "Un cálculo de farol está completo solo cuando el rango aporta suficientes retiros creíbles."
        }
      ]
    }
  },
  "trainers": {
    "trainer-percentages": {
      "questions": {
        "nine-outs-next-card": {
          "prompt": "Tienes 9 outs limpios en el flop. ¿Aproximadamente con qué frecuencia conectas en el turn?",
          "context": "Usa la estimación rápida de una carta o calcula 9 ÷ 47.",
          "explanation": "9 de las 47 cartas no vistas son outs: 9 ÷ 47 ≈ 19%. La regla del 2 da una estimación rápida del 18%.",
          "choices": {
            "a": {
              "label": "Cerca del 9%",
              "feedback": "Eso trata cada out como aproximadamente 1%. Con una carta por venir, multiplica los outs limpios por unos 2."
            },
            "b": {
              "label": "Cerca del 19%",
              "feedback": "Correcto: 9 ÷ 47 es aproximadamente 19%, y la regla del 2 da una estimación rápida del 18%."
            },
            "c": {
              "label": "Cerca del 36%",
              "feedback": "Esa es la probabilidad aproximada hasta el river cuando quedan dos cartas, no la probabilidad de solo la siguiente carta."
            }
          }
        },
        "nine-outs-two-cards": {
          "prompt": "Con 9 outs limpios en el flop, ¿aproximadamente con qué frecuencia conectas para el river?",
          "context": "Supón que verás ambas cartas comunitarias restantes.",
          "explanation": "La probabilidad exacta es de aproximadamente 35%. La regla del 4 da 36%, suficiente para una decisión rápida.",
          "choices": {
            "a": {
              "label": "Cerca del 19%",
              "feedback": "Esa es aproximadamente la probabilidad de conectar solo en el turn."
            },
            "b": {
              "label": "Cerca del 27%",
              "feedback": "Esto es demasiado bajo para dos oportunidades de conectar uno de nueve outs limpios."
            },
            "c": {
              "label": "Cerca del 35%",
              "feedback": "Correcto: la probabilidad exacta con dos cartas es de aproximadamente 35%; la regla del 4 estima 36%."
            }
          }
        },
        "half-pot-call": {
          "prompt": "El bote es 100. El villano apuesta 50. ¿Qué equidad necesita una igualada para el punto de equilibrio?",
          "context": "Igualas 50 y el bote final se convierte en 200.",
          "explanation": "El monto de la igualada ÷ el bote final es 50 ÷ 200 = 25%.",
          "choices": {
            "a": {
              "label": "Cerca del 20%",
              "feedback": "Esto subestima el precio porque tu igualada de 50 fichas debe incluirse en el bote final."
            },
            "b": {
              "label": "Cerca del 25%",
              "feedback": "Correcto: igualar 50 crea un bote final de 200, y 50 ÷ 200 es 25%."
            },
            "c": {
              "label": "Cerca del 33%",
              "feedback": "Ese es el precio de la igualada contra una apuesta del tamaño del bote, no una de medio bote."
            }
          }
        },
        "three-quarter-pot-call": {
          "prompt": "El bote es 120. El villano apuesta 90. ¿Qué equidad necesita una igualada?",
          "context": "Después de igualar 90, el bote final será 300.",
          "explanation": "90 ÷ 300 = 30%. No dividas solo entre el bote anterior a tu igualada.",
          "choices": {
            "a": {
              "label": "Cerca del 25%",
              "feedback": "Ese es el precio familiar contra una apuesta de medio bote; esta apuesta es mayor."
            },
            "b": {
              "label": "Cerca del 30%",
              "feedback": "Correcto: después de igualar, el bote final es 300, así que 90 ÷ 300 es 30%."
            },
            "c": {
              "label": "Cerca del 43%",
              "feedback": "Eso compara la apuesta con el bote anterior a tu igualada en lugar del bote final que puedes ganar."
            }
          }
        },
        "eight-outs-river": {
          "prompt": "Tienes 8 outs limpios en el turn. ¿Aproximadamente con qué frecuencia conectas en el river?",
          "context": "Queda una carta por venir y hay 46 cartas no vistas.",
          "explanation": "8 ÷ 46 ≈ 17%. Multiplicar los outs por 2 da una estimación rápida del 16%.",
          "choices": {
            "a": {
              "label": "Cerca del 9%",
              "feedback": "Eso está más cerca de cuatro outs con una carta por venir."
            },
            "b": {
              "label": "Cerca del 17%",
              "feedback": "Correcto: 8 ÷ 46 es aproximadamente 17%, y la regla del 2 da una estimación rápida del 16%."
            },
            "c": {
              "label": "Cerca del 32%",
              "feedback": "Eso aplica a grandes rasgos la regla del 4, pero solo queda una carta por venir en el river."
            }
          }
        }
      }
    },
    "quiz-core-decisions": {
      "questions": {
        "button-ace-jack": {
          "prompt": "Cara a cara, con 100 ciegas grandes. Estás en el botón con A♠ J♦ y la acción llega a ti preflop.",
          "context": "Elige una referencia práctica para principiantes.",
          "explanation": "A-J va muy por delante de una mano aleatoria de ciega grande. Subir construye valor y aprovecha tu ventaja de posición. Las estrategias fuertes pueden incluir alguna mano que entre pagando la ciega, pero retirarse es demasiado tight.",
          "choices": {
            "a": {
              "label": "Retirarse",
              "feedback": "A-J es mucho demasiado fuerte para soltarla contra una mano aleatoria de ciega grande."
            },
            "b": {
              "label": "Solo igualar",
              "feedback": "Algunas estrategias avanzadas combinan limps, pero igualar solo renuncia a una subida de valor clara y sencilla."
            },
            "c": {
              "label": "Subir",
              "feedback": "Correcto: sube por valor y conserva la ventaja de posición después del flop."
            }
          }
        },
        "river-bluff-catcher": {
          "prompt": "En el river, el bote es 80 y el villano apuesta 80. Tu carta atrapa-faroles gana alrededor del 25% de las veces.",
          "context": "No hay acción futura después de esta igualada.",
          "explanation": "Una apuesta del tamaño del bote te exige 33% de equidad: 80 ÷ 240. Una estimación honesta del 25% queda por debajo del punto de equilibrio, así que retírate.",
          "choices": {
            "a": {
              "label": "Retirarse",
              "feedback": "Correcto: tu estimación de victoria del 25% queda por debajo del precio de equilibrio del 33%."
            },
            "b": {
              "label": "Igualar",
              "feedback": "Igualar pierde a largo plazo cuando la estimación de victoria indicada está por debajo de la equidad requerida."
            },
            "c": {
              "label": "Subir",
              "feedback": "Una subida de farol necesita fuerte evidencia de que el rival se retirará; el precio por sí solo no la proporciona."
            }
          }
        },
        "thin-river-value": {
          "prompt": "El villano pasa en el river. Tienes el par superior con un kicker fuerte y varios pares más débiles pueden igualar.",
          "context": "Quedan muy pocos proyectos fallados en el rango del villano.",
          "explanation": "Una apuesta de valor más pequeña apunta a las manos de un par más débiles que identificaste. Pasar puede combinarse en algunas situaciones, pero perderse automáticamente las igualadas claras de manos peores deja valor sobre la mesa.",
          "choices": {
            "a": {
              "label": "Pasar automáticamente",
              "feedback": "Pasar es seguro, pero pierde valor cuando varios pares más débiles pueden igualar."
            },
            "b": {
              "label": "Apostar poco por valor",
              "feedback": "Correcto: elige un tamaño que mantenga en la mano a los pares de un par más débiles identificados."
            },
            "c": {
              "label": "Ir all-in",
              "feedback": "La apuesta excesiva probablemente hará retirarse a las manos más débiles que quieres que igualen."
            }
          }
        },
        "poor-bluff-candidate": {
          "prompt": "Tu proyecto de color bajo no conecta en el river. El villano es propenso a igualar y tus cartas no bloquean las igualadas fuertes de un par.",
          "context": "Casi no tienes valor en el showdown, pero hay poca evidencia de que el rival se retirará.",
          "explanation": "Un proyecto fallado no es automáticamente un farol. Contra un rango propenso a igualar, sin blockers útiles, el fold equity es demasiado bajo. Guarda el farol para una mejor oportunidad.",
          "choices": {
            "a": {
              "label": "Pasar",
              "feedback": "Correcto: abandona la mano cuando el rival iguala demasiado a menudo y tu mano tiene blockers pobres."
            },
            "b": {
              "label": "Apostar porque fallaste",
              "feedback": "Un proyecto fallado no es automáticamente un farol; primero identifica suficientes manos mejores que puedan retirarse."
            },
            "c": {
              "label": "Siempre sobreapostar",
              "feedback": "Arriesgar más fichas no arregla un fold equity débil ni unos efectos de blockers pobres."
            }
          }
        }
      }
    },
    "quiz-preflop-mastery": {
      "questions": {
        "mastery-early-a8o": {
          "prompt": "Seis jugadores, con 100 ciegas grandes. Eres el primero en actuar con la mano mostrada arriba.",
          "context": "Quedan cinco jugadores con cartas vivas detrás de ti.",
          "explanation": "A-8 offsuit no tiene suficiente calidad de cartas ni jugabilidad para superar cinco rangos. La posición convierte esto en un retiro disciplinado.",
          "choices": {
            "fold": {
              "label": "Retirarse",
              "feedback": "Correcto: el as débil offsuit es dominado con demasiada frecuencia con cinco rangos aún detrás."
            },
            "limp": {
              "label": "Igualar 1 ciega grande",
              "feedback": "Entrar pagando la ciega como primero en actuar invita a un bote con muchos jugadores, con una mano que a menudo termina en el segundo mejor par superior."
            },
            "raise": {
              "label": "Subir a 2.5 ciegas grandes",
              "feedback": "Esto es demasiado amplio para una referencia sencilla de posición temprana con seis jugadores."
            }
          }
        },
        "mastery-button-a8s": {
          "prompt": "Seis jugadores, con 100 ciegas grandes. Todos se retiran hasta llegar a ti en el botón.",
          "context": "Solo quedan la ciega pequeña y la ciega grande.",
          "explanation": "La misma mano que se retira temprano se convierte en subida en el botón porque quedan menos jugadores y tendrás posición cuando te igualen.",
          "choices": {
            "fold": {
              "label": "Retirarse",
              "feedback": "Retirarse renuncia a una oportunidad rentable en posición tardía contra solo dos rangos restantes."
            },
            "limp": {
              "label": "Igualar 1 ciega grande",
              "feedback": "Entrar pagando la ciega puede existir en estrategias avanzadas, pero subir es la referencia más clara para principiantes."
            },
            "raise": {
              "label": "Subir a 2.5 ciegas grandes",
              "feedback": "Correcto: que sea suited, un blocker de as y la posición hacen de esto una apertura práctica desde el botón."
            }
          }
        },
        "mastery-isolate-kqs": {
          "prompt": "El cutoff entra pagando 1 ciega grande. Estás en el botón con ambas ciegas detrás.",
          "context": "Las pilas efectivas son de 100 ciegas grandes.",
          "explanation": "K-Q suited encabeza un rango típico de manos que entran pagando la ciega. Subir el tamaño contra ese jugador construye valor y desalienta a las ciegas a entrar barato.",
          "choices": {
            "fold": {
              "label": "Retirarse",
              "feedback": "K-Q suited es mucho demasiado fuerte para retirarse contra un rango típico de manos que pagan la ciega."
            },
            "call": {
              "label": "Igualar 1 ciega grande",
              "feedback": "Igualar es jugable, pero invita a ambas ciegas y pierde un aislamiento de valor claro."
            },
            "raise": {
              "label": "Subir a 5 ciegas grandes",
              "feedback": "Correcto: sube por valor e intenta jugar cara a cara contra el jugador que pagó la ciega, con posición."
            }
          }
        },
        "mastery-overlimp-22": {
          "prompt": "Dos jugadores entran pagando la ciega. Estás en el botón, las pilas son profundas y las ciegas rara vez suben.",
          "context": "Elige la referencia más clara de baja varianza para la mesa descrita.",
          "explanation": "Un par pequeño se beneficia de un bote barato con varios jugadores solo cuando las pilas son profundas, el riesgo de squeeze es bajo y tienes posición.",
          "choices": {
            "fold": {
              "label": "Retirarse",
              "feedback": "Retirarse es seguro, pero las condiciones pasivas y profundas hacen razonable un intento barato de trío (set-mine)."
            },
            "call": {
              "label": "Igualar 1 ciega grande",
              "feedback": "Correcto: la posición, las pilas profundas y el bajo riesgo de squeeze respaldan entrar pagando por detrás de forma selectiva."
            },
            "raise": {
              "label": "Subir a 6 ciegas grandes",
              "feedback": "Subir puede combinarse, pero este par pequeño sufre con varios igualadores y con la presión postflop."
            }
          }
        },
        "mastery-aJo-early-open": {
          "prompt": "Un jugador disciplinado de posición temprana sube a 3 ciegas grandes. Estás en la ciega grande.",
          "context": "Tienes 100 ciegas grandes y actuarás primero después del flop.",
          "explanation": "La posición temprana del que sube y su tamaño mayor hacen que su rango sea fuerte. A-J offsuit a menudo crea un par de segunda calidad muy costoso.",
          "choices": {
            "fold": {
              "label": "Retirarse",
              "feedback": "Correcto: el rango cerrado de posición temprana domina demasiados de tus resultados de par superior."
            },
            "call": {
              "label": "Igualar 2 ciegas grandes",
              "feedback": "El descuento por la ciega ya puesta no supera la dominación y la mala materialización de la equidad."
            },
            "raise": {
              "label": "Subir a 10 ciegas grandes",
              "feedback": "Esta mano es un farol sencillo pobre contra un rango fuerte de posición temprana."
            }
          }
        },
        "mastery-kqs-facing-cutoff": {
          "prompt": "El cutoff sube a 2.5 ciegas grandes. Estás en el botón.",
          "context": "Ambas ciegas siguen detrás y las pilas efectivas son de 100 ciegas grandes.",
          "explanation": "K-Q suited rinde bien contra un rango de apertura de cutoff. La posición hace de la igualada una referencia robusta sin inflar demasiado el bote.",
          "choices": {
            "fold": {
              "label": "Retirarse",
              "feedback": "K-Q suited tiene demasiada equidad y jugabilidad para retirarse ante una apertura normal de cutoff."
            },
            "call": {
              "label": "Igualar 2.5 ciegas grandes",
              "feedback": "Correcto: igualar materializa la equidad de la mano con posición y mantiene involucradas a las manos más débiles."
            },
            "raise": {
              "label": "Subir a 8 ciegas grandes",
              "feedback": "Volver a subir puede combinarse, pero igualar es la referencia más clara con esta mano tan jugable."
            }
          }
        },
        "mastery-87s-blind-defense": {
          "prompt": "El botón sube a 2.25 ciegas grandes. La ciega pequeña se retira; estás en la ciega grande.",
          "context": "Ya pusiste 1 ciega grande y las pilas efectivas son de 100 ciegas grandes.",
          "explanation": "La subida pequeña ofrece un precio favorable, y la conectividad suited crea formas robustas de mejorar después del flop.",
          "choices": {
            "fold": {
              "label": "Retirarse",
              "feedback": "Retirarse es demasiado conservador para este precio bajo contra un rango amplio de posición tardía."
            },
            "call": {
              "label": "Igualar 1.25 ciegas grandes",
              "feedback": "Correcto: el descuento y la conectividad suited respaldan una defensa práctica."
            },
            "raise": {
              "label": "Subir a 9 ciegas grandes",
              "feedback": "Volver a subir puede combinarse, pero igualar es la forma más sencilla de materializar la equidad de esta mano."
            }
          }
        },
        "mastery-a5s-three-bet": {
          "prompt": "Un botón activo sube a 2.5 ciegas grandes. La ciega pequeña se retira; estás en la ciega grande.",
          "context": "Elige la opción agresiva con las mejores razones estructurales.",
          "explanation": "A-5 suited es una re-subida de farol ocasional y deliberada: bloquea los ases fuertes y conserva potencial de escalera y de color cuando le igualan.",
          "choices": {
            "fold": {
              "label": "Retirarse",
              "feedback": "Retirarse es viable, pero renuncia a un blocker útil y al potencial de escalera mínima (wheel) suited."
            },
            "call": {
              "label": "Igualar 1.5 ciegas grandes",
              "feedback": "Igualar es viable, pero no usa el blocker del as para crear presión inmediata."
            },
            "raise": {
              "label": "Subir a 9 ciegas grandes",
              "feedback": "Correcto: el as bloquea las manos premium que continúan y la mano sigue siendo jugable cuando le igualan."
            }
          }
        }
      }
    },
    "quiz-postflop-mastery": {
      "questions": {
        "postflop-mastery-dry-cbet": {
          "prompt": "Subiste desde el cutoff y la ciega grande igualó. Pasa este flop seco hacia ti.",
          "context": "El bote es 6 ciegas grandes. Elige la referencia más clara y favorable para tu rango.",
          "explanation": "En cara a cara sobre un tablero seco de carta más alta, quien subió puede usar una apuesta de continuación pequeña tanto con manos hechas como con manos falladas seleccionadas.",
          "choices": {
            "check": {
              "label": "Pasar",
              "feedback": "Pasar puede combinarse, pero renuncia a una oportunidad de bajo riesgo en un tablero que favorece fuertemente a quien subió preflop."
            },
            "small": {
              "label": "Apostar 2 ciegas grandes",
              "feedback": "Correcto: una apuesta de un tercio del bote aplica presión mientras representa las muchas damas fuertes y sobreparejas de tu rango."
            },
            "large": {
              "label": "Apostar 6 ciegas grandes",
              "feedback": "Una apuesta del tamaño del bote arriesga demasiado cuando un tamaño menor puede presionar las mismas manos sin par."
            }
          }
        },
        "postflop-mastery-wet-multiway": {
          "prompt": "Subiste preflop y dos jugadores igualaron. Ambos rivales pasan este flop conectado.",
          "context": "El bote es 9 ciegas grandes. Los igualadores adicionales tienen muchos pares, combinaciones de dos pares y proyectos de escalera.",
          "explanation": "Más rivales y un tablero muy conectado reducen la ventaja automática de ser quien subió preflop. Pasar protege tu rango y materializa la equidad.",
          "choices": {
            "check": {
              "label": "Pasar",
              "feedback": "Correcto: el tablero húmedo con varios jugadores conecta fuerte con los rangos que igualan, mientras tu mano conserva equidad útil para el turn."
            },
            "small": {
              "label": "Apostar 3 ciegas grandes",
              "feedback": "Una apuesta pequeña difícilmente hará retirarse a pares o a proyectos robustos y puede invitar subidas difíciles."
            },
            "large": {
              "label": "Apostar 8 ciegas grandes",
              "feedback": "Un farol grande contra dos rangos conectados arriesga demasiado sin un objetivo claro de retiro."
            }
          }
        },
        "postflop-mastery-flop-value": {
          "prompt": "Subiste en el botón, la ciega grande igualó y pasa este flop.",
          "context": "El bote es 6 ciegas grandes. Varios pares más débiles y proyectos backdoor pueden continuar.",
          "explanation": "El par superior con el kicker más alto tiene varios objetivos más débiles que igualan. Un tamaño moderado captura valor sin forzar que el rango se vuelva innecesariamente fuerte.",
          "choices": {
            "check": {
              "label": "Pasar",
              "feedback": "Pasar protege la mano, pero pierde valor claro de damas más débiles, ochos, pares de mano y proyectos."
            },
            "half": {
              "label": "Apostar 3 ciegas grandes",
              "feedback": "Correcto: el medio bote mantiene involucrados a los igualadores débiles realistas mientras empieza a construir valor."
            },
            "overbet": {
              "label": "Apostar 10 ciegas grandes",
              "feedback": "La sobreapuesta hace retirarse a gran parte del rango débil que quieres que iguale y te aísla contra las manos más fuertes que continúan."
            }
          }
        },
        "postflop-mastery-turn-pot-control": {
          "prompt": "Apostaste en el flop y la ciega grande igualó. Pasan de nuevo en este turn tranquilo.",
          "context": "El bote es 14 ciegas grandes. Tu par tiene valor en el showdown, pero pocas manos claramente más débiles pueden igualar dos apuestas grandes más.",
          "explanation": "El valor medio en el showdown no siempre necesita protección. La posición te permite tomar una carta gratis y tomar una decisión más informada en el river.",
          "choices": {
            "check": {
              "label": "Pasar",
              "feedback": "Correcto: pasar materializa el valor en el showdown, protege tu rango de pasadas y evita inflar el bote contra reyes más fuertes."
            },
            "half": {
              "label": "Apostar 7 ciegas grandes",
              "feedback": "Existe algo de valor de protección, pero muchas manos débiles se retiran mientras los pares más fuertes continúan."
            },
            "pot": {
              "label": "Apostar 14 ciegas grandes",
              "feedback": "Una apuesta del tamaño del bote aísla esta mano de fuerza media contra demasiada parte del rango más fuerte."
            }
          }
        },
        "postflop-mastery-flush-price": {
          "prompt": "La ciega grande apuesta 5 ciegas grandes a un bote de 10 ciegas grandes en este flop.",
          "context": "Igualar 5 hace que el bote final sea 20 ciegas grandes, así que el precio de equilibrio es 25%.",
          "explanation": "El monto de la igualada dividido entre el bote final es 5 ÷ 20 = 25%. Una equidad de color hasta el river de aproximadamente 35% hace de la igualada la referencia matemática limpia.",
          "choices": {
            "fold": {
              "label": "Retirarse",
              "feedback": "Nueve outs limpios de color llegan al river alrededor del 35% de las veces, cómodamente por encima del precio del 25%."
            },
            "call": {
              "label": "Igualar 5 ciegas grandes",
              "feedback": "Correcto: el proyecto del color máximo tiene suficiente equidad para este precio sin asumir que el rival se retirará."
            },
            "shove": {
              "label": "Ir all-in",
              "feedback": "Una subida puede funcionar a veces, pero el all-in añade supuestos innecesarios de fold equity y de stack-off a una igualada rentable."
            }
          }
        },
        "postflop-mastery-combo-draw": {
          "prompt": "Igualaste en el botón preflop. La ciega grande pasa este flop hacia ti.",
          "context": "El bote es 8 ciegas grandes. Puedes mejorar a escalera o a color y puedes hacer retirarse a muchas manos sin par ahora.",
          "explanation": "Los proyectos fuertes son semibluffs útiles porque ambas partes de la apuesta importan: las manos sin par peores pueden retirarse y muchas cartas te mejoran cuando te igualan.",
          "choices": {
            "check": {
              "label": "Pasar",
              "feedback": "Pasar materializa la equidad, pero pierde una oportunidad fuerte de semibluff con muchas cartas que mejoran y fold equity inmediato."
            },
            "bet": {
              "label": "Apostar 5 ciegas grandes",
              "feedback": "Correcto: el combo draw robusto puede ganar ahora mediante retiros o mejorando cuando le igualan."
            },
            "all-in": {
              "label": "Ir all-in",
              "feedback": "El proyecto es fuerte, pero una sobreapuesta extrema arriesga mucho más de lo necesario para aplicar presión útil."
            }
          }
        },
        "postflop-mastery-river-value": {
          "prompt": "La ciega grande pasa este river después de igualar dos apuestas moderadas.",
          "context": "El bote es 16 ciegas grandes. Los pares superiores más débiles y algunos segundos pares aún pueden pagar una apuesta de valor pequeña.",
          "explanation": "Un river seguro deja al par superior con el kicker más alto por delante de varias cartas atrapa-faroles. Un tamaño de valor pequeño encaja con ese rango objetivo amplio.",
          "choices": {
            "check": {
              "label": "Pasar",
              "feedback": "Pasar gana en el showdown, pero pierde valor fino de varias manos realistas de un par más débiles."
            },
            "small": {
              "label": "Apostar 5 ciegas grandes",
              "feedback": "Correcto: el tamaño pequeño apunta a los pares más débiles sin exigirles igualar una apuesta muy polarizada."
            },
            "all-in": {
              "label": "Ir all-in",
              "feedback": "Un all-in grande hace retirarse a demasiada parte del rango más débil y le igualan una selección mucho más fuerte."
            }
          }
        },
        "postflop-mastery-river-bluff-catch": {
          "prompt": "La ciega grande apuesta 25 ciegas grandes a un bote de 20 ciegas grandes en este river.",
          "context": "Igualar necesita alrededor del 36% de equidad. Según la línea y el rival, estimas que esta carta atrapa-faroles gana solo el 25%.",
          "explanation": "Una carta atrapa-faroles es una decisión de precio. Igualar 25 crea un bote final de 70 ciegas grandes: 25 ÷ 70 ≈ 36%, por encima de la estimación de victoria del 25%.",
          "choices": {
            "fold": {
              "label": "Retirarse",
              "feedback": "Correcto: el par superior parece fuerte, pero la frecuencia de farol estimada no alcanza el precio de la igualada."
            },
            "call": {
              "label": "Igualar 25 ciegas grandes",
              "feedback": "La mano le gana solo a faroles, y la estimación de victoria del 25% está por debajo del requisito de aproximadamente 36%."
            },
            "raise": {
              "label": "Ir all-in",
              "feedback": "Convertir el valor en el showdown en un farol necesita evidencia de blocker y de retiro que el escenario no proporciona."
            }
          }
        }
      }
    }
  }
};
