import { createAudioPlayer, setAudioModeAsync } from 'expo-audio';

import type { TableMomentReactionId } from '../../domain/multiplayer/tableMoments';

/**
 * Original local table-moment media: one bundled WAV blip and one bundled
 * sticker PNG per reaction, generated by scripts/generate-moment-assets.mjs.
 * Everything is required by path and bundled by Metro — nothing is ever
 * fetched from a URL, and the mapping is total over the authored reaction
 * ids, so a new reaction cannot render with missing media.
 */

export const TABLE_MOMENT_STICKER_BY_REACTION: Record<
  TableMomentReactionId,
  ReturnType<typeof require>
> = {
  cheer: require('../../../assets/stickers/cheer.png'),
  surprised: require('../../../assets/stickers/surprised.png'),
  laugh: require('../../../assets/stickers/laugh.png'),
  niceHand: require('../../../assets/stickers/niceHand.png'),
  thinking: require('../../../assets/stickers/thinking.png'),
  disappointed: require('../../../assets/stickers/disappointed.png'),
};

const soundByReaction: Record<TableMomentReactionId, ReturnType<typeof require>> = {
  cheer: require('../../../assets/sounds/cheer.wav'),
  surprised: require('../../../assets/sounds/surprised.wav'),
  laugh: require('../../../assets/sounds/laugh.wav'),
  niceHand: require('../../../assets/sounds/niceHand.wav'),
  thinking: require('../../../assets/sounds/thinking.wav'),
  disappointed: require('../../../assets/sounds/disappointed.wav'),
};

let audioModeReady = false;
const players = new Map<string, ReturnType<typeof createAudioPlayer>>();

async function ensureAudioMode(): Promise<void> {
  if (audioModeReady) return;
  await setAudioModeAsync({ playsInSilentMode: false });
  audioModeReady = true;
}

const allInPlayerSource = require('../../../assets/sounds/allIn.wav');

/**
 * Plays the bundled blip for one moment through the local expo-audio player.
 * Callers gate playback through tableMomentSoundEnabled first; failures are
 * swallowed because a moment must never interrupt gameplay. There is no
 * remote audio path anywhere in this module.
 */
export function playAllInMomentSound(): void {
  void (async () => {
    try {
      await ensureAudioMode();
      let player = players.get('allIn');
      if (!player) {
        player = createAudioPlayer(allInPlayerSource);
        players.set('allIn', player);
      } else {
        player.seekTo(0);
      }
      await player.play();
    } catch {
      // The all-in flash is presentation-only; audio must never interrupt
      // the table.
    }
  })();
}
export function playTableMomentSound(reactionId: TableMomentReactionId): void {
  const source = soundByReaction[reactionId];
  void (async () => {
    try {
      await ensureAudioMode();
      let player = players.get(reactionId);
      if (!player) {
        player = createAudioPlayer(source);
        players.set(reactionId, player);
      } else {
        player.seekTo(0);
      }
      player.play();
    } catch {
      // Local playback must never interrupt a poker action.
    }
  })();
}
