import { createAudioPlayer, setAudioModeAsync } from 'expo-audio';

import type { TableMomentReactionId } from '../../domain/multiplayer/tableMoments';

/**
 * Original local table-moment media: one bundled sticker PNG per reaction,
 * generated by scripts/generate-moment-assets.mjs.
 * Everything is required by path and bundled by Metro — nothing is ever
 * fetched from a URL, and the mapping is total over the authored reaction
 * ids, so a new reaction cannot render with missing media.
 */

export const TABLE_MOMENT_STICKER_BY_REACTION: Record<
  TableMomentReactionId,
  ReturnType<typeof require>
> = {
  cheer: require('../../../assets/stickers/cheer.png'),
  surprised: require('../../../assets/stickers/surprised.png'),
  laugh: require('../../../assets/stickers/laugh.png'),
  niceHand: require('../../../assets/stickers/niceHand.png'),
  thinking: require('../../../assets/stickers/thinking.png'),
  disappointed: require('../../../assets/stickers/disappointed.png'),
  goodLuck: require('../../../assets/stickers/goodLuck.png'),
  wellPlayed: require('../../../assets/stickers/wellPlayed.png'),
  bigMove: require('../../../assets/stickers/bigMove.png'),
  soClose: require('../../../assets/stickers/soClose.png'),
  onFire: require('../../../assets/stickers/onFire.png'),
  goodGame: require('../../../assets/stickers/goodGame.png'),
};

let audioModeReady = false;
const players = new Map<string, ReturnType<typeof createAudioPlayer>>();

async function ensureAudioMode(): Promise<void> {
  if (audioModeReady) return;
  await setAudioModeAsync({ playsInSilentMode: false });
  audioModeReady = true;
}

const allInPlayerSource = require('../../../assets/sounds/allIn.wav');

/** Plays the separate all-in accent; ordinary table reactions are silent. */
export function playAllInMomentSound(): void {
  void (async () => {
    try {
      await ensureAudioMode();
      let player = players.get('allIn');
      if (!player) {
        player = createAudioPlayer(allInPlayerSource);
        players.set('allIn', player);
      } else {
        player.seekTo(0);
      }
      await player.play();
    } catch {
      // The all-in flash is presentation-only; audio must never interrupt
      // the table.
    }
  })();
}
