import type { ScenarioSpot } from '../domain/learning/types';

/**
 * Shared contract for the generated Phase 19 (`es-419`, `pt-BR`) scenario
 * catalogs. The catalogs are generated by `scripts/sync-locale-catalog.mjs`
 * from the JSON translation memory under `.claude/tmp/translation/out/`; this
 * module owns the shapes and the runtime resolution so no per-locale module
 * needs executable logic.
 *
 * Poker-fact policy: instance-specific values (the hero hand label, the
 * calculation amounts) are interpolated at runtime from the live scenario, so
 * a translated sentence can never show numbers that disagree with the spot.
 * Prose that the English source varies per instance beyond those values is
 * written qualitatively per template, mirroring the shipped Chinese catalog.
 */

export type ScenarioCalculationKind = 'call' | 'bluff' | 'implied-odds';

/** One branch of a kind-dependent feedback sentence. */
export interface ScenarioFeedbackVariant {
  /** Matches `scenario.calculation?.kind`. Omitted on the final default. */
  if?: ScenarioCalculationKind;
  text: string;
}

export type ScenarioFeedbackEntry = string | readonly ScenarioFeedbackVariant[];

export type ScenarioReasoningEntry = string | { readonly mathFallback: string };

export interface ScenarioChoiceCopy {
  label: string;
  feedback: ScenarioFeedbackEntry;
}

export interface ScenarioTemplateEntry {
  focus: string;
  opponentAction: string;
  prompt: string;
  reasoning: ScenarioReasoningEntry;
  takeaway: string;
  choices: Record<string, ScenarioChoiceCopy>;
}

export type ScenarioTemplateCatalog = Record<string, ScenarioTemplateEntry>;

/**
 * Per-language vocabulary the runtime translators need: position terms
 * (longest-first phrase replacement), action-label rules (anchored regex with
 * `$1`-style templates), the hero-hand label fragments, and the three
 * calculation summary sentences used by `mathFallback` reasoning.
 */
export interface ScenarioVocab {
  terms: Record<string, string>;
  actions: ReadonlyArray<{ pattern: string; template: string }>;
  handLabels: { thisHand: string; pair: string; suited: string; offsuit: string };
  mathSummaries: {
    bluff: string;
    impliedOdds: string;
    call: string;
    callWithEquity: string;
  };
}

const RANK_LABELS: Record<number, string> = {
  14: 'A', 13: 'K', 12: 'Q', 11: 'J', 10: '10', 9: '9', 8: '8',
  7: '7', 6: '6', 5: '5', 4: '4', 3: '3', 2: '2',
};

export function scenarioTemplateId(id: string): string {
  return id.replace(/-\d+$/, '');
}

function interpolateTemplate(template: string, values: Record<string, string>): string {
  return template.replace(/\{\{(\w+)\}\}/g, (match, name: string) => values[name] ?? match);
}

function heroHandLabel(scenario: ScenarioSpot, handLabels: ScenarioVocab['handLabels']): string {
  const [first, second] = scenario.heroCards;
  if (!first || !second) return handLabels.thisHand;
  const firstRank = RANK_LABELS[first.rank] ?? `${first.rank}`;
  const secondRank = RANK_LABELS[second.rank] ?? `${second.rank}`;
  if (first.rank === second.rank) return `${firstRank}-${secondRank} ${handLabels.pair}`;
  return `${firstRank}-${secondRank} ${first.suit === second.suit ? handLabels.suited : handLabels.offsuit}`;
}

function calculationValues(calculation: NonNullable<ScenarioSpot['calculation']>): Record<string, string> {
  const values: Record<string, string> = {};
  for (const [key, value] of Object.entries(calculation)) {
    if (typeof value === 'number') values[key] = String(value);
  }
  return values;
}

function mathSummary(
  scenario: ScenarioSpot,
  summaries: ScenarioVocab['mathSummaries'],
): string | null {
  const calculation = scenario.calculation;
  if (!calculation) return null;
  const values = calculationValues(calculation);
  if (calculation.kind === 'bluff') return interpolateTemplate(summaries.bluff, values);
  if (calculation.kind === 'implied-odds') return interpolateTemplate(summaries.impliedOdds, values);
  return interpolateTemplate(
    calculation.estimatedEquityPercent === undefined ? summaries.call : summaries.callWithEquity,
    values,
  );
}

/**
 * Builds the per-language scenario localizer from a generated catalog. Like
 * the Chinese catalogs, coverage is exhaustive: a missing template or choice
 * entry throws so parity gates catch it loudly instead of leaking English.
 */
export function createScenarioLocalizer(
  catalog: ScenarioTemplateCatalog,
  vocab: ScenarioVocab,
): (scenario: ScenarioSpot) => ScenarioSpot {
  const termKeys = Object.keys(vocab.terms).sort((a, b) => b.length - a.length);
  const actionRules = vocab.actions.map((rule) => ({
    regex: new RegExp(rule.pattern, 'u'),
    template: rule.template,
  }));

  function translatePosition(value: string): string {
    let result = value;
    for (const key of termKeys) result = result.split(key).join(vocab.terms[key]);
    return result;
  }

  function translateAction(label: string): string {
    const rule = actionRules.find(({ regex }) => regex.test(label));
    if (!rule) throw new Error(`Missing localized scenario action rule: ${label}`);
    return label.replace(rule.regex, rule.template);
  }

  return (scenario: ScenarioSpot): ScenarioSpot => {
    const template = scenarioTemplateId(scenario.id);
    const copy = catalog[template];
    if (!copy) throw new Error(`Missing localized scenario copy: ${template}`);

    const calculation = scenario.calculation;
    const values: Record<string, string> = {
      heroHand: heroHandLabel(scenario, vocab.handLabels),
      ...(calculation ? calculationValues(calculation) : {}),
    };

    const reasoning = typeof copy.reasoning === 'object'
      ? (mathSummary(scenario, vocab.mathSummaries) ?? interpolateTemplate(copy.reasoning.mathFallback, values))
      : interpolateTemplate(copy.reasoning, values);

    return {
      ...scenario,
      // Every rendered field passes through interpolation: the generated
      // catalogs carry {{heroHand}} and calculation placeholders wherever the
      // English source varies per instance, so a raw token must never reach a
      // screen (enforced by the unresolved-placeholder suite).
      focus: interpolateTemplate(copy.focus, values),
      opponentAction: interpolateTemplate(copy.opponentAction, values),
      prompt: interpolateTemplate(copy.prompt, values),
      reasoning,
      takeaway: interpolateTemplate(copy.takeaway, values),
      position: translatePosition(scenario.position),
      opponentPosition: translatePosition(scenario.opponentPosition),
      choices: scenario.choices.map((choice) => {
        const choiceCopy = copy.choices[choice.id];
        if (!choiceCopy) throw new Error(`Missing localized scenario feedback: ${template}/${choice.id}`);
        const feedback = choiceCopy.feedback;
        let resolved: string;
        if (typeof feedback === 'string') {
          resolved = interpolateTemplate(feedback, values);
        } else {
          const matched = feedback.find((variant) => variant.if !== undefined && variant.if === calculation?.kind);
          const chosen = matched ?? feedback[feedback.length - 1]!;
          resolved = interpolateTemplate(chosen.text, values);
        }
        return {
          ...choice,
          label: translateAction(choice.label),
          feedback: resolved,
        };
      }),
    };
  };
}
