import type { Card, Rank, Suit } from '../poker/types';
import type { ScenarioChoice, ScenarioTrainerDefinition } from './types';

const card = (rank: Rank, suit: Suit): Card => ({ rank, suit });

export const scenarioTrainer: ScenarioTrainerDefinition = {
  id: 'scenario-core-decisions',
  type: 'scenario_drill',
  title: 'Scenario training',
  description: 'Read the table, choose a play, and get coached',
  estimatedMinutes: 6,
  scenarios: [
    {
      id: 'button-ace-jack-suited',
      focus: 'Preflop value',
      street: 'preflop',
      position: 'Button · Small blind',
      opponentPosition: 'Big blind',
      effectiveStackBb: 100,
      potBb: 1.5,
      heroCards: [card(14, 'spades'), card(11, 'spades')],
      board: [],
      opponentAction: 'Action folds to you heads-up.',
      prompt: 'What is your clearest baseline play?',
      choices: [
        { id: 'fold', label: 'Fold', grade: 'mistake', feedback: 'A-J suited is far too strong to release heads-up.' },
        { id: 'limp', label: 'Call 0.5 BB', grade: 'reasonable', feedback: 'Strong strategies can mix limps, but raising is the simpler value-first baseline.' },
        { id: 'raise', label: 'Raise to 2.5 BB', grade: 'best', feedback: 'You build value, pressure weaker hands, and keep the positional advantage after the flop.' },
      ],
      bestChoiceId: 'raise',
      reasoning: 'A-J suited is well ahead of a random big-blind hand. Raising earns value now and keeps initiative without risking an excessive part of the stack.',
      takeaway: 'Raise strong button hands for value; position lets you realize that advantage more often.',
    },
    {
      id: 'large-open-trash-defense',
      focus: 'Blind defense',
      street: 'preflop',
      position: 'Big blind',
      opponentPosition: 'Button · Small blind',
      effectiveStackBb: 60,
      potBb: 5,
      heroCards: [card(7, 'clubs'), card(2, 'diamonds')],
      board: [],
      opponentAction: 'Button raises to 4 BB. You have 1 BB invested and must call 3 BB.',
      prompt: 'How should you defend?',
      choices: [
        { id: 'fold', label: 'Fold', grade: 'best', feedback: 'The large size worsens your price, and 7-2 offsuit realizes equity poorly out of position.' },
        { id: 'call', label: 'Call 3 BB', grade: 'mistake', feedback: 'Already investing 1 BB is not a reason to continue when the remaining call is unprofitable.' },
        { id: 'raise', label: 'Raise to 12 BB', grade: 'mistake', feedback: 'This hand has poor blockers and playability, making it a weak bluff candidate.' },
      ],
      bestChoiceId: 'fold',
      reasoning: 'You need 3 BB to contest a 5 BB pot, and you will act first after the flop. The raw price does not rescue one of the weakest disconnected offsuit hands.',
      takeaway: 'Defend wider against small opens, but let the weakest hands go as the price increases.',
    },
    {
      id: 'nut-flush-draw-price',
      focus: 'Draws and pot odds',
      street: 'flop',
      position: 'Button',
      opponentPosition: 'Big blind',
      effectiveStackBb: 84,
      potBb: 18,
      heroCards: [card(14, 'hearts'), card(5, 'hearts')],
      board: [card(13, 'hearts'), card(8, 'clubs'), card(2, 'hearts')],
      opponentAction: 'Big blind bets 6 BB into 12 BB. The displayed pot is now 18 BB.',
      prompt: 'Choose the cleanest response.',
      choices: [
        { id: 'fold', label: 'Fold', grade: 'mistake', feedback: 'Nine heart outs plus overcard potential make folding to this price too tight.' },
        { id: 'call', label: 'Call 6 BB', grade: 'best', feedback: 'Calling needs 25% equity, while nine clean flush outs have about 35% equity by the river.' },
        { id: 'raise', label: 'Raise to 20 BB', grade: 'reasonable', feedback: 'A semi-bluff can work, but it adds fold-equity assumptions. Calling is the clearest baseline.' },
      ],
      bestChoiceId: 'call',
      reasoning: 'After your 6 BB call, the final pot is 24 BB, so the break-even price is 6 ÷ 24 = 25%. A nine-out flush draw is comfortably above that with two cards to come before future-action adjustments.',
      takeaway: 'Compare realistic draw equity with the final pot after your call—not the pot before it.',
    },
    {
      id: 'turn-top-pair-value',
      focus: 'Value betting',
      street: 'turn',
      position: 'Button',
      opponentPosition: 'Big blind',
      effectiveStackBb: 72,
      potBb: 18,
      heroCards: [card(14, 'spades'), card(12, 'diamonds')],
      board: [card(12, 'clubs'), card(7, 'hearts'), card(3, 'spades'), card(2, 'clubs')],
      opponentAction: 'Big blind checks a second time.',
      prompt: 'How do you continue with top pair, top kicker?',
      choices: [
        { id: 'check', label: 'Check', grade: 'reasonable', feedback: 'Checking controls the pot, but it misses value from queens, sevens, pairs, and draws.' },
        { id: 'bet', label: 'Bet 9 BB', grade: 'best', feedback: 'A half-pot bet targets several worse hands while charging club and straight draws.' },
        { id: 'all-in', label: 'Move all-in', grade: 'mistake', feedback: 'An oversized shove folds too much of the weaker range you want to keep calling.' },
      ],
      bestChoiceId: 'bet',
      reasoning: 'You can name several worse hands that continue, and the board still offers draws. Half pot captures value without isolating yourself against only very strong hands.',
      takeaway: 'Value betting starts by identifying worse hands that can realistically call your size.',
    },
    {
      id: 'river-overbet-bluff-catcher',
      focus: 'Bluff catching',
      street: 'river',
      position: 'Button',
      opponentPosition: 'Big blind',
      effectiveStackBb: 55,
      potBb: 36,
      heroCards: [card(13, 'clubs'), card(11, 'clubs')],
      board: [card(13, 'diamonds'), card(8, 'spades'), card(6, 'hearts'), card(3, 'clubs'), card(2, 'diamonds')],
      opponentAction: 'Big blind bets 20 BB into 16 BB. You estimate this bluff catcher wins about 25% of the time.',
      prompt: 'What does the price tell you to do?',
      choices: [
        { id: 'fold', label: 'Fold', grade: 'best', feedback: 'You need about 36% equity, so a trustworthy 25% estimate cannot support a call.' },
        { id: 'call', label: 'Call 20 BB', grade: 'mistake', feedback: 'Top pair looks attractive, but the call loses when your equity estimate is below the price.' },
        { id: 'raise', label: 'Raise all-in', grade: 'mistake', feedback: 'Turning a hand with showdown value into a bluff needs strong blocker and fold evidence you do not have.' },
      ],
      bestChoiceId: 'fold',
      reasoning: 'Calling 20 BB makes the final pot 56 BB. Required equity is 20 ÷ 56 ≈ 36%, well above the stated 25% chance of winning.',
      takeaway: 'Do not let absolute hand strength override the price and your range-based win estimate.',
    },
    {
      id: 'missed-draw-bad-bluff',
      focus: 'Bluff selection',
      street: 'river',
      position: 'Button',
      opponentPosition: 'Big blind',
      effectiveStackBb: 48,
      potBb: 24,
      heroCards: [card(12, 'clubs'), card(5, 'clubs')],
      board: [card(13, 'spades'), card(9, 'clubs'), card(4, 'clubs'), card(2, 'diamonds'), card(2, 'hearts')],
      opponentAction: 'Big blind checks. This opponent calls too often, and your cards do not block strong one-pair calls.',
      prompt: 'Should the missed draw bluff?',
      choices: [
        { id: 'check', label: 'Check back', grade: 'best', feedback: 'Low fold equity and poor blockers make this a disciplined give-up.' },
        { id: 'small', label: 'Bet 8 BB', grade: 'mistake', feedback: 'A small bet gives a call-heavy opponent an easy price and lacks a clear better-hand target.' },
        { id: 'pot', label: 'Bet 24 BB', grade: 'mistake', feedback: 'A bigger bet risks more chips without evidence this opponent will release enough pairs.' },
      ],
      bestChoiceId: 'check',
      reasoning: 'Missing a draw does not automatically create a profitable bluff. Good bluffs need enough folds, useful blockers, or both; this spot offers neither.',
      takeaway: 'Bluff because the range can fold—not simply because your draw missed.',
    },
  ],
};

export function scenarioChoicePoints(choice: ScenarioChoice): number {
  if (choice.grade === 'best') return 1;
  if (choice.grade === 'reasonable') return 0.5;
  return 0;
}
