-- Generated by `supabase migration new multiplayer_legacy_liveness_renewal`.
-- Sequenced after the already-future-dated liveness migration so this
-- replacement is not overwritten during a fresh database replay.
-- A validated pre-lifecycle canonical seat may omit participation. It still
-- belongs to its human owner; the Edge normalizer validates its balances
-- before commands. Do not block that owner's upgrade with a renewal 403.
create or replace function public.multiplayer_renew_seat_liveness(
  p_room_id uuid, p_user_id uuid, p_renewed_at_ms bigint
)
returns boolean
language plpgsql
security invoker
set search_path = ''
as $$
declare
  room_seats jsonb;
begin
  if p_room_id is null or p_user_id is null or p_renewed_at_ms is null or p_renewed_at_ms <= 0 then
    raise exception 'Invalid seat liveness renewal.' using errcode = '22023';
  end if;
  select state.canonical_state -> 'seats' into room_seats
  from private.multiplayer_game_states as state
  join public.multiplayer_rooms as room on room.id = state.room_id
  where state.room_id = p_room_id and room.expires_at > now();
  if not found then
    raise exception 'Multiplayer room was not found.' using errcode = 'P0002';
  end if;
  if jsonb_typeof(room_seats) is distinct from 'array' or not exists (
    select 1 from jsonb_array_elements(room_seats) as seat
    where seat ->> 'userId' = p_user_id::text
      and seat ->> 'kind' = 'human'
      and coalesce(seat ->> 'participation', 'active') in ('active', 'disconnected', 'sitting-out', 'rebuy-pending')
  ) then
    raise exception 'Only a seated human may renew seat liveness.' using errcode = '42501';
  end if;
  insert into private.multiplayer_seat_liveness (room_id, user_id, renewed_at_ms)
  values (p_room_id, p_user_id, p_renewed_at_ms)
  on conflict (room_id, user_id) do update
    set renewed_at_ms = greatest(private.multiplayer_seat_liveness.renewed_at_ms, excluded.renewed_at_ms);
  delete from private.multiplayer_seat_liveness as stale using public.multiplayer_rooms as room
  where room.id = stale.room_id and (room.expires_at <= now()
    or to_timestamp(stale.renewed_at_ms / 1000.0) < now() - interval '3 days');
  return true;
end;
$$;

revoke execute on function public.multiplayer_renew_seat_liveness(uuid, uuid, bigint) from public, anon, authenticated;
grant execute on function public.multiplayer_renew_seat_liveness(uuid, uuid, bigint) to service_role;
