// GENERATED by scripts/sync-locale-catalog.mjs from the JSON translation
// memory under translation-memory/pt-BR/. Edit the JSON sources and
// re-run the sync script; hand edits here will be overwritten.
// DRAFT: awaiting qualified native pt-BR poker-language review.
import type { LearningContentCatalog } from '../learningContentChinese';

export const portugueseLearningContent: LearningContentCatalog = {
  "cheatSheets": {
    "sheet-hand-rankings": {
      "groups": [
        {
          "title": "Da mais forte à mais fraca",
          "rows": [
            {
              "label": "straight flush",
              "detail": "Cinco cartas consecutivas do mesmo naipe"
            },
            {
              "label": "Quadra",
              "detail": "Quatro cartas do mesmo valor"
            },
            {
              "label": "Full",
              "detail": "Trinca mais um par"
            },
            {
              "label": "flush",
              "detail": "Cinco cartas do mesmo naipe, não consecutivas"
            },
            {
              "label": "Sequência",
              "detail": "Cinco valores consecutivos em naipes mistos"
            },
            {
              "label": "Trinca",
              "detail": "Três cartas do mesmo valor"
            },
            {
              "label": "Dois pares",
              "detail": "Dois pares diferentes"
            },
            {
              "label": "Um par",
              "detail": "Duas cartas do mesmo valor"
            },
            {
              "label": "Carta alta",
              "detail": "Nenhuma combinação feita das anteriores"
            }
          ]
        },
        {
          "title": "Desempates",
          "rows": [
            {
              "label": "Mesma categoria",
              "detail": "Compare primeiro a parte feita, depois os kickers"
            },
            {
              "label": "A mesa joga",
              "detail": "Se os dois usam as mesmas cinco cartas, o pote é dividido"
            }
          ]
        }
      ],
      "note": "Os percentuais são categorias finais aproximadas entre todas as mãos aleatórias de Hold’em com sete cartas. Eles não são a sua chance de formar a mão a partir de uma mão inicial específica, e não são a sua chance de vencer."
    },
    "sheet-position": {
      "groups": [
        {
          "title": "Antes do flop",
          "rows": [
            {
              "label": "Botão / small blind",
              "detail": "Paga o small blind e age primeiro"
            },
            {
              "label": "Big blind (BB)",
              "detail": "Paga o big blind e age em segundo lugar"
            }
          ]
        },
        {
          "title": "Depois do flop",
          "rows": [
            {
              "label": "Big blind (BB)",
              "detail": "Age primeiro no flop, no turn e no river"
            },
            {
              "label": "Botão",
              "detail": "Age por último e tem a vantagem de informação"
            }
          ]
        }
      ]
    },
    "sheet-percentages": {
      "groups": [
        {
          "title": "Outs limpos",
          "rows": [
            {
              "label": "Outs: 4",
              "detail": "≈ 9% na próxima carta · 17% até o river"
            },
            {
              "label": "Outs: 8",
              "detail": "≈ 17% na próxima carta · 32% até o river"
            },
            {
              "label": "Outs: 9",
              "detail": "≈ 19% na próxima carta · 35% até o river"
            },
            {
              "label": "Outs: 15",
              "detail": "≈ 32% na próxima carta · 54% até o river"
            }
          ]
        },
        {
          "title": "Diante de uma aposta",
          "rows": [
            {
              "label": "Meio pote",
              "detail": "25% de equidade de pagamento exigida"
            },
            {
              "label": "Dois terços do pote",
              "detail": "≈ 29% de equidade de pagamento exigida"
            },
            {
              "label": "Três quartos do pote",
              "detail": "30% de equidade de pagamento exigida"
            },
            {
              "label": "Pote cheio",
              "detail": "33% de equidade de pagamento exigida"
            }
          ]
        }
      ],
      "note": "Estes números assumem outs limpos e nenhuma aposta futura. Desconte os outs que podem formar uma mão mais forte para o oponente."
    },
    "sheet-preflop": {
      "groups": [
        {
          "title": "Como ler a tabela",
          "rows": [
            {
              "label": "Pares",
              "detail": "A diagonal de AA a 22"
            },
            {
              "label": "Mesmo naipe",
              "detail": "Acima da diagonal; as duas cartas compartilham o naipe"
            },
            {
              "label": "Naipes diferentes",
              "detail": "Abaixo da diagonal; as cartas têm naipes diferentes"
            }
          ]
        },
        {
          "title": "Ajuste antes de agir",
          "rows": [
            {
              "label": "Assento mais cedo = mais apertado",
              "detail": "Mais jogadores podem despertar com uma mão forte atrás de você."
            },
            {
              "label": "O big blind defende mais largo",
              "detail": "Você já investiu 1 big blind, então uma raise pequena oferece um preço melhor."
            },
            {
              "label": "Stacks fundos favorecem mãos do mesmo naipe",
              "detail": "Mãos conectadas do mesmo naipe ganham valor quando mais fichas podem ser ganhas depois do flop."
            }
          ]
        }
      ],
      "note": "Esta é uma referência inicial explicável para iniciantes, não uma tabela de solver. Tendências do oponente e tamanho de raise continuam importando."
    },
    "sheet-advanced-math": {
      "groups": [
        {
          "title": "Verificações de valor futuro",
          "rows": [
            {
              "label": "implied odds",
              "detail": "Adicione apenas fichas futuras realistas ganhas depois de melhorar."
            },
            {
              "label": "reverse implied odds",
              "detail": "Desconte as melhoras que podem formar uma cara segunda melhor mão."
            },
            {
              "label": "Stack efetivo",
              "detail": "O valor futuro não pode exceder o menor stack vivo."
            }
          ]
        },
        {
          "title": "Desistências exigidas para um blefe puro",
          "rows": [
            {
              "label": "Meio pote",
              "detail": "Arrisca 0.5 do pote para ganhar 1 · cerca de 33%"
            },
            {
              "label": "Dois terços do pote",
              "detail": "Arrisca 0.67 do pote para ganhar 1 · cerca de 40%"
            },
            {
              "label": "Pote cheio",
              "detail": "Arrisca 1 pote para ganhar 1 · 50%"
            }
          ]
        }
      ],
      "note": "Os limites de blefe puro assumem equidade zero quando pago e nenhuma ação futura. Semi-blefes exigem menos desistências, mas apenas quando a equidade de melhora é limpa e realizável."
    }
  },
  "lessons": {
    "lesson-hand-rankings": {
      "sections": [
        {
          "heading": "Use as cinco melhores cartas",
          "body": "O Texas Hold’em dá a você sete cartas disponíveis: duas cartas de mão e cinco cartas comunitárias. Seu resultado é sempre a combinação de cinco cartas mais forte. Você pode usar as duas cartas de mão, apenas uma ou nenhuma.",
          "takeaway": "Não acrescente uma sexta carta para desempatar. Só as cinco melhores cartas contam.",
          "example": {
            "title": "Exemplo · royal flush",
            "detail": "A♠ K♠ mais Q♠ J♠ 10♠ formam o straight flush com ás alto de cinco cartas. O par de dois não importa."
          }
        },
        {
          "heading": "Ordene as mãos da mais rara à mais comum",
          "body": "Straight flush, quadra, full house, flush, sequência, trinca, dois pares, um par e, por último, carta alta.",
          "bullets": [
            "O flush vence a sequência.",
            "O full house vence o flush.",
            "O ás pode ser a carta mais alta em A-K-Q-J-10 ou a mais baixa em A-2-3-4-5, mas não pode conectar as duas pontas."
          ]
        },
        {
          "heading": "Desempate em ordem",
          "body": "Compare primeiro a parte que forma a mão e depois os kickers restantes, do mais alto ao mais baixo. Se as mesmas cinco cartas valem para os dois jogadores, o pote é dividido.",
          "takeaway": "Com um par, compare o par, depois o kicker mais alto e em seguida os outros dois kickers."
        }
      ]
    },
    "lesson-position-blinds": {
      "sections": [
        {
          "heading": "As blinds criam ação",
          "body": "O small blind e o big blind são apostas obrigatórias pagas antes de as cartas serem distribuídas. No heads-up, o botão paga o small blind e age primeiro antes do flop.",
          "example": {
            "title": "Exemplo · mão no botão",
            "detail": "Com A♠ J♠ no botão no heads-up, você paga o small blind e age primeiro no pré-flop, mas por último no turn e no river."
          }
        },
        {
          "heading": "A ordem se inverte depois do flop",
          "body": "Depois do flop, o big blind age primeiro e o botão age por último. Agir por último tem valor porque você vê a escolha do outro jogador antes de fazer a sua.",
          "takeaway": "Posição é informação. Normalmente você pode jogar mais mãos no botão do que fora de posição."
        },
        {
          "heading": "O botão gira a cada mão",
          "body": "O botão se alterna no heads-up, então os dois jogadores se revezam pagando cada blind e recebendo a vantagem posicional."
        }
      ]
    },
    "lesson-actions-order": {
      "sections": [
        {
          "heading": "Quando ninguém apostou",
          "body": "Você pode passar e ceder a ação sem adicionar fichas, ou apostar e definir um preço. Uma rodada termina quando todos os jogadores ativos igualam a mesma aposta e não resta nenhuma ação."
        },
        {
          "heading": "Quando você enfrenta uma aposta",
          "body": "Você pode desistir, pagar o valor necessário para cobrir a aposta ou aumentar para um total maior. Um aumento normal em no-limit deve ser de pelo menos o tamanho da aposta ou aumento completo anterior.",
          "bullets": [
            "Desistir abre mão do seu direito ao pote.",
            "Pagar cobre o preço atual.",
            "Aumentar eleva o preço para o oponente."
          ],
          "example": {
            "title": "Exemplo · par mais draw",
            "detail": "Q♥ J♥ em J♠ 8♥ 2♥ tem o par superior e um draw de flush. Diante de uma aposta, compare desistir, pagar e um aumento legal, não apenas as cartas."
          }
        },
        {
          "heading": "All-in é um limite de fichas, não uma mão especial",
          "body": "Um jogador pode apostar todas as fichas que restam. Um all-in curto pode ser menor que um aumento completo e pode não reabrir o direito de aumentar. O RiverMind calcula os limites legais para você.",
          "takeaway": "Antes de escolher uma ação, identifique o preço do pagamento, o tamanho do pote e quem age depois."
        }
      ]
    },
    "lesson-starting-hands": {
      "sections": [
        {
          "heading": "Comece pela qualidade das cartas",
          "body": "Pares podem formar mãos fortes de um par ou trincas ocultas. Cartas altas formam pares superiores mais fortes. Cartas suited e conectadas ganham maneiras de formar flushes e sequências, mas essas vantagens são menores do que muitos iniciantes esperam.",
          "example": {
            "title": "Exemplo · estrutura premium",
            "detail": "A♠ K♠ combina duas cartas altas, suited e conexão de sequência. Cada característica adiciona maneiras úteis de continuar depois do flop."
          }
        },
        {
          "heading": "A posição muda o limite",
          "body": "No botão no heads-up você age por último depois do flop, então pode entrar com lucro com mais mãos. No big blind você já tem fichas investidas, mas vai agir primeiro no pós-flop.",
          "takeaway": "Uma mão pode ser um aumento no botão e uma desistência sob forte pressão fora de posição."
        },
        {
          "heading": "Aumente com um propósito",
          "body": "Um aumento no pré-flop pode ganhar as blinds, construir valor com mãos mais fortes e evitar revelar sua força exata. Use a tabela inicial como referência de aprendizado e depois ajuste ao comportamento do oponente."
        }
      ]
    },
    "lesson-outs-equity-odds": {
      "sections": [
        {
          "heading": "Conte os outs limpos",
          "body": "Um out é uma carta não vista que provavelmente melhora sua mão até a vencedora. Não conte uma carta como limpa quando ela também pode completar uma mão mais forte do oponente.",
          "example": {
            "title": "Exemplo · draw do nut flush",
            "detail": "A♥ 5♥ em K♥ 8♣ 2♥ deixa quatro copas visíveis, sobrando nove copas não vistas que completam um flush com ás alto."
          }
        },
        {
          "heading": "Faça uma estimativa rápida",
          "body": "Com uma carta por vir, multiplique os outs limpos por 2. Do flop com duas cartas por vir, multiplique por 4. A regra do 4 perde precisão com muitos outs, então use-a como conta de mesa, não como calculadora exata.",
          "bullets": [
            "9 outs de flush: cerca de 19% na próxima carta.",
            "9 outs de flush: cerca de 35% até o river.",
            "8 outs de sequência: cerca de 17% na próxima carta."
          ]
        },
        {
          "heading": "Compare a equidade com o preço",
          "body": "A equidade necessária para pagar é o valor pago dividido pelo pote final depois do seu pagamento. Pagar 50 em um pote que fica em 200 exige 25% de equidade antes de considerar a ação futura.",
          "takeaway": "Pague quando sua equidade realista superar o ponto de equilíbrio com margem suficiente para cobrir a incerteza e as decisões futuras."
        }
      ]
    },
    "lesson-value-bluffs": {
      "sections": [
        {
          "heading": "Apostas de valor recebem pagamento de mãos piores",
          "body": "Uma aposta de valor funciona quando mãos piores suficientes podem pagar. O melhor tamanho não é automaticamente o maior; escolha um tamanho contra o qual essas mãos piores possam continuar de forma realista.",
          "example": {
            "title": "Exemplo · candidata a aposta de valor",
            "detail": "A♠ Q♦ em Q♣ 7♥ 3♠ pode ser paga por damas mais fracas, setes, pares e alguns draws. Nomeie essas mãos antes de escolher um tamanho."
          }
        },
        {
          "heading": "Blefes fazem mãos melhores desistirem",
          "body": "Um blefe precisa de fold equity. Prefira candidatas que bloqueiem pagamentos fortes, não bloqueiem desistências e tenham pouco valor no showdown. Blefe menos contra jogadores que pagam demais.",
          "example": {
            "title": "Exemplo · draw não completado",
            "detail": "Q♣ 5♣ erra em K♠ 9♣ 4♣ 2♦ 2♥. Errar sozinho não basta; isso vira um blefe apenas quando mãos melhores suficientes podem desistir."
          }
        },
        {
          "heading": "Muitos bons checks não são nem valor nem blefe",
          "body": "Passar pode proteger uma mão de força média, realizar a equidade do draw ou evitar que todas as mãos piores desistam. A agressividade é útil apenas quando o propósito combina com o range e o board.",
          "takeaway": "Antes de apostar, nomeie as mãos piores que pagam ou as mãos melhores que desistem."
        }
      ]
    },
    "lesson-preflop-opening-position": {
      "sections": [
        {
          "heading": "Primeiro identifique quem ainda vai agir",
          "body": "Um pote não aberto significa que ninguém pagou ou aumentou antes de você. A posição inicial exige mãos mais fortes porque vários jogadores ainda podem ter uma mão premium. A posição tardia permite abrir mais mãos porque restam menos ranges e é mais provável que você aja por último depois do flop.",
          "takeaway": "Use um range de entrada mais fechado quando mais jogadores ainda estão esperando para agir."
        },
        {
          "heading": "Aumente em vez de pagar a blind",
          "body": "Um aumento pode ganhar as blinds na hora, construir valor com mãos mais fortes e reduzir a chance de um pote cheio de jogadores. Como referência simples de cash game, use cerca de 2.5 big blinds quando entrar primeiro e mantenha o mesmo tamanho em todo o seu range de abertura.",
          "bullets": [
            "Posição inicial: priorize pares, ases fortes e cartas broadway fortes.",
            "Cutoff e botão: adicione mais ases suited, conectores suited e cartas altas jogáveis.",
            "Evite mudar o tamanho só porque suas cartas são fortes ou fracas."
          ]
        },
        {
          "heading": "Deixe a posição decidir as mãos de fronteira",
          "body": "Uma mão de fronteira pode ser um fold claro em posição inicial e um aumento razoável no botão. A posição não torna todas as mãos jogáveis, mas melhora a frequência com que você rouba as blinds e o quanto você consegue realizar equidade depois do flop.",
          "takeaway": "Antes de olhar uma tabela, pergunte: quantos jogadores restam e eu terei posição depois?",
          "example": {
            "title": "Exemplo · a mesma mão muda de categoria",
            "detail": "A♠ 8♠ costuma ser amplo demais para abrir primeiro em posição inicial em uma mesa de seis jogadores, mas vira um aumento prático no botão depois que todos desistem."
          }
        }
      ]
    },
    "lesson-preflop-limpers": {
      "sections": [
        {
          "heading": "Pagar a blind muda o pote, não seu objetivo",
          "body": "O jogador que paga a blind completa um big blind sem aumentar. O range dele costuma ser limitado ou desequilibrado, mas os jogadores atrás ainda podem aparecer com mãos fortes. Comece perguntando se sua mão busca valor, um flop barato com vários jogadores ou nenhum investimento."
        },
        {
          "heading": "Isole com força e posição",
          "body": "Aumente mãos que estão à frente do range provável de quem pagou a blind e que jogam bem se forem pagas. Adicione aproximadamente um big blind ao seu tamanho normal de abertura para cada jogador que pagou a blind, e um pouco mais quando você ficar fora de posição.",
          "bullets": [
            "Um jogador que pagou a blind na frente: cerca de 4 a 5 big blinds é uma referência útil para iniciantes.",
            "Escolha mãos que formem pares fortes ou draws robustos, não mãos fracas offsuit.",
            "Mais jogadores que pagam a blind criam uma recompensa maior, mas também tornam o isolamento menos provável."
          ]
        },
        {
          "heading": "Pagar atrás é uma decisão seletiva",
          "body": "Alguns pares pequenos e mãos suited conectadas podem pagar atrás quando os stacks são fundos e é provável que vários jogadores vejam o flop. Não pague a blind com mãos fracas só porque o preço parece barato; situações difíceis de dominância reversa podem custar muito mais depois.",
          "takeaway": "Aumente para isolar com vantagem clara; pague atrás apenas com uma mão e uma profundidade de stack que se beneficiem de um pote com vários jogadores.",
          "example": {
            "title": "Exemplo · isolamento por valor",
            "detail": "K♠ Q♠ no botão depois de um pagamento de blind do cutoff é forte o bastante para aumentar por valor e tentar jogar heads-up em posição."
          }
        }
      ]
    },
    "lesson-preflop-facing-raise": {
      "sections": [
        {
          "heading": "A posição de quem abriu define o range dele",
          "body": "Um aumento de posição inicial costuma representar um range mais forte que um aumento do botão. Continue mais fechado contra aberturas iniciais e mais amplo contra aberturas tardias. Sua própria posição também importa: pagar no botão é mais fácil de realizar do que pagar no small blind.",
          "takeaway": "Nunca julgue suas duas cartas sozinhas; compare-as com a posição de quem abriu e com os jogadores atrás."
        },
        {
          "heading": "Dê a cada resposta uma função",
          "body": "Desista com mãos dominadas ou que não conseguem realizar equidade suficiente. Pague com mãos que jogam bem no preço oferecido, principalmente em posição. Relance com mãos premium por valor e use apenas um conjunto pequeno e deliberado de blefes com bons bloqueadores.",
          "bullets": [
            "Relançamentos por valor querem que mãos fortes piores continuem.",
            "Os pagamentos precisam de equidade suficiente, jogabilidade e proteção contra os jogadores atrás.",
            "Um ás fraco não é automaticamente um pagamento; pode formar um par superior caro que fica como segunda melhor mão."
          ]
        },
        {
          "heading": "A pressão cresce a cada aumento",
          "body": "Quando você enfrenta um 3-bet, o pote é maior e os ranges são mais fortes. Continue com o topo do seu range de abertura, considerando a posição e a profundidade de stack. Evite pagar apenas para defender as fichas que já investiu.",
          "takeaway": "À medida que a ação fica mais forte, continue com mãos que continuam robustas, não com mãos que só parecem atraentes isoladamente.",
          "example": {
            "title": "Exemplo · evite a dominância",
            "detail": "A♦ J♣ no big blind normalmente deve desistir contra uma abertura sólida de posição inicial, enquanto a mesma mão pode continuar com muito mais tranquilidade contra um aumento pequeno do botão."
          }
        }
      ]
    },
    "lesson-preflop-blind-defense": {
      "sections": [
        {
          "heading": "As fichas colocadas melhoram o preço, não as cartas",
          "body": "No big blind, você paga apenas a diferença entre a blind colocada e o aumento. Esse desconto permite um range de continuação mais amplo, principalmente contra aberturas pequenas de posição tardia. A blind colocada já está no pote, então não defenda só para evitar “perdê-la”."
        },
        {
          "heading": "Tamanho e posição mudam a resposta",
          "body": "Defenda mais amplo contra uma abertura pequena do botão e mais fechado contra uma abertura grande de posição inicial. Mãos suited e conectadas realizam equidade melhor que mãos offsuit desconectadas. Do small blind, feche ainda mais porque o big blind ainda pode agir e você normalmente ficará fora de posição.",
          "bullets": [
            "Abertura menor + posição mais tardia = defesa mais ampla.",
            "Abertura maior + posição mais inicial = defesa mais fechada.",
            "Prefira mãos que possam formar pares fortes, sequências ou flushes."
          ]
        },
        {
          "heading": "Relance por valor ou pressão útil",
          "body": "Dê 3-bet com suas mãos mais fortes por valor. Alguns ases suited funcionam como mãos de pressão ocasionais porque bloqueiam ases premium e mantêm jogabilidade quando pagos. Evite blefar com mãos fracas aleatórias que não têm bloqueadores nem potencial pós-flop.",
          "takeaway": "Defenda porque o preço, os ranges e a jogabilidade funcionam juntos, não porque a blind pareça sua.",
          "example": {
            "title": "Exemplo · defesa sensível ao preço",
            "detail": "8♠ 7♠ pode pagar um aumento pequeno do botão no big blind, mas a mesma mão costuma desistir quando um jogador de posição inicial usa um tamanho grande."
          }
        }
      ]
    },
    "lesson-preflop-three-bet-plan": {
      "sections": [
        {
          "heading": "Comece pelas mãos que querem ação",
          "body": "Um 3-bet por valor deve ficar feliz quando quem abriu continua com um range mais fraco. O limite exato muda com a posição: damas e ás-rei são valor claro contra uma abertura tardia, enquanto uma abertura inicial fechada exige uma referência mais forte.",
          "takeaway": "Construa primeiro o núcleo de valor; não comece procurando mãos de blefe."
        },
        {
          "heading": "Adicione mãos de pressão por razões estruturais",
          "body": "Os melhores 3-bets de blefe ocasionais bloqueiam continuações premium e mantêm equidade útil quando pagos. Os ases baixos suited são candidatos comuns porque um ás remove combinações de ases, ás-rei e ás-dama, enquanto a carta baixa pode formar sequências e flushes.",
          "bullets": [
            "Prefira bloqueadores contra as continuações mais fortes de quem abriu.",
            "Prefira cartas suited ou conectadas que possam melhorar de mais de uma maneira.",
            "Evite mãos fracas offsuit aleatórias que formam pares dominados quando pagas."
          ],
          "example": {
            "title": "Exemplo · bloqueador mais jogabilidade",
            "detail": "A♠ 5♠ no big blind pode às vezes dar 3-bet em uma abertura do botão. Ela bloqueia ases premium e ainda pode formar sequências com o ás baixo ou o nut flush."
          }
        },
        {
          "heading": "Use a posição para escolher o tamanho",
          "body": "Fora de posição, use um tamanho maior porque quem abriu realizará a equidade mais facilmente se pagar. Contra uma abertura de 2.5 big blinds com 100 big blinds, cerca de 8 big blinds em posição e de 9 a 11 big blinds fora de posição são referências práticas de aprendizado. Adicione mais quando um pagamento criar uma situação de squeeze.",
          "takeaway": "Antes de aumentar, saiba se a mão é de valor ou de pressão, o tamanho que vai usar e como vai responder a um 4-bet."
        }
      ]
    },
    "lesson-preflop-facing-three-bet": {
      "sections": [
        {
          "heading": "Reinicie a decisão depois do relançamento",
          "body": "Um 3-bet cria um preço novo contra um range mais estreito. As fichas do seu aumento de abertura não são mais suas. Compare a mão, as posições, o tamanho e o stack efetivo a partir da decisão atual, em vez de pagar para defender o investimento anterior.",
          "takeaway": "Trate o aumento de abertura como custo afundado e avalie o novo pote com honestidade."
        },
        {
          "heading": "Os pagamentos precisam de posição e jogabilidade robusta",
          "body": "Broadways suited em posição e alguns pares podem pagar um 3-bet normal porque realizam equidade e formam combinações fortes. Fora de posição, feche o range de pagamento: cartas altas offsuit dominadas costumam formar pares caros de segunda melhor mão em um pote inflado.",
          "bullets": [
            "Pague mais vezes em posição e contra um tamanho razoável.",
            "Desista mais vezes fora de posição ou contra um range que começou cedo.",
            "Não use um pagamento apenas para evitar levar um blefe."
          ],
          "example": {
            "title": "Exemplo · a posição protege a equidade",
            "detail": "K♠ Q♠ no botão pode pagar um 3-bet normal do big blind com mais conforto do que K♦ Q♣ pode pagar um 3-bet do small blind fora de posição."
          }
        },
        {
          "heading": "Dê 4-bet com um plano para o último aumento",
          "body": "Dê 4-bet com o topo do range por valor e use apenas um pequeno componente de blefes guiados por bloqueadores. A profundidade de stack determina o comprometimento: com 100 big blinds um 4-bet compacto pode deixar espaço para desistir de blefes selecionados, enquanto stacks mais curtos levam mãos fortes ao comprometimento direto.",
          "takeaway": "Escolha desistir, pagar ou dar 4-bet antes que a emoção entre no pote grande, e saiba o que um 5-bet significaria."
        }
      ]
    },
    "lesson-postflop-board-texture": {
      "sections": [
        {
          "heading": "Comece pela conexão e os naipes",
          "body": "Os boards secos contêm poucos draws de sequência ou flush imediatos. Boards molhados conectam muitos valores ou compartilham naipes, então mais mãos podem melhorar ou já ser fortes. A textura descreve como os ranges interagem com o board, não se as cartas parecem altas ou baixas.",
          "bullets": [
            "Seco: valores desconectados com três naipes.",
            "Molhado: valores conectados, draws pareados ou duas cartas do mesmo naipe.",
            "Boards pareados reduzem algumas combinações e podem tornar uma trinca possível."
          ]
        },
        {
          "heading": "Compare os dois ranges com o board",
          "body": "Quem aumentou no pré-flop costuma ter mais combinações de carta alta, enquanto quem pagou pode ter mais conectores suited e pares pequenos. Um board seco e alto pode favorecer quem aumentou; um board baixo e conectado pode interagir fortemente com quem pagou.",
          "example": {
            "title": "Exemplo · par superior estável",
            "detail": "A♠ Q♦ em Q♣ 7♥ 2♠ é o par superior em um board seco. Poucas cartas do turn completam um draw óbvio, então muitos pares mais fracos podem continuar."
          }
        },
        {
          "heading": "Nomeie as cartas que mudam o plano",
          "body": "Antes de agir, identifique turns ou rivers que completem draws, criem uma overcard, pareiem o board ou deixem a textura quase igual. Planejar por classes de cartas é mais útil do que tentar prever uma carta exata.",
          "takeaway": "Leia primeiro a textura e depois pergunte qual range conecta melhor e quais cartas futuras mudam essa vantagem."
        }
      ]
    },
    "lesson-postflop-continuation-bets": {
      "sections": [
        {
          "heading": "Um aumento no pré-flop não exige aposta no flop",
          "body": "Uma aposta de continuação é simplesmente uma aposta no flop feita pelo agressor do pré-flop. Funciona melhor quando seu range tem vantagem, o board está estável e um oponente precisa defender. Passar faz parte de uma estratégia completa, não é uma admissão de que errou."
        },
        {
          "heading": "Use apostas pequenas onde muitas mãos se beneficiam",
          "body": "Em boards secos e altos, uma aposta pequena pode conquistar desistências de mãos sem par arriscando pouco. Mãos fortes também usam esse tamanho para que a aposta não revele se você conectou.",
          "example": {
            "title": "Exemplo · aposta de range pequena",
            "detail": "Depois de aumentar no pré-flop, A♠ K♦ costuma poder apostar pequeno quando recebem um check em Q♣ 7♥ 2♠ no heads-up. Seu range contém muitas damas fortes e overpairs, e o board oferece poucos draws poderosos."
          }
        },
        {
          "heading": "Dê mais check em boards molhados ou multiway",
          "body": "Boards conectados criam mais pagamentos e aumentos fortes. Oponentes extras tornam mais provável que alguém tenha conectado. Dê mais check com mãos que erraram e de força média quando o board favorece os ranges de pagamento ou restam vários jogadores.",
          "takeaway": "Dê aposta de continuação porque o range e o board sustentam a aposta, não simplesmente porque você aumentou no pré-flop."
        }
      ]
    },
    "lesson-postflop-value-sizing": {
      "sections": [
        {
          "heading": "O valor começa com um range de pagamento",
          "body": "Uma aposta de valor ganha dinheiro quando mãos mais fracas suficientes podem pagar. Antes de escolher um tamanho, nomeie essas mãos: pares superiores mais fracos, segundos pares, pares em mão ou draws. Se você não consegue nomear pagadores mais fracos realistas, dar check pode proteger seu valor no showdown."
        },
        {
          "heading": "Deixe a textura e o range definirem o tamanho",
          "body": "Apostas pequenas mantêm um range fraco e amplo envolvido em boards secos. Apostas maiores podem cobrar dos draws ou mirar um range forte mais fechado em boards molhados. Não aposte maior automaticamente só porque a sua própria mão é forte.",
          "example": {
            "title": "Exemplo · alvo de valor no turn",
            "detail": "A♠ Q♦ em Q♣ 8♥ 3♠ 6♦ pode apostar cerca de meio pote depois de um segundo check. Damas mais fracas, oitos, pares em mão e draws disponíveis ainda podem continuar."
          }
        },
        {
          "heading": "Reavalie a cada carta nova",
          "body": "Uma carta do turn pode adicionar draws ou fortalecer quem paga. O river remove toda a equidade futura e costuma reduzir as mãos que podem pagar. Reconstrua o alvo de valor em vez de repetir por hábito o tamanho da rodada anterior.",
          "takeaway": "Primeiro nomeie as mãos mais fracas que pagam; depois escolha o tamanho que essas mãos podem pagar de forma realista."
        }
      ]
    },
    "lesson-postflop-playing-draws": {
      "sections": [
        {
          "heading": "Conte apenas os outs limpos",
          "body": "Um out limpo normalmente melhora sua mão até a vencedora. Uma carta de flush que também pareia o board, ou uma carta de sequência que completa uma sequência mais alta, pode ser descontada. Comece pelo draw visível e depois remova as melhoras questionáveis.",
          "example": {
            "title": "Exemplo · draw de flush forte",
            "detail": "9♥ 8♥ em Q♥ 7♣ 2♥ tem nove outs de flush aparentes mais um potencial útil de sequência. O valor exato ainda depende de se um oponente pode ter um draw de copas mais alto."
          }
        },
        {
          "heading": "Compare a equidade com o pote final",
          "body": "Para um pagamento, divida o valor pago pelo pote depois do seu pagamento. Uma aposta de meio pote no flop oferece um preço de equilíbrio de 25%. Nove outs limpos de flush chegam ao river cerca de 35% das vezes, antes de considerar apostas futuras ou outs sujos."
        },
        {
          "heading": "Dê semi-blefe quando os dois caminhos importam",
          "body": "Um semi-blefe pode ganhar na hora por desistências ou mais tarde completando o draw. Prefira draws robustos, bloqueadores úteis e oponentes capazes de desistir. Pagar costuma ser mais limpo quando o preço é bom e o fold equity é incerto.",
          "takeaway": "Não aumente apenas porque tem um draw; aumente quando a equidade de melhora e um fold equity crível funcionam juntos."
        }
      ]
    },
    "lesson-postflop-river-decisions": {
      "sections": [
        {
          "heading": "O river não tem equidade futura",
          "body": "Não restam cartas, então os draws completaram ou erraram. Cada aposta deve ter um propósito no presente: ser pago por mãos piores ou fazer mãos melhores desistirem. Mãos de força média costumam preferir dar check e chegar ao showdown."
        },
        {
          "heading": "Aposte por valor tão fino quanto o range permitir",
          "body": "Mãos fortes de um par ainda podem apostar por valor em rivers seguros quando vários pares mais fracos pagam. Dimensione para o alvo. Uma aposta menor pode ganhar mais de um range bluff-catcher amplo do que uma aposta grande que só mãos fortes pagam.",
          "example": {
            "title": "Exemplo · limite do bluff-catcher",
            "detail": "K♠ Q♠ em K♦ 8♣ 6♥ 3♠ 2♦ continua sendo o par superior, mas diante de uma aposta grande e polarizada no river pode vencer apenas blefes. O pagamento depende do preço e da frequência de blefe esperada."
          }
        },
        {
          "heading": "Capture blefes com evidência, não com curiosidade",
          "body": "Um bluff-catcher perde para todas as mãos de valor e vence apenas blefes. Compare o preço do pagamento com uma estimativa realista de blefes e depois considere bloqueadores e tendências do oponente. Desistir de uma mão que parece forte pode ser correto contra um range com valor demais.",
          "takeaway": "No river, nomeie as mãos piores que pagam, as melhores que desistem ou os blefes que você vence antes de comprometer mais fichas."
        }
      ]
    },
    "lesson-postflop-range-advantage": {
      "sections": [
        {
          "heading": "Vantagem de range não é a sua mão exata",
          "body": "Um range tem vantagem quando todas as suas mãos prováveis têm, em média, mais equidade do que o range do oponente neste board. Quem abre pré-flop costuma ter mais ases fortes e overpairs em flops altos e desconectados, mesmo quando as duas cartas na sua mão não conectaram.",
          "takeaway": "Pergunte qual range completo conecta melhor antes de perguntar se a sua mão exata quer apostar."
        },
        {
          "heading": "A vantagem de nuts controla os maiores potes",
          "body": "A vantagem de nuts pertence ao range com mais combinações perto do topo das mãos possíveis. Quem paga pode ter mais dois pares e sequências em boards baixos e conectados, mesmo quando quem abriu mantém uma pequena vantagem de equidade média. O range sem a vantagem de nuts deve usar menos apostas grandes.",
          "example": {
            "title": "Exemplo · quem paga tem mais mãos fortes",
            "detail": "Em 8♠ 7♥ 6♠, o big blind pode ter mais dois pares, trincas e sequências feitas do que uma abertura do cutoff. Quem abriu deveria dar check com frequência em vez de forçar uma continuation bet grande."
          }
        },
        {
          "heading": "Cada jogador extra fortalece o campo que continua",
          "body": "Em pots com vários jogadores, pelo menos um oponente conecta com mais frequência e cada jogador precisa continuar contra vários ranges. Blefe menos, aposte por valor de forma mais seletiva e evite presumir que um aumento pré-flop dá permissão para pressionar a mesa inteira.",
          "takeaway": "À medida que o número de jogadores sobe, exija um respaldo de range mais forte e um alvo mais claro antes de apostar."
        }
      ]
    },
    "lesson-postflop-three-bet-pots": {
      "sections": [
        {
          "heading": "A ação pré-flop estreita os dois ranges",
          "body": "Um pote de 3-bet começa com mais pares premium, ases fortes e cartas broadway do que um pote com uma única raise. O pote inicial maior também reduz o SPR, então uma ou duas apostas pós-flop podem comprometer uma parte significativa do stack.",
          "takeaway": "Não copie as frequências de um pote com uma única raise para um pote de 3-bet sem reconstruir os dois ranges."
        },
        {
          "heading": "Boards altos e secos costumam suportar pressão pequena",
          "body": "Quem faz o 3-bet costuma ter mais A-K, A-Q e overpairs. Em um flop com as ou rei alto e desconectado, uma aposta pequena pode funcionar com boa parte desse range, porque quem pagou tem menos mãos muito fortes e poucos draws urgentes.",
          "example": {
            "title": "Exemplo · aposta pequena favorável ao range",
            "detail": "Depois de dar 3-bet no botão e ser pago, K♠ Q♣ pode apostar pouco em A♦ 7♣ 2♥. A vantagem de range gera pressão mesmo quando a mão exata errou o flop."
          }
        },
        {
          "heading": "Boards conectados exigem contenção",
          "body": "Boards baixos conectados e de dois naipes dão a quem pagou mais trincas, dois pares e draws fortes. Dê check com mais frequência, especialmente com cartas altas sem par. Ao apostar, use um tamanho e uma seleção de mãos que resistam a raises e turns difíceis.",
          "takeaway": "Um pote pré-flop maior aumenta o custo da agressão automática; deixe a conexão com o board escolher o plano no flop."
        }
      ]
    },
    "lesson-postflop-turn-barrels": {
      "sections": [
        {
          "heading": "Classifique o que o turn mudou",
          "body": "Um turn pode favorecer o agressor, favorecer quem pagou, completar um draw, criar novos draws ou quase não mudar nada. Reconstrua a comparação de ranges antes de repetir a ação do flop. Uma carta aparentemente inofensiva pode melhorar os pares e os draws de quem pagou."
        },
        {
          "heading": "Barrele quando restam dois caminhos para ganhar",
          "body": "Mãos fortes de valor podem cobrar de mãos feitas mais fracas e de draws. Semi-blefes funcionam melhor quando podem melhorar e também fazer mãos melhores desistirem. Overcards, draws de flush, draws de sequência e bloqueadores úteis podem se combinar em uma segunda aposta crível.",
          "example": {
            "title": "Exemplo · equidade mais pressão",
            "detail": "A♥ 5♥ em K♥ 7♣ 2♥ Q♠ mantém o draw de flush nuts e bloqueia continuações fortes de as alto. Depois de uma aposta no flop paga, ela pode usar um barrel controlado no turn contra um range com muitas mãos de um par."
          }
        },
        {
          "heading": "Desista quando a história e a equidade desaparecem",
          "body": "Uma aposta no flop paga elimina muitas desistências automáticas. Se o turn fortalece quem pagou, sua mão tem pouca equidade de melhora e seus bloqueadores removem desistências em vez de pagamentos, dar check é disciplina, não passividade. Guarde fichas para um candidato melhor.",
          "takeaway": "Antes de barrelear, nomeie os pagamentos mais fracos, as mãos melhores que desistiriam e as cartas que ainda podem melhorar sua mão."
        }
      ]
    },
    "lesson-postflop-river-polarization": {
      "sections": [
        {
          "heading": "Comece pelo alvo, não pelo botão",
          "body": "Sem cartas por vir, uma aposta no river precisa ser paga por mãos piores ou fazer mãos melhores desistirem. Nomeie essas mãos antes de escolher um tamanho. Se nenhum dos grupos é realista, dar check costuma ser a referência disciplinada.",
          "takeaway": "Um tamanho no river só é útil quando o range-alvo está claro."
        },
        {
          "heading": "Mantenha o valor fino convidativo",
          "body": "Mãos fortes de um par podem apostar por valor em rivers seguros quando pares mais fracos ainda pagam. Tamanhos menores mantêm esses bluff catchers interessados. Apostar demais pode fazer desistirem as mãos que você vence e isolar você contra mãos mais fortes.",
          "example": {
            "title": "Exemplo · dê preço aos reis mais fracos",
            "detail": "K♠ Q♣ em K♦ 9♣ 5♥ 3♠ 2♦ pode usar uma aposta pequena no river depois de três checks do big blind. Reis piores e alguns pares podem pagar; uma overbet atacaria um range muito mais estreito."
          }
        },
        {
          "heading": "Polarize quando o range sustenta",
          "body": "Apostas grandes representam valor muito forte ou blefes, e deixam as mãos de força média no range de check. Escolha blefes que bloqueiem os pagamentos prováveis e não bloqueiem as desistências prováveis. O tamanho e a seleção de mãos precisam contar a mesma história.",
          "takeaway": "Apostas grandes no river precisam de um range polarizado, não apenas de confiança em uma mão."
        }
      ]
    },
    "lesson-postflop-river-bluff-catchers": {
      "sections": [
        {
          "heading": "Um bluff catcher só vence blefes",
          "body": "Quando sua mão perde para toda aposta de valor, a força absoluta importa menos do que a mistura de valor e blefes do oponente. Conte os draws fracassados plausíveis e as combinações de valor a partir de toda a ação, não apenas da carta do river.",
          "takeaway": "Não pague porque a mão parece forte; pague porque restam blefes suficientes."
        },
        {
          "heading": "Deixe o preço definir o limite",
          "body": "Divida o pagamento pelo pote final depois de pagar. Pagar 8 big blinds para ganhar um pote final de 40 exige 20% de equidade, enquanto pagar 30 para ganhar 84 exige cerca de 36%. Uma aposta maior exige uma leitura de blefe muito mais forte.",
          "example": {
            "title": "Exemplo · a mesma mão, um preço diferente",
            "detail": "A♣ J♣ em J♦ 8♠ 6♥ 3♣ 2♠ pode pagar uma aposta pequena no river contra draws fracassados, mas desistir diante de uma overbet grande de uma linha carregada de valor. A mão não mudou; a frequência de blefe exigida mudou."
          }
        },
        {
          "heading": "Use bloqueadores como evidência de apoio",
          "body": "Um bluff catcher útil pode bloquear valor deixando os draws fracassados disponíveis. O perfil de bloqueadores oposto pode piorar um pagamento tentador. Bloqueadores refinam uma estimativa realista do range; eles não resgatam uma linha com poucos blefes naturais.",
          "takeaway": "Combine preço, ação e bloqueadores — nunca use uma única pista de forma isolada."
        }
      ]
    },
    "lesson-tournament-stack-zones": {
      "sections": [
        {
          "heading": "Big blinds tornam os stacks comparáveis",
          "body": "Uma contagem de fichas só tem significado ao lado das blinds atuais. Divida o stack efetivo pelo big blind antes de cada decisão importante. Quarenta big blinds deixam espaço para várias ruas; doze big blinds podem fazer uma raise pré-flop comprometer grande parte do stack.",
          "takeaway": "Recalcule o stack efetivo em big blinds quando as blinds sobem ou quando um jogador mais curto entra no pote."
        },
        {
          "heading": "Use as zonas como lembretes de planejamento",
          "body": "Acima de cerca de 30 big blinds, raises normais e planos pós-flop continuam disponíveis. Entre 16 e 30 big blinds, use tamanhos eficientes e planeje a resposta a um all-in. Com 15 big blinds ou menos, muitas decisões de quem age primeiro se simplificam para all-in ou desistência, porque uma raise pequena pode criar um pote comprometido desconfortável.",
          "bullets": [
            "Fundo: preserve espaço pós-flop e evite all-ins desnecessários.",
            "Médio: aumente com eficiência e saiba a resposta a um all-in.",
            "Curto: priorize o fold equity e evite pagamentos especulativos que consomem o stack."
          ]
        },
        {
          "heading": "O menor stack ativo define a decisão",
          "body": "O stack efetivo é o máximo que qualquer um dos dois pode perder na mão. Se você tem 40 big blinds e o oponente tem 12, a decisão heads-up se comporta como um pote de 12 big blinds. Fichas extras atrás não criam implied odds adicionais contra esse jogador.",
          "takeaway": "Use o menor stack vivo — não a sua própria contagem de fichas — para escolher o plano de comprometimento.",
          "example": {
            "title": "Exemplo · o stack efetivo, não o exibido",
            "detail": "Você tem 38 big blinds no botão com A♠ 9♠, mas o big blind tem 13. Planeje o confronto em torno de 13 big blinds."
          }
        }
      ]
    },
    "lesson-tournament-short-stack-opens": {
      "sections": [
        {
          "heading": "A posição ainda controla o range de entrada",
          "body": "Stacks curtos não transformam toda mão em all-in. A posição inicial precisa passar por vários ranges vivos, enquanto o botão ou o small blind pode pressionar menos jogadores. Aperte as mãos offsuit fracas nas posições iniciais e ataque de forma mais seletiva quando restarem apenas as blinds.",
          "takeaway": "A urgência do stack curto muda o tamanho da decisão, não o valor da posição."
        },
        {
          "heading": "Use o menor aumento que mantém o plano claro",
          "body": "Com cerca de 18 a 30 big blinds, uma abertura de 2 a 2.25 big blinds arrisca menos e aplica pressão parecida com a de um tamanho maior de cash game. Antes de aumentar, decida quais mãos pagam, desistem ou continuam contra um all-in de cada jogador atrás.",
          "example": {
            "title": "Exemplo · abertura eficiente com stack médio",
            "detail": "A♥ 10♥ no botão de seis jogadores com 24 big blinds pode abrir para cerca de 2.2 big blinds e ainda tomar uma decisão deliberada contra qualquer uma das blinds."
          }
        },
        {
          "heading": "Vá de all-in quando a raise pequena não cria um ramo útil",
          "body": "Com cerca de 15 big blinds ou menos, um all-in direto pode combinar fold equity imediato com toda a equidade da mão quando pago. Prefira mãos e posições que rendam razoavelmente contra os ranges de pagamento. Desista das mãos que dependem de vários oponentes falharem em despertar com força.",
          "takeaway": "Um all-in é útil quando elimina uma decisão desconfortável de aumentar e desistir — não apenas porque o stack parece incômodo."
        }
      ]
    },
    "lesson-tournament-reshoves-calls": {
      "sections": [
        {
          "heading": "Re-shove contra o range real de quem abriu",
          "body": "Uma abertura de posição tardia costuma começar mais larga do que uma de posição inicial. Com um stack curto, ases fortes e pares podem re-shove por valor contra um range amplo do botão, enquanto as mesmas mãos podem exigir cautela contra uma abertura inicial disciplinada.",
          "takeaway": "Não rotule uma mão de “re-shove” sem nomear a posição de quem abriu e o range provável."
        },
        {
          "heading": "Dinheiro morto ajuda só depois da força do range",
          "body": "Blinds, antes e uma raise de abertura criam fichas que você pode ganhar de imediato. Essa recompensa pode apoiar um all-in, mas não torna rentáveis as mãos dominadas contra um range de continuação apertado. Estime quem desiste, quem paga e como sua mão se comporta quando paga.",
          "example": {
            "title": "Exemplo · re-shove de valor",
            "detail": "A♣ Q♣ com 16 big blinds no big blind pode re-shove sobre uma abertura ampla do botão. Ela tem equidade forte quando paga e pode ganhar a abertura mais as blinds de imediato."
          }
        },
        {
          "heading": "Pagar um all-in exige evidência mais forte",
          "body": "Quem paga não tem fold equity, então a mão precisa vencer parte suficiente do range de all-in pelo preço oferecido. Pague mais largo contra um all-in curto de posição tardia e mais apertado contra um de posição inicial. Fichas já postas melhoram o preço, mas não apagam o domínio.",
          "takeaway": "Para pagamentos, remova o fold equity da história e compare a mão diretamente com o range de all-in e o preço."
        }
      ]
    },
    "lesson-tournament-risk-premium": {
      "sections": [
        {
          "heading": "Ganhos iguais em fichas nem sempre valem o mesmo no torneio",
          "body": "No cash game, ganhar 10 fichas compensa perder 10 fichas. Perto da bolha de um torneio, perder pode encerrar o evento enquanto ganhar a mesma quantidade pode apenas melhorar um stack que já estava seguro. Essa assimetria cria um prêmio de risco: um stack coberto costuma precisar de mais equidade para pagar um all-in do que as pot odds sozinhas sugerem.",
          "takeaway": "Use as odds em fichas como ponto de partida e pergunte depois quanto a eliminação custa no estado atual do torneio."
        },
        {
          "heading": "O prêmio de risco muda pagamentos mais do que a pressão de quem age primeiro",
          "body": "Pagar um all-in não tem fold equity e pode encerrar o torneio. Abrir ou ir all-in primeiro ainda pode ganhar sem resistência, então um jogador pode pressionar mais mãos e pagar menos. Evite o erro comum de ficar uniformemente apertado na bolha.",
          "bullets": [
            "Stacks médios cobertos devem evitar pagamentos de all-in marginais.",
            "Líderes em fichas podem pressionar stacks que não conseguem pagar com conforto.",
            "Stacks curtos ainda precisam aproveitar as oportunidades lucrativas de quem age primeiro."
          ]
        },
        {
          "heading": "Trate a orientação de ICM do RiverMind como uma referência prática",
          "body": "O ICM exato depende de cada stack e da estrutura de premiação. O RiverMind usa ajustes de risco limitados e explicáveis — não tabelas de solver. Quando os detalhes da premiação ou os ranges dos oponentes são incertos, mantenha a conclusão direcional: pagar mais apertado, pressionar mais largo ou quase nenhuma mudança relevante.",
          "takeaway": "Nunca apresente um ajuste de ICM simplificado como uma tabela exata do torneio.",
          "example": {
            "title": "Exemplo · mesmo pote, custo diferente",
            "detail": "Três jogadores restam e dois avançam. Com A♠ 10♦, um stack médio coberto pelo líder deve recusar um pagamento de all-in marginal que poderia ser razoável longe da bolha."
          }
        }
      ]
    },
    "lesson-tournament-stack-coverage": {
      "sections": [
        {
          "heading": "A cobertura determina a ameaça de eliminação",
          "body": "Um jogador cobre outro quando pode ganhar todo o stack dele. Se o líder em fichas der all-in contra você, pagar e perder pode eliminar você. Se você cobre um stack curto, perder o mesmo pote dói, mas não necessariamente encerra o evento. Essa diferença muda a interação de ranges antes de considerar as cartas.",
          "takeaway": "Antes de uma decisão de all-in, identifique quem cobre quem e quais stacks sobrevivem a uma perda."
        },
        {
          "heading": "Líderes pressionam; stacks médios evitam colisões",
          "body": "Um líder pode abrir com mais frequência quando os oponentes cobertos precisam proteger a sobrevivência. Um stack médio deve ser especialmente cauteloso ao disputar um pote enorme com o líder enquanto um stack mais curto está perto da eliminação. Isso não significa desistir de mãos premium nem atacar às cegas: muda as vantagens marginais.",
          "example": {
            "title": "Exemplo · o stack mais curto importa",
            "detail": "Com stacks de 42, 21 e 6 big blinds e duas vagas em disputa, o stack de 21 big blinds deve evitar um pagamento justo contra o líder enquanto o stack de 6 continua vivo."
          }
        },
        {
          "heading": "Stacks curtos não podem esperar para sempre",
          "body": "O stack mais curto tem menos valor de sobrevivência para proteger e menos mãos futuras antes que as blinds o consumam. O fold equity agindo primeiro costuma ser seu melhor recurso. Ainda assim, considere posição e ranges de pagamento: “ser o mais curto” não é permissão para dar all-in com quaisquer duas cartas contra a mesa inteira.",
          "takeaway": "A cobertura muda o preço do fracasso, mas a qualidade da mão, a posição e o fold equity ainda determinam a ação."
        }
      ]
    },
    "lesson-tournament-bubble-decisions": {
      "sections": [
        {
          "heading": "Leia o estado do torneio antes das cartas",
          "body": "Conte os jogadores restantes, identifique as vagas que pagam ou classificam, ordene os stacks vivos e anote a cobertura. Depois converta o stack efetivo em big blinds. Isso evita que um hábito familiar do cash game anule os incentivos reais do torneio.",
          "bullets": [
            "Quantos jogadores restam e quantos avançam?",
            "Quem é o mais curto e quem cobre você?",
            "Isso é um pagamento sem fold equity ou uma ação de quem age primeiro?"
          ]
        },
        {
          "heading": "Mude as decisões marginais, não as óbvias",
          "body": "A pressão da bolha deve empurrar decisões apertadas para a desistência e a pressão lucrativa de quem age primeiro para a ação. Ela não deve transformar uma mão dominada em um pagamento nem uma mão premium em uma desistência automática. Se a referência do cash game está longe do limite, o ajuste de torneio costuma ser pequeno.",
          "takeaway": "Aplique o prêmio de risco na borda do range, não como motivo para abandonar os fundamentos do pôquer."
        },
        {
          "heading": "Enuncie o pressuposto por trás da recomendação",
          "body": "Uma explicação útil de torneio nomeia a relação de stacks e o pressuposto de range: “mais apertado porque o líder cobre você e resta um stack de seis big blinds”, ou “mais largo agindo primeiro porque restam apenas dois stacks limitados pelo risco”. Se essa frase não pode ser completada, o ajuste provavelmente é vago demais.",
          "takeaway": "Um bom conselho de torneio nomeia a fonte da pressão em vez de dizer apenas “ICM”.",
          "example": {
            "title": "Exemplo · pressão explicável",
            "detail": "Como líder com 35 big blinds no botão, K♣ 9♣ pode abrir com eficiência contra dois stacks de 14 big blinds que enfrentam a eliminação se continuarem."
          }
        }
      ]
    },
    "lesson-opponents-evidence": {
      "sections": [
        {
          "heading": "Observe decisões, não resultados",
          "body": "Um blefe mostrado é um ponto de dados, não a prova de que alguém sempre blefa. Registre a situação pública: posição, preço, rua e se o jogador apostou, pagou, aumentou ou desistiu. Um pote perdido pode conter uma decisão forte, e um pote ganho pode conter um erro.",
          "bullets": [
            "Os estilos paciente e grudento se separam por entradas repetidas e frequências de pagamento.",
            "Os estilos de pressão e engano se separam por agressão repetida e pelo seu momento.",
            "Contra um estilo equilibrado, sem vazamento repetido em uma única direção, mantenha a referência intacta."
          ],
          "takeaway": "Descreva o que aconteceu repetidamente antes de atribuir um rótulo ao jogador."
        },
        {
          "heading": "Exija uma amostra relevante",
          "body": "Duas mãos são uma pista; não são uma leitura estável. Procure pelo menos três decisões semelhantes e prefira oito ou mais mãos observadas antes de fazer um ajuste significativo. Uma leitura de loose play pré-flop não prova automaticamente que o mesmo jogador blefa demais no river.",
          "bullets": [
            "Combine a evidência com o mesmo tipo de situação.",
            "Reduza o ajuste quando a amostra for pequena.",
            "Atualize a leitura quando ações novas divergirem."
          ]
        },
        {
          "heading": "Mantenha a estratégia base por baixo",
          "body": "Uma exploração deve ser uma mudança medida a partir de uma referência sólida. Com evidência fraca, escolha a decisão normal de range e preço. Com evidência repetida, mude a frequência ou o tamanho gradualmente em vez de saltar a um extremo.",
          "takeaway": "A confiança determina o tamanho do ajuste, não apenas a direção.",
          "example": {
            "title": "Exemplo · pista inicial, ação normal",
            "detail": "Depois de apenas dois pagamentos loose observados, A♠ 5♠ não deveria disparar um blefe no river sem equidade só porque o oponente “parece grudento”. Use o teste normal de bloqueadores e alvos de desistência."
          }
        }
      ]
    },
    "lesson-opponents-callers-folders": {
      "sections": [
        {
          "heading": "Contra quem paga muito, aposte por valor de forma mais direta",
          "body": "Quando a evidência repetida mostra pagamentos demais, amplie com moderação o valor fino e escolha tamanhos que o range mais fraco ainda possa pagar. Reduza os blefes de baixa equidade, porque as desistências exigidas são menos prováveis. Não confunda “paga com frequência” com “nunca desiste”: pressão forte e preços ruins continuam importando.",
          "takeaway": "Ranges grudentos recompensam o valor e punem blefes sem apoio."
        },
        {
          "heading": "Contra quem desiste muito, pressione ranges capados",
          "body": "Quando um jogador desiste repetidamente a apostas razoáveis, adicione blefes selecionados com bloqueadores ou potencial de melhora. Evite blefar demais contra ranges claramente fortes; um jogador que desiste de muitas mãos fracas ainda pode continuar corretamente com as fortes.",
          "example": {
            "title": "Exemplo · pressão apoiada por evidência",
            "detail": "Depois de doze mãos e cinco desistências em pots com uma única raise comparáveis, Q♣ J♣ pode barrelear um draw forte com mais frequência do que contra um oponente desconhecido."
          }
        },
        {
          "heading": "Ajuste uma alavanca por vez",
          "body": "Comece pela frequência: blefe um pouco menos ou aposte por valor um pouco mais. Mude o tamanho só quando puder nomear o range-alvo. Ampliar o range e usar tamanhos extremos ao mesmo tempo dificulta saber se a leitura ou a execução causou o resultado.",
          "takeaway": "Uma exploração pequena e explicável ensina mais do que um ajuste de tudo ou nada."
        }
      ]
    },
    "lesson-opponents-aggression-traps": {
      "sections": [
        {
          "heading": "Agressão mais larga cria mais valor de bluff catch",
          "body": "Um jogador que aposta e aumenta em muitos pontos críveis chega com mais combinações fracas do que um jogador paciente. Com uma amostra suficiente e um preço justo, defenda mais bluff catchers. Continue respeitando a textura do board e os bloqueadores; agressão sozinha não torna todo pagamento lucrativo.",
          "takeaway": "Amplie a defesa apenas onde a agressão observada pode conter blefes realistas."
        },
        {
          "heading": "A agressão paciente representa mais força",
          "body": "Um oponente seletivo que de repente aumenta depois de muitas mãos passivas costuma merecer mais crédito. Desista com mais facilidade dos bluff catchers marginais e das mãos feitas fracas, especialmente quando a linha tem poucos draws fracassados naturais.",
          "example": {
            "title": "Exemplo · respeite uma raise rara",
            "detail": "Depois de dezesseis mãos observadas com pouca agressão, K♠ Q♦ em K♥ 9♣ 4♠ 4♦ 2♣ pode desistir com mais conforto diante de uma raise grande no river."
          }
        },
        {
          "heading": "O engano exige proteção de range, não adivinhação",
          "body": "Um jogador enganoso pode atrasar a agressão ou slow-playar mãos fortes. Mantenha algumas mãos fortes nos seus ranges de check e de pagamento para que a ação posterior fique protegida. Não tente identificar a armadilha exata; compare o range completo de valor e blefes com o seu preço.",
          "takeaway": "Contra armadilhas, proteja ranges e preços de decisão em vez de tentar ler mentes."
        }
      ]
    },
    "lesson-math-implied-odds": {
      "sections": [
        {
          "heading": "As odds diretas param no pote atual",
          "body": "As pot odds diretas comparam o pagamento com o pote final se nenhuma ficha adicional entrar. As implied odds adicionam fichas futuras que você espera ganhar depois de melhorar. Elas importam mais para mãos fortes disfarçadas, stacks fundos, posição e oponentes propensos a pagar outra aposta.",
          "takeaway": "Fichas futuras contam apenas quando a melhora e o pagamento são realistas."
        },
        {
          "heading": "Estime o valor futuro que falta",
          "body": "Primeiro calcule o limite direto do pagamento. Se a sua equidade fica aquém, estime quantos big blinds extras você precisa ganhar depois para fechar a diferença. Compare esse alvo com o stack efetivo e uma aposta futura realista — não com todo o stack restante do oponente.",
          "example": {
            "title": "Exemplo · par pequeno com espaço atrás",
            "detail": "Pagar 2 big blinds com 6♠ 6♦ pode ser razoável quando restam mais de 60 big blinds e um overpair forte provavelmente paga uma aposta significativa depois que você faz uma trinca no flop."
          }
        },
        {
          "heading": "A posição melhora a realização",
          "body": "Agir por último facilita coletar valor depois de melhorar e evitar pagar a mais quando erra. Pots com vários jogadores podem aumentar o pagamento potencial, mas também criam draws concorrentes mais fortes. Mantenha a estimativa conservadora.",
          "takeaway": "Implied odds são um ajuste baseado em evidência, não permissão para pagar qualquer draw."
        }
      ]
    },
    "lesson-math-reverse-implied-odds": {
      "sections": [
        {
          "heading": "Nem todo out cria um vencedor limpo",
          "body": "Reverse implied odds são perdas futuras depois de formar uma segunda melhor mão. Um draw de flush baixo pode completar e perder para um flush mais alto; um as dominado pode formar par e perder para um kicker melhor. Esses resultados fazem a mão valer menos do que uma contagem simples de outs sugere.",
          "takeaway": "Desconte os outs que melhoram sua mão sem torná-la de forma confiável a melhor."
        },
        {
          "heading": "O potencial de nuts importa mais com stacks fundos",
          "body": "Stacks fundos aumentam tanto os ganhos implícitos quanto as perdas inversas implícitas. Cartas pequenas do mesmo nape parecem atrativas, mas um pote grande em um board com quatro cartas do mesmo nape costuma concentrar a ação em torno de flushes mais altos. Prefira draws que podem fazer os nuts ou que são fáceis de largar.",
          "example": {
            "title": "Exemplo · risco de flush dominado",
            "detail": "7♥ 5♥ em K♥ J♥ 2♣ tem um draw de flush, mas uma ação forte de um range de posição inicial pode incluir muitos copas mais altos. Trate menos de todos os nove copas como cartas limpas de valor."
          }
        },
        {
          "heading": "Use uma margem de equidade conservadora",
          "body": "Quando os outs estão sujos ou a ação futura será difícil, exija mais do que o limite básico de pagamento. Largar um draw apertado não é “ignorar as odds”: é contabilizar a qualidade da equidade e o custo de erros posteriores.",
          "takeaway": "Compare com o preço a equidade de vitórias limpas — não apenas a chance de formar uma mão com nome."
        }
      ]
    },
    "lesson-math-break-even-bluffs": {
      "sections": [
        {
          "heading": "Risco dividido por risco mais recompensa",
          "body": "Para um blefe puro sem equidade de showdown, as desistências exigidas = aposta ÷ (aposta + pote antes da aposta). Apostar 10 sobre 20 arrisca 10 para ganhar 20, então exige desistências acima de 10 ÷ 30, ou cerca de 33%, antes de considerar o rake ou a ação futura.",
          "bullets": [
            "Blefe de meio pote: exige cerca de 33% de desistências.",
            "Blefe de dois terços do pote: exige cerca de 40% de desistências.",
            "Blefe do tamanho do pote: exige 50% de desistências."
          ],
          "takeaway": "Memorize os limites comuns e verifique se o range do oponente realmente pode desistir com essa frequência."
        },
        {
          "heading": "A equidade do semi-blefe reduz a exigência de desistências",
          "body": "Um draw ainda pode ganhar quando pago, então ele exige menos desistências imediatas do que um blefe puro. O valor exato depende da equidade, da realização e da ação futura. Use o percentual do blefe puro como teto conservador e confirme que o draw tem caminhos limpos de melhora.",
          "takeaway": "A equidade quando pago ajuda apenas quando o draw é limpo e provavelmente realizará seu valor.",
          "example": {
            "title": "Exemplo · dois caminhos para ganhar",
            "detail": "A♣ 5♣ em K♦ 8♣ 3♣ pode ganhar quando uma aposta de meio pote provoca desistências e pode melhorar para o flush nuts quando paga."
          }
        },
        {
          "heading": "A matemática não inventa alvos de desistência",
          "body": "Depois de encontrar o percentual de desistências exigido, nomeie as mãos melhores que realmente desistem. Bloqueadores, vantagem de range e evidência do oponente determinam se a estimativa é plausível. Contra um range que paga muito, até um limite matematicamente modesto pode ser irreal.",
          "takeaway": "Um cálculo de blefe só está completo quando o range fornece desistências críveis suficientes."
        }
      ]
    }
  },
  "trainers": {
    "trainer-percentages": {
      "questions": {
        "nine-outs-next-card": {
          "prompt": "Você tem 9 outs limpos no flop. Com que frequência, aproximadamente, você acerta no turn?",
          "context": "Use a estimativa rápida de uma carta ou calcule 9 ÷ 47.",
          "explanation": "9 das 47 cartas não vistas são outs: 9 ÷ 47 ≈ 19%. A regra do 2 dá uma estimativa rápida de 18%.",
          "choices": {
            "a": {
              "label": "Cerca de 9%",
              "feedback": "Isso trata cada out como cerca de 1%. Com uma carta por vir, multiplique os outs limpos por cerca de 2."
            },
            "b": {
              "label": "Cerca de 19%",
              "feedback": "Correto: 9 ÷ 47 é cerca de 19%, e a regra do 2 dá uma estimativa rápida de 18%."
            },
            "c": {
              "label": "Cerca de 36%",
              "feedback": "Essa é a chance aproximada até o river quando restam duas cartas, não a chance de apenas a próxima carta."
            }
          }
        },
        "nine-outs-two-cards": {
          "prompt": "Com 9 outs limpos no flop, com que frequência, aproximadamente, você acerta até o river?",
          "context": "Suponha que você verá as duas cartas comunitárias restantes.",
          "explanation": "A chance exata é de cerca de 35%. A regra do 4 dá 36%, o que é próximo o suficiente para uma decisão rápida.",
          "choices": {
            "a": {
              "label": "Cerca de 19%",
              "feedback": "Essa é aproximadamente a chance de acertar apenas no turn."
            },
            "b": {
              "label": "Cerca de 27%",
              "feedback": "Isso é baixo demais para duas chances de acertar um de nove outs limpos."
            },
            "c": {
              "label": "Cerca de 35%",
              "feedback": "Correto: a chance exata com duas cartas é de cerca de 35%; a regra do 4 estima 36%."
            }
          }
        },
        "half-pot-call": {
          "prompt": "O pote é 100. O vilão aposta 50. De quanta equidade um pagamento precisa para o ponto de equilíbrio?",
          "context": "Você paga 50 e o pote final se torna 200.",
          "explanation": "O valor do pagamento ÷ o pote final é 50 ÷ 200 = 25%.",
          "choices": {
            "a": {
              "label": "Cerca de 20%",
              "feedback": "Isso subestima o preço porque seu pagamento de 50 fichas deve ser incluído no pote final."
            },
            "b": {
              "label": "Cerca de 25%",
              "feedback": "Correto: pagar 50 cria um pote final de 200, e 50 ÷ 200 é 25%."
            },
            "c": {
              "label": "Cerca de 33%",
              "feedback": "Esse é o preço do pagamento contra uma aposta do tamanho do pote, não uma de meio pote."
            }
          }
        },
        "three-quarter-pot-call": {
          "prompt": "O pote é 120. O vilão aposta 90. De quanta equidade um pagamento precisa?",
          "context": "Depois de pagar 90, o pote final será 300.",
          "explanation": "90 ÷ 300 = 30%. Não divida apenas pelo pote anterior ao seu pagamento.",
          "choices": {
            "a": {
              "label": "Cerca de 25%",
              "feedback": "Esse é o preço familiar contra uma aposta de meio pote; essa aposta é maior."
            },
            "b": {
              "label": "Cerca de 30%",
              "feedback": "Correto: após pagar, o pote final é 300, então 90 ÷ 300 é 30%."
            },
            "c": {
              "label": "Cerca de 43%",
              "feedback": "Isso compara a aposta com o pote anterior ao seu pagamento, em vez do pote final que você pode ganhar."
            }
          }
        },
        "eight-outs-river": {
          "prompt": "Você tem 8 outs limpos no turn. Com que frequência, aproximadamente, você acerta no river?",
          "context": "Falta uma carta por vir e há 46 cartas não vistas.",
          "explanation": "8 ÷ 46 ≈ 17%. Multiplicar os outs por 2 dá uma estimativa rápida de 16%.",
          "choices": {
            "a": {
              "label": "Cerca de 9%",
              "feedback": "Isso está mais próximo de quatro outs com uma carta por vir."
            },
            "b": {
              "label": "Cerca de 17%",
              "feedback": "Correto: 8 ÷ 46 é cerca de 17%, e a regra do 2 dá uma estimativa rápida de 16%."
            },
            "c": {
              "label": "Cerca de 32%",
              "feedback": "Isso aplica, em linhas gerais, a regra do 4, mas resta apenas uma carta por vir no river."
            }
          }
        }
      }
    },
    "quiz-core-decisions": {
      "questions": {
        "button-ace-jack": {
          "prompt": "Heads-up, com 100 big blinds. Você está no botão com A♠ J♦ e a ação é sua no pré-flop.",
          "context": "Escolha uma referência prática para iniciantes.",
          "explanation": "A-J está muito à frente de uma mão aleatória de big blind. Aumentar constrói valor e aproveita a sua vantagem de posição. Estratégias fortes podem incluir alguns limps, mas desistir é tight demais.",
          "choices": {
            "a": {
              "label": "Desistir",
              "feedback": "A-J é forte demais para ser descartada contra uma mão aleatória de big blind."
            },
            "b": {
              "label": "Apenas pagar",
              "feedback": "Algumas estratégias avançadas misturam limps, mas pagar apenas abre mão de um aumento de valor claro e simples."
            },
            "c": {
              "label": "Aumentar",
              "feedback": "Correto: aumente por valor e mantenha a vantagem de posição após o flop."
            }
          }
        },
        "river-bluff-catcher": {
          "prompt": "No river, o pote é 80 e o vilão aposta 80. Seu bluff-catcher ganha cerca de 25% das vezes.",
          "context": "Não há ação futura depois desse pagamento.",
          "explanation": "Uma aposta do tamanho do pote exige 33% de equidade: 80 ÷ 240. Uma estimativa honesta de 25% fica abaixo do ponto de equilíbrio, então desista.",
          "choices": {
            "a": {
              "label": "Desistir",
              "feedback": "Correto: sua estimativa de vitória de 25% fica abaixo do preço de equilíbrio de 33%."
            },
            "b": {
              "label": "Pagar",
              "feedback": "Pagar perde no longo prazo quando a estimativa de vitória indicada está abaixo da equidade exigida."
            },
            "c": {
              "label": "Aumentar",
              "feedback": "Um aumento de blefe precisa de forte evidência de desistência; o preço sozinho não a fornece."
            }
          }
        },
        "thin-river-value": {
          "prompt": "O vilão passa no river. Você tem o par maior com um kicker forte e vários pares mais fracos podem pagar.",
          "context": "Restam muito poucos draws errados no range do vilão.",
          "explanation": "Uma aposta de valor menor mira as mãos de um par mais fracas que você identificou. Passar pode entrar no mix em algumas situações, mas abrir mão automaticamente das pagas claras de mãos piores deixa valor para trás.",
          "choices": {
            "a": {
              "label": "Passar automaticamente",
              "feedback": "Passar é seguro, mas perde valor quando vários pares mais fracos podem pagar."
            },
            "b": {
              "label": "Apostar pouco por valor",
              "feedback": "Correto: escolha um tamanho que mantenha envolvidos os pares de um par mais fracos que você identificou."
            },
            "c": {
              "label": "Ir de all-in",
              "feedback": "A aposta exagerada provavelmente fará desistir as mãos mais fracas que você quer que paguem."
            }
          }
        },
        "poor-bluff-candidate": {
          "prompt": "Seu draw de flush baixo erra o river. O vilão é propenso a pagar e suas cartas não bloqueiam as pagas fortes de um par.",
          "context": "Você quase não tem valor no showdown, mas há pouca evidência de que o oponente vai desistir.",
          "explanation": "Um draw errado não é automaticamente um blefe. Contra um range propenso a pagar, sem blockers úteis, o fold equity é baixo demais. Guarde o blefe para uma melhor oportunidade.",
          "choices": {
            "a": {
              "label": "Passar",
              "feedback": "Correto: desista da mão quando o oponente paga demais e sua mão tem blockers fracos."
            },
            "b": {
              "label": "Apostar porque errou",
              "feedback": "Um draw errado não é automaticamente um blefe; primeiro identifique mãos melhores suficientes que possam desistir."
            },
            "c": {
              "label": "Sempre apostar acima do pote",
              "feedback": "Arriscar mais fichas não conserta um fold equity fraco nem efeitos de blockers fracos."
            }
          }
        }
      }
    },
    "quiz-preflop-mastery": {
      "questions": {
        "mastery-early-a8o": {
          "prompt": "Seis jogadores, com 100 big blinds. Você é o primeiro a agir com a mão mostrada acima.",
          "context": "Restam cinco jogadores com cartas vivas atrás de você.",
          "explanation": "A-8 offsuit não tem qualidade de cartas e jogabilidade suficientes para superar cinco ranges. A posição torna essa uma desistência disciplinada.",
          "choices": {
            "fold": {
              "label": "Desistir",
              "feedback": "Correto: o ás fraco offsuit é dominado com frequência demais com cinco ranges ainda atrás."
            },
            "limp": {
              "label": "Pagar 1 big blind",
              "feedback": "Dar limp abrindo a mão convida a um pote cheio, com uma mão que frequentemente termina com o segundo melhor par maior."
            },
            "raise": {
              "label": "Aumentar para 2.5 big blinds",
              "feedback": "Isso é loose demais para uma referência simples de posição inicial com seis jogadores."
            }
          }
        },
        "mastery-button-a8s": {
          "prompt": "Seis jogadores, com 100 big blinds. Todos desistem até você no botão.",
          "context": "Restam apenas o small blind e o big blind.",
          "explanation": "A mesma mão que desiste cedo vira um aumento no botão, porque restam menos jogadores e você terá posição quando for pago.",
          "choices": {
            "fold": {
              "label": "Desistir",
              "feedback": "Desistir abre mão de uma oportunidade lucrativa em posição tardia contra apenas dois ranges restantes."
            },
            "limp": {
              "label": "Pagar 1 big blind",
              "feedback": "Um limp pode existir em estratégias avançadas, mas aumentar é a referência mais clara para iniciantes."
            },
            "raise": {
              "label": "Aumentar para 2.5 big blinds",
              "feedback": "Correto: o suited, um blocker de ás e a posição tornam essa uma abertura prática no botão."
            }
          }
        },
        "mastery-isolate-kqs": {
          "prompt": "O cutoff dá limp de 1 big blind. Você está no botão com as duas blinds atrás.",
          "context": "Os stacks efetivos são de 100 big blinds.",
          "explanation": "K-Q suited encabeza um range típico de limp. Aumentar o tamanho contra o limper constrói valor e desestimula as blinds a entrarem barato.",
          "choices": {
            "fold": {
              "label": "Desistir",
              "feedback": "K-Q suited é forte demais para desistir contra um range típico de limp."
            },
            "call": {
              "label": "Pagar 1 big blind",
              "feedback": "Pagar é jogável, mas convida as duas blinds e perde um isolamento de valor claro."
            },
            "raise": {
              "label": "Aumentar para 5 big blinds",
              "feedback": "Correto: aumente por valor e tente jogar heads-up contra o limper, em posição."
            }
          }
        },
        "mastery-overlimp-22": {
          "prompt": "Dois jogadores dão limp. Você está no botão, os stacks são fundos e as blinds raramente aumentam.",
          "context": "Escolha a referência mais clara de baixa variância para a mesa descrita.",
          "explanation": "Um par pequeno se beneficia de um pote barato multiway apenas quando os stacks são fundos, o risco de squeeze é baixo e você tem posição.",
          "choices": {
            "fold": {
              "label": "Desistir",
              "feedback": "Desistir é seguro, mas as condições passivas e fundas tornam razoável um set-mine barato."
            },
            "call": {
              "label": "Pagar 1 big blind",
              "feedback": "Correto: posição, stacks fundos e baixo risco de squeeze sustentam um over-limp seletivo."
            },
            "raise": {
              "label": "Aumentar para 6 big blinds",
              "feedback": "Aumentar pode entrar no mix, mas esse par pequeno sofre com vários pagadores e com pressão pós-flop."
            }
          }
        },
        "mastery-aJo-early-open": {
          "prompt": "Um jogador disciplinado de posição inicial aumenta para 3 big blinds. Você está no big blind.",
          "context": "Você está com 100 big blinds e agirá primeiro após o flop.",
          "explanation": "A posição inicial de quem abriu e o tamanho maior tornam o range dele forte. A-J offsuit frequentemente cria um segundo melhor par caro.",
          "choices": {
            "fold": {
              "label": "Desistir",
              "feedback": "Correto: o range fechado de posição inicial domina demais os seus resultados de par maior."
            },
            "call": {
              "label": "Pagar 2 big blinds",
              "feedback": "O desconto da blind não supera a dominação e a má realização de equidade."
            },
            "raise": {
              "label": "Aumentar para 10 big blinds",
              "feedback": "Essa mão é um blefe simples ruim contra um range forte de posição inicial."
            }
          }
        },
        "mastery-kqs-facing-cutoff": {
          "prompt": "O cutoff aumenta para 2.5 big blinds. Você está no botão.",
          "context": "As duas blinds seguem atrás e os stacks efetivos são de 100 big blinds.",
          "explanation": "K-Q suited tem bom desempenho contra um range de abertura de cutoff. A posição torna o pagamento uma referência robusta sem inflar demais o pote.",
          "choices": {
            "fold": {
              "label": "Desistir",
              "feedback": "K-Q suited tem equidade e jogabilidade demais para desistir para uma abertura normal de cutoff."
            },
            "call": {
              "label": "Pagar 2.5 big blinds",
              "feedback": "Correto: pagar realiza a equidade da mão em posição e mantém mãos mais fracas envolvidas."
            },
            "raise": {
              "label": "Aumentar para 8 big blinds",
              "feedback": "Re-aumentar pode entrar no mix, mas pagar é a referência mais clara com essa mão jogável."
            }
          }
        },
        "mastery-87s-blind-defense": {
          "prompt": "O botão aumenta para 2.25 big blinds. O small blind desiste; você está no big blind.",
          "context": "Você já pagou 1 big blind e os stacks efetivos são de 100 big blinds.",
          "explanation": "O aumento pequeno oferece um preço favorável, e a conectividade suited cria formas robustas de melhorar após o flop.",
          "choices": {
            "fold": {
              "label": "Desistir",
              "feedback": "Desistir é tight demais para esse preço baixo contra um range amplo de posição tardia."
            },
            "call": {
              "label": "Pagar 1.25 big blinds",
              "feedback": "Correto: o desconto e a conectividade suited sustentam uma defesa prática."
            },
            "raise": {
              "label": "Aumentar para 9 big blinds",
              "feedback": "Re-aumentar pode entrar no mix, mas pagar é a forma mais simples de realizar a equidade dessa mão."
            }
          }
        },
        "mastery-a5s-three-bet": {
          "prompt": "Um botão ativo aumenta para 2.5 big blinds. O small blind desiste; você está no big blind.",
          "context": "Escolha a opção agressiva com as melhores razões estruturais.",
          "explanation": "A-5 suited é um re-aumento de blefe ocasional e deliberado: bloqueia ases fortes e mantém potencial de sequência e de flush quando pago.",
          "choices": {
            "fold": {
              "label": "Desistir",
              "feedback": "Desistir é viável, mas abre mão de um blocker útil e do potencial de wheel suited."
            },
            "call": {
              "label": "Pagar 1.5 big blinds",
              "feedback": "Pagar é viável, mas não usa o blocker de ás para criar pressão imediata."
            },
            "raise": {
              "label": "Aumentar para 9 big blinds",
              "feedback": "Correto: o ás bloqueia as continuações premium e a mão continua jogável quando pago."
            }
          }
        }
      }
    },
    "quiz-postflop-mastery": {
      "questions": {
        "postflop-mastery-dry-cbet": {
          "prompt": "Você aumentou do cutoff e o big blind pagou. Ele passa este flop seco para você.",
          "context": "O pote é 6 big blinds. Escolha a referência mais clara e favorável ao seu range.",
          "explanation": "Em heads-up em um board seco de carta alta, quem aumentou pode usar uma aposta de continuação pequena tanto com mãos feitas quanto com mãos que erraram selecionadas.",
          "choices": {
            "check": {
              "label": "Passar",
              "feedback": "Passar pode entrar no mix, mas abre mão de uma oportunidade de baixo risco em um board que favorece fortemente quem aumentou no pré-flop."
            },
            "small": {
              "label": "Apostar 2 big blinds",
              "feedback": "Correto: uma aposta de um terço do pote aplica pressão enquanto representa as muitas damas fortes e overpairs do seu range."
            },
            "large": {
              "label": "Apostar 6 big blinds",
              "feedback": "Uma aposta do tamanho do pote arrisca demais quando um tamanho menor pode pressionar as mesmas mãos sem par."
            }
          }
        },
        "postflop-mastery-wet-multiway": {
          "prompt": "Você aumentou no pré-flop e dois jogadores pagaram. Os dois oponentes passam neste flop conectado.",
          "context": "O pote é 9 big blinds. Os pagadores extras têm muitos pares, combinações de dois pares e draws de sequência.",
          "explanation": "Mais oponentes e um board muito conectado reduzem a vantagem automática de ser quem aumentou no pré-flop. Passar protege o seu range e realiza equidade.",
          "choices": {
            "check": {
              "label": "Passar",
              "feedback": "Correto: o board molhado multiway conecta fortemente com os ranges de pagamento, enquanto sua mão mantém equidade útil no turn."
            },
            "small": {
              "label": "Apostar 3 big blinds",
              "feedback": "Uma aposta pequena dificilmente fará pares ou draws robustos desistirem e pode convidar aumentos difíceis."
            },
            "large": {
              "label": "Apostar 8 big blinds",
              "feedback": "Um blefe grande contra dois ranges conectados arrisca demais sem um alvo claro de desistência."
            }
          }
        },
        "postflop-mastery-flop-value": {
          "prompt": "Você aumentou no botão, o big blind pagou e ele passa neste flop.",
          "context": "O pote é 6 big blinds. Vários pares mais fracos e draws backdoor podem continuar.",
          "explanation": "O par maior com o kicker maior tem vários alvos mais fracos que podem pagar. Um tamanho moderado captura valor sem forçar o range a ficar desnecessariamente forte.",
          "choices": {
            "check": {
              "label": "Passar",
              "feedback": "Passar protege a mão, mas perde valor claro de damas mais fracas, oitos, pocket pairs e draws."
            },
            "half": {
              "label": "Apostar 3 big blinds",
              "feedback": "Correto: meio pote mantém os pagadores mais fracos realistas envolvidos enquanto começa a construir valor."
            },
            "overbet": {
              "label": "Apostar 10 big blinds",
              "feedback": "O overbet faz desistir grande parte do range fraco que você quer que pague e isola você contra as continuações mais fortes."
            }
          }
        },
        "postflop-mastery-turn-pot-control": {
          "prompt": "Você apostou no flop e o big blind pagou. Ele passa de novo neste turn tranquilo.",
          "context": "O pote é 14 big blinds. Seu par tem valor no showdown, mas poucas mãos claramente mais fracas podem pagar mais duas apostas grandes.",
          "explanation": "Valor médio no showdown nem sempre precisa de proteção. A posição permite pegar uma carta grátis e tomar uma decisão mais informada no river.",
          "choices": {
            "check": {
              "label": "Passar",
              "feedback": "Correto: passar realiza valor no showdown, protege o seu range de check e evita inflar o pote contra reis mais fortes."
            },
            "half": {
              "label": "Apostar 7 big blinds",
              "feedback": "Existe algum valor de proteção, mas muitas mãos mais fracas desistem enquanto pares mais fortes continuam."
            },
            "pot": {
              "label": "Apostar 14 big blinds",
              "feedback": "Uma aposta do tamanho do pote isola essa mão de força média contra grande parte demais do range mais forte."
            }
          }
        },
        "postflop-mastery-flush-price": {
          "prompt": "O big blind aposta 5 big blinds em um pote de 10 big blinds neste flop.",
          "context": "Pagar 5 faz o pote final ser 20 big blinds, então o preço de equilíbrio é 25%.",
          "explanation": "O valor do pagamento dividido pelo pote final é 5 ÷ 20 = 25%. Cerca de 35% de equidade de flush até o river torna o pagamento a referência matemática limpa.",
          "choices": {
            "fold": {
              "label": "Desistir",
              "feedback": "Nove outs limpos de flush chegam ao river cerca de 35% das vezes, confortavelmente acima do preço de 25%."
            },
            "call": {
              "label": "Pagar 5 big blinds",
              "feedback": "Correto: o draw do nut flush tem equidade suficiente para esse preço sem assumir que o oponente vai desistir."
            },
            "shove": {
              "label": "Ir de all-in",
              "feedback": "Um aumento às vezes funciona, mas o shove adiciona suposições desnecessárias de fold equity e de stack-off a um pagamento lucrativo."
            }
          }
        },
        "postflop-mastery-combo-draw": {
          "prompt": "Você pagou no botão no pré-flop. O big blind passa este flop para você.",
          "context": "O pote é 8 big blinds. Você pode melhorar para sequência ou flush e pode fazer muitas mãos sem par desistirem agora.",
          "explanation": "Draws fortes são semibluffs úteis porque as duas partes da aposta importam: mãos sem par piores podem desistir e muitas cartas te melhoram quando pago.",
          "choices": {
            "check": {
              "label": "Passar",
              "feedback": "Passar realiza equidade, mas perde uma forte oportunidade de semibluff com muitas cartas que melhoram e fold equity imediato."
            },
            "bet": {
              "label": "Apostar 5 big blinds",
              "feedback": "Correto: o combo draw robusto pode vencer por desistências agora ou melhorando quando pago."
            },
            "all-in": {
              "label": "Ir de all-in",
              "feedback": "O draw é forte, mas um overbet extremo arrisca muito mais do que o necessário para aplicar pressão útil."
            }
          }
        },
        "postflop-mastery-river-value": {
          "prompt": "O big blind passa este river após pagar duas apostas moderadas.",
          "context": "O pote é 16 big blinds. Pares maiores mais fracos e alguns segundos pares ainda podem pagar uma aposta de valor pequena.",
          "explanation": "Um river seguro deixa o par maior com kicker maior à frente de vários bluff-catchers. Um tamanho de valor pequeno combina com esse range de alvos amplo.",
          "choices": {
            "check": {
              "label": "Passar",
              "feedback": "Passar ganha no showdown, mas perde valor fino de várias mãos realistas de um par mais fracas."
            },
            "small": {
              "label": "Apostar 5 big blinds",
              "feedback": "Correto: o tamanho pequeno mira os pares mais fracos sem exigir que paguem uma aposta altamente polarizada."
            },
            "all-in": {
              "label": "Ir de all-in",
              "feedback": "Um shove grande faz desistir parte demais do range mais fraco e é pago por uma seleção muito mais forte."
            }
          }
        },
        "postflop-mastery-river-bluff-catch": {
          "prompt": "O big blind aposta 25 big blinds em um pote de 20 big blinds neste river.",
          "context": "Pagar precisa de cerca de 36% de equidade. Com base na linha e no oponente, você estima que este bluff-catcher ganha apenas 25%.",
          "explanation": "Um bluff-catcher é uma decisão de preço. Pagar 25 cria um pote final de 70 big blinds: 25 ÷ 70 ≈ 36%, acima da estimativa de vitória de 25%.",
          "choices": {
            "fold": {
              "label": "Desistir",
              "feedback": "Correto: o par maior parece forte, mas a frequência de blefe estimada não alcança o preço do pagamento."
            },
            "call": {
              "label": "Pagar 25 big blinds",
              "feedback": "A mão vence apenas blefes, e a estimativa de vitória de 25% está abaixo do requisito de cerca de 36%."
            },
            "raise": {
              "label": "Ir de all-in",
              "feedback": "Transformar valor no showdown em blefe precisa de evidência de blocker e de desistência que o cenário não fornece."
            }
          }
        }
      }
    }
  }
};
