// GENERATED by scripts/sync-locale-catalog.mjs from the JSON translation
// memory under translation-memory/pt-BR/. Edit the JSON sources and
// re-run the sync script; hand edits here will be overwritten.
// DRAFT: awaiting qualified native pt-BR poker-language review.
import type { ScenarioTemplateCatalog, ScenarioVocab } from '../scenarioCatalog';

export const portugueseScenarioTemplates: ScenarioTemplateCatalog = {
  "river-polarized-value": {
    "focus": "Valor polarizado no river",
    "opponentAction": "O big blind pagou o flop e o turn e passa depois que o river completa o flush montado desde o flop.",
    "prompt": "Como {{heroHand}} com o nut flush pode mirar um range limitado que contém flushes menores e bluff-catchers?",
    "reasoning": "{{heroHand}} com o nut flush está no topo do range no river, enquanto o oponente que passa tem menos chance de ter os nuts. Uma aposta polarizada grande constrói valor e fornece o lado de valor necessário para blefes grandes no river.",
    "takeaway": "Use os maiores tamanhos no river com mãos que permanecem confortáveis quando pagas.",
    "choices": {
      "small": {
        "label": "Apostar 12 big blinds",
        "feedback": "Uma aposta pequena recebe pagamentos, mas deixa valor para trás contra um range que pode conter muitos bluff-catchers fortes."
      },
      "check": {
        "label": "Passar",
        "feedback": "Passar remove valor do topo do seu range contra várias mãos fortes que ainda podem pagar."
      },
      "overbet": {
        "label": "Apostar 54 big blinds",
        "feedback": "O nut flush sustenta um tamanho polarizado que pode ser pago por flushes menores e bluff-catchers selecionados."
      }
    }
  },
  "short-stack-reshove": {
    "focus": "Re-aumento com stack curto",
    "opponentAction": "O botão aumenta para 2.5 big blinds. Você tem 20 big blinds efetivos.",
    "prompt": "Como a profundidade de stack deve moldar a resposta de valor com {{heroHand}}?",
    "reasoning": "Com 20 big blinds, {{heroHand}} tem equidade forte contra o range de abertura e continuação do botão. Um all-in nega equidade ao oponente e evita tamanhos de re-aumento menores desconfortáveis.",
    "takeaway": "Stacks mais curtos levam mãos fortes de pré-flop ao comprometimento direto contra aberturas amplas de posições tardias.",
    "choices": {
      "call": {
        "label": "Pagar 1.5 big blinds",
        "feedback": "Pagar mantém o range amplo, mas perde o valor limpo de se comprometer nessa profundidade."
      },
      "all-in": {
        "label": "Aumentar all-in",
        "feedback": "A relação stack-pote (SPR) baixa torna um all-in de valor direto prático contra uma abertura ampla."
      },
      "fold": {
        "label": "Desistir",
        "feedback": "{{heroHand}} é forte demais para desistir contra uma abertura de posição tardia."
      }
    }
  },
  "turn-favors-caller-check": {
    "focus": "O turn favorece quem pagou",
    "opponentAction": "O big blind pagou sua aposta no flop e passa depois que o turn conecta as cartas medianas.",
    "prompt": "Como a mudança de range deve afetar o overpair {{heroHand}}?",
    "reasoning": "O turn completa e fortalece muitas mãos conectadas no range de pagamento do flop do big blind. {{heroHand}} mantém valor de showdown, mas a mudança de range torna o controle de pote a referência mais clara.",
    "takeaway": "Refaça a comparação de ranges quando um turn completa os draws naturais e as combinações de pares de quem pagou.",
    "choices": {
      "large": {
        "label": "Apostar 18 big blinds",
        "feedback": "Uma aposta do tamanho do pote mira em um turn que melhora muitos dos pares e draws de quem pagou em mãos mais fortes."
      },
      "check": {
        "label": "Passar",
        "feedback": "Passar protege o valor de showdown e evita um pote grande contra sequências e dois pares recém-formados."
      },
      "small": {
        "label": "Apostar 6 big blinds",
        "feedback": "Uma aposta pequena de proteção pode fazer parte de uma estratégia mista, mas exige desistir com cuidado quando quem pagou aplica pressão forte."
      }
    }
  },
  "ace-blocker-three-bet": {
    "focus": "Re-aumento com bloqueador",
    "opponentAction": "Um botão ativo aumenta para 2.5 big blinds. A small blind desiste.",
    "prompt": "Qual opção agressiva {{heroHand}} pode sustentar?",
    "reasoning": "{{heroHand}} bloqueia as combinações de A-A, A-K e A-Q e mantém potencial de sequência e flush quando pago, o que a torna uma mão útil de pressão ocasional.",
    "takeaway": "Escolha re-aumentos de blefe por bloqueadores e jogabilidade — não simplesmente porque as cartas são fracas.",
    "choices": {
      "call": {
        "label": "Pagar 1.5 big blinds",
        "feedback": "Pagar usa o preço, embora o deixe fora de posição e sem iniciativa."
      },
      "raise": {
        "label": "Aumentar para 9 big blinds",
        "feedback": "O ás bloqueia as continuações premium e a carta baixa do mesmo naipe mantém equidade jogável."
      },
      "fold": {
        "label": "Desistir",
        "feedback": "Desistir é aceitável, mas abre mão do bloqueador desta mão e da jogabilidade do mesmo naipe."
      }
    }
  },
  "missed-draw": {
    "focus": "Seleção de blefes",
    "opponentAction": "O big blind passa. Este oponente paga demais, e suas cartas não bloqueiam os pagamentos fortes de mãos de um par.",
    "prompt": "O draw perdido deve blefar?",
    "reasoning": "Perder um draw não cria automaticamente um blefe lucrativo. Esta combinação de oponente, board e bloqueadores oferece fold equity insuficiente.",
    "takeaway": "Blefe porque o range pode desistir — não simplesmente porque o seu draw perdeu.",
    "choices": {
      "pot": {
        "label": "Apostar 30 big blinds",
        "feedback": "Uma aposta maior arrisca mais fichas sem evidência de que este oponente vai largar pares suficientes."
      },
      "small": {
        "label": "Apostar 10 big blinds",
        "feedback": "Uma aposta pequena dá a um oponente que paga muito um preço fácil e não tem um alvo claro de mãos melhores."
      },
      "check": {
        "label": "Passar",
        "feedback": "Fold equity baixo e bloqueadores fracos tornam essa uma desistência disciplinada."
      }
    }
  },
  "bubble-leader-pressure": {
    "focus": "Pressão do líder em fichas",
    "opponentAction": "Duas vagas avançam. Você cobre as duas blinds de 14 big blinds, e todos desistem até você.",
    "prompt": "Qual plano de primeira entrada usa a pressão de sobrevivência sem arriscar toda a liderança?",
    "reasoning": "As duas blinds enfrentam eliminação se continuarem, então {{heroHand}} pode abrir com eficiência. A vantagem sustenta pressão mais frequente, não um all-in extremo que arrisca a liderança em fichas.",
    "takeaway": "Líderes convertem a cobertura em pressão pequena e frequente, não em embates de all-in imprudentes.",
    "choices": {
      "fold": {
        "label": "Desistir",
        "feedback": "{{heroHand}} tem qualidade de cartas e pressão de botão suficientes para abrir contra dois ranges limitados."
      },
      "shove": {
        "label": "Ir all-in",
        "feedback": "Arriscar mais de 30 big blinds é desnecessário quando uma abertura pequena captura a maior parte da pressão da bolha."
      },
      "raise": {
        "label": "Aumentar para 2.1 big blinds",
        "feedback": "Uma abertura compacta pressiona as duas blinds e preserva a capacidade de responder a um all-in."
      }
    }
  },
  "premium-three-bet": {
    "focus": "Enfrentando um 3-bet",
    "opponentAction": "Você aumentou para 2.5 big blinds, o small blind desistiu e o big blind re-aumentou.",
    "prompt": "Qual é o plano de valor mais claro com {{heroHand}}?",
    "reasoning": "{{heroHand}} quer construir um pote grande contra o range mais forte de continuações do oponente. Um aumento controlado aplica pressão sem saltar direto para um all-in desnecessário.",
    "takeaway": "Quando você tem o topo do seu range, responda à pressão construindo valor—não protegendo o resultado.",
    "choices": {
      "call": {
        "label": "Pagar 6 big blinds",
        "feedback": "Pagar pode emboscar, mas deixa valor na mesa e permite que o oponente realize equidade barato."
      },
      "raise": {
        "label": "Aumentar para 21 big blinds",
        "feedback": "Um 4-bet controlado constrói valor e ainda deixa espaço para mãos premium mais fracas continuarem."
      },
      "fold": {
        "label": "Desistir",
        "feedback": "{{heroHand}} está no topo absoluto do seu range e não pode desistir para um 3-bet normal."
      }
    }
  },
  "button-suited-open": {
    "focus": "Abertura no botão",
    "opponentAction": "Todos os jogadores antes de você desistem. Restam apenas as blinds.",
    "prompt": "Como a posição deve influenciar {{heroHand}}?",
    "reasoning": "Com apenas dois jogadores atrás e posição pós-flop garantida quando pago, {{heroHand}} é uma abertura prática de botão.",
    "takeaway": "A posição tardia adiciona aberturas lucrativas porque menos ranges restam e você age por último após o flop.",
    "choices": {
      "fold": {
        "label": "Desistir",
        "feedback": "Desistir é seguro, mas abre mão de uma oportunidade útil de abertura em posição tardia."
      },
      "raise": {
        "label": "Aumentar para 2.5 big blinds",
        "feedback": "{{heroHand}} tem jogabilidade suficiente para pressionar dois ranges aleatórios de blinds."
      },
      "limp": {
        "label": "Pagar 1 big blind",
        "feedback": "Um plano simples de aumentar como primeiro usa a posição com mais eficácia do que pagar a blind."
      }
    }
  },
  "dominated-broadway-fold": {
    "focus": "Evitando a dominação",
    "opponentAction": "Um jogador disciplinado em posição inicial aumenta para 3 big blinds.",
    "prompt": "Como você deve tratar {{heroHand}} contra este range?",
    "reasoning": "{{heroHand}} frequentemente forma um segundo par dominado contra uma abertura apertada de posição inicial e precisa jogar o flop, o turn e o river fora de posição.",
    "takeaway": "Desista mais frequentemente de broadways dominados de naipes diferentes conforme quem abre está mais cedo e usa um tamanho maior.",
    "choices": {
      "raise": {
        "label": "Aumentar para 10 big blinds",
        "feedback": "Esta mão não tem os blockers nem a equidade robusta para um re-aumento de blefe simples."
      },
      "fold": {
        "label": "Desistir",
        "feedback": "O range inicial domina muitos dos seus resultados de par superior."
      },
      "call": {
        "label": "Pagar 2 big blinds",
        "feedback": "Um desconto pequeno não conserta a jogabilidade ruim contra um range forte fora de posição."
      }
    }
  },
  "short-stack-open": {
    "focus": "Abertura com stack curto",
    "opponentAction": "Todos desistem até você com 25 big blinds efetivos.",
    "prompt": "Como o stack mais curto deve afetar {{heroHand}}?",
    "reasoning": "Com 25 big blinds, {{heroHand}} segue sendo uma abertura forte, mas um tamanho compacto preserva espaço para responder à ação atrás.",
    "takeaway": "Conforme os stacks encurtam, use tamanhos de abertura eficientes e planeje a resposta a um all-in antes de aumentar.",
    "choices": {
      "raise": {
        "label": "Aumentar para 2.25 big blinds",
        "feedback": "Uma abertura pequena arrisca pouco e prepara as decisões de re-aumento com stack curto."
      },
      "limp": {
        "label": "Pagar 1 big blind",
        "feedback": "Pagar a blind entrega a iniciativa e cria pressão desconfortável atrás."
      },
      "fold": {
        "label": "Desistir",
        "feedback": "{{heroHand}} é uma abertura de valor clara nessa profundidade."
      }
    }
  },
  "math-implied-short-fold": {
    "focus": "Teto das odds implícitas",
    "opponentAction": "Um range forte de posição inicial abre para 3 big blinds. Restam apenas cerca de 12 big blinds após um pagamento.",
    "prompt": "O stack efetivo curto fornece valor futuro suficiente para {{heroHand}}?",
    "reasoning": "{{heroHand}} raramente forma uma trinca no flop, e o stack efetivo não pode pagar o valor adicional necessário para compensar. Stacks curtos limitam as odds implícitas mesmo quando o oponente é forte.",
    "takeaway": "O valor futuro não pode exceder o stack efetivo; as odds implícitas desaparecem rápido conforme os stacks encurtam.",
    "choices": {
      "shove": {
        "label": "Ir all-in",
        "feedback": "{{heroHand}} tem equidade fraca contra o range inicial que pode pagar o all-in."
      },
      "fold": {
        "label": "Desistir",
        "feedback": "O stack restante é pequeno demais para recuperar com a frequência necessária a diferença de equidade direta ({{directRequiredEquityPercent}}%) após formar a trinca; a melhora limpa estimada é de apenas {{estimatedCleanEquityPercent}}%."
      },
      "call": {
        "label": "Pagar 3 big blinds",
        "feedback": "O mesmo pagamento que funciona com stack fundo perde o suporte das odds implícitas quando resta pouco valor futuro a ganhar, cerca de {{minimumFutureWinBb}} big blinds."
      }
    }
  },
  "squeeze-value": {
    "focus": "Squeeze de valor",
    "opponentAction": "O cutoff aumenta para 2.5 big blinds e o botão paga. O big blind ainda está atrás.",
    "prompt": "Qual é a linha de valor mais clara com {{heroHand}}?",
    "reasoning": "{{heroHand}} está muito à frente dos ranges combinados de continuação do abridor e de quem pagou. Re-aumentar constrói valor e desencoraja o big blind de entrar barato.",
    "takeaway": "Quando um aumento é pago, expanda o tamanho de valor para cobrar os dois ranges e reduzir o campo.",
    "choices": {
      "call": {
        "label": "Pagar 2 big blinds",
        "feedback": "Pagar prende, mas convida um pote a quatro jogadores e perde valor dos dois ranges."
      },
      "fold": {
        "label": "Desistir",
        "feedback": "{{heroHand}} está perto do topo do range e não pode desistir aqui."
      },
      "raise": {
        "label": "Aumentar para 12 big blinds",
        "feedback": "Um squeeze maior cobra os dois jogadores e reduz a chance de um pote cheio."
      }
    }
  },
  "math-half-pot-bluff": {
    "focus": "Limiar do blefe de meio pote",
    "opponentAction": "O oponente passa com um range limitado de mãos de um par. Você estima que pelo menos 40% desse range desiste para uma aposta de 10 big blinds.",
    "prompt": "O que a matemática do ponto de equilíbrio sustenta com {{heroHand}}?",
    "reasoning": "Um blefe puro de {{riskBb}} big blinds arrisca {{riskBb}} para ganhar {{rewardBb}}, então precisa de cerca de {{requiredFoldPercent}}% de desistências. A estimativa declarada de 40% supera esse limiar, e {{heroHand}} tem pouco valor de showdown.",
    "takeaway": "As desistências necessárias são o risco dividido pelo risco mais o pote que você pode ganhar.",
    "choices": {
      "all-in": {
        "label": "Ir all-in",
        "feedback": "A situação sustenta o blefe de meio pote medido, não um tamanho extremo sem cálculo."
      },
      "check": {
        "label": "Passar",
        "feedback": "Passar desiste com segurança, mas a estimativa de desistências declarada supera o limiar do blefe puro."
      },
      "bet": {
        "label": "Apostar 10 big blinds",
        "feedback": "Arriscar {{riskBb}} para ganhar {{rewardBb}} precisa de cerca de {{requiredFoldPercent}}% de desistências, abaixo da estimativa sustentada de 40%."
      }
    }
  },
  "read-sticky-bluff-restraint": {
    "focus": "Contenção de blefes contra quem paga",
    "opponentAction": "Ao longo de dezoito mãos, este oponente desistiu apenas duas vezes em nove decisões comparáveis no river e agora passa.",
    "prompt": "{{heroHand}} tem evidência de desistências suficiente para blefar?",
    "reasoning": "{{heroHand}} tem pouco valor de showdown, mas isso sozinho não cria um blefe. A amostra relevante do oponente e os bloqueadores fracos apontam para fold equity insuficiente.",
    "takeaway": "Um draw perdido vira blefe apenas quando mãos melhores podem desistir de forma crível.",
    "choices": {
      "large": {
        "label": "Apostar 18 big blinds",
        "feedback": "Arriscar mais não conserta bloqueadores fracos nem um range de oponente que continua repetidamente."
      },
      "check": {
        "label": "Passar",
        "feedback": "A mão tem bloqueadores fracos, e a amostra de pagamentos estabelecida torna improváveis as desistências necessárias."
      }
    }
  },
  "suited-broadway-call": {
    "focus": "Pagar em posição",
    "opponentAction": "O cutoff aumenta para 2.5 big blinds. As duas blinds seguem atrás de você.",
    "prompt": "Qual é o plano base mais claro com {{heroHand}}?",
    "reasoning": "{{heroHand}} se sai bem contra um range de cutoff e geralmente terá posição. Pagar evita inflar o pote contra continuações mais fortes.",
    "takeaway": "Mãos fortes e jogáveis podem pagar em posição sem transformar toda continuação em um re-aumento.",
    "choices": {
      "raise": {
        "label": "Aumentar para 8 big blinds",
        "feedback": "Um re-aumento pode entrar no mix, mas pagar é a forma mais simples de realizar a equidade desta mão."
      },
      "call": {
        "label": "Pagar 2.5 big blinds",
        "feedback": "Pagar mantém as mãos mais fracas na mão e aproveita sua vantagem posicional."
      },
      "fold": {
        "label": "Desistir",
        "feedback": "{{heroHand}} tem equidade e jogabilidade demais para desistir diante de uma abertura normal de cutoff."
      }
    }
  },
  "middle-pair-open": {
    "focus": "Abertura com par",
    "opponentAction": "Os jogadores antes de você desistem. Três jogadores permanecem atrás.",
    "prompt": "Como você deve entrar com {{heroHand}}?",
    "reasoning": "{{heroHand}} tem força imediata de par e potencial útil de trinca. Uma abertura normal pode ganhar agora ou chegar ao flop com iniciativa.",
    "takeaway": "Pares jogáveis geralmente entram em potes não abertos com o mesmo tamanho de aumento do resto do seu range.",
    "choices": {
      "raise": {
        "label": "Aumentar para 2.5 big blinds",
        "feedback": "Aumente como primeiro a entrar e mantenha formas de ganhar sem formar a trinca."
      },
      "limp": {
        "label": "Pagar 1 big blind",
        "feedback": "Entrar apenas pagando a blind convida pressão e torna seu range de entrada mais fácil de ler."
      },
      "fold": {
        "label": "Desistir",
        "feedback": "Desistir é conservador, mas este par normalmente é forte o suficiente para abrir aqui."
      }
    }
  },
  "isolate-limper": {
    "focus": "Isolamento e posição",
    "opponentAction": "O cutoff dá limp de 1 big blind. O small blind e o big blind ainda esperam atrás de você.",
    "prompt": "Qual é o plano mais claro com {{heroHand}}?",
    "reasoning": "{{heroHand}} está à frente de um range típico de limp. Aumentar com um tamanho que cobra esse range reduz a chance de jogar num pote cheio.",
    "takeaway": "Use a posição e as mãos fortes para isolar limps mais fracos em vez de entrar automaticamente junto.",
    "choices": {
      "fold": {
        "label": "Desistir",
        "feedback": "{{heroHand}} é forte demais para desistir contra um único limp."
      },
      "call": {
        "label": "Pagar 1 big blind",
        "feedback": "Pagar mantém o pote pequeno, mas convida as duas blinds e abre mão de uma ótima oportunidade de isolamento."
      },
      "raise": {
        "label": "Aumentar para 5.5 big blinds",
        "feedback": "Aumentar constrói valor, desencoraja as blinds e busca jogar em posição contra quem deu limp."
      }
    }
  },
  "button-value": {
    "focus": "Valor no pré-flop",
    "opponentAction": "Todos desistem até você no heads-up.",
    "prompt": "Qual é a sua referência mais clara de iniciante?",
    "reasoning": "{{heroHand}} está confortavelmente à frente de uma mão aleatória de big blind. Um aumento padrão gera valor agora sem arriscar uma parte excessiva do stack.",
    "takeaway": "Aumente mãos fortes do botão por valor; a posição ajuda você a realizar essa vantagem.",
    "choices": {
      "limp": {
        "label": "Pagar 0.5 big blinds",
        "feedback": "Algumas estratégias fortes incluem pagar a blind, mas aumentar é a referência mais simples focada em valor."
      },
      "fold": {
        "label": "Desistir",
        "feedback": "{{heroHand}} é forte demais para largar contra uma mão aleatória de big blind."
      },
      "raise": {
        "label": "Aumentar para 3 big blinds",
        "feedback": "Você constrói valor, pressiona mãos mais fracas e mantém a vantagem posicional após o flop."
      }
    }
  },
  "math-implied-set-call": {
    "focus": "Alvo das odds implícitas",
    "opponentAction": "Um range forte de posição inicial abre para 3 big blinds. As blinds são passivas e mais de 60 big blinds permanecem atrás.",
    "prompt": "O valor futuro realista pode sustentar pagar {{callAmountBb}} big blinds com {{heroHand}}?",
    "reasoning": "A chance direta de formar uma trinca no flop está abaixo do preço imediato, mas {{heroHand}} pode plausivelmente ganhar o valor extra necessário de um range forte de overpair com stacks fundos e posição.",
    "takeaway": "As odds implícitas precisam de um pagamento futuro realista, stack suficiente atrás e jogadores gerenciáveis atrás.",
    "choices": {
      "fold": {
        "label": "Desistir",
        "feedback": "Desistir evita variância, mas as condições fundas e em posição podem sustentar uma caça à trinca conservadora."
      },
      "raise": {
        "label": "Aumentar para 10 big blinds",
        "feedback": "{{heroHand}} tem desempenho ruim contra um range de continuação apertado e não precisa virar blefe."
      },
      "call": {
        "label": "Pagar 3 big blinds",
        "feedback": "Posição, stacks efetivos fundos, risco baixo de squeeze e um range forte com probabilidade de pagar após a trinca tornam o alvo implícito plausível."
      }
    }
  },
  "river-thin-value": {
    "focus": "Tamanho de valor fino",
    "opponentAction": "O big blind passa. Várias mãos de um par mais fracas ainda podem pagar uma aposta modesta.",
    "prompt": "Qual tamanho mantém as mãos mais fracas pagando com mais frequência?",
    "reasoning": "Uma aposta de um terço do pote mira os pares mais fracos que você identificou. O objetivo não é o tamanho máximo; é o maior tamanho que mãos mais fracas suficientes podem pagar.",
    "takeaway": "Escolha um tamanho de valor imaginando as mãos mais fracas que realmente vão pagar.",
    "choices": {
      "all-in": {
        "label": "Ir all-in",
        "feedback": "A aposta grande demais faz desistir boa parte do exato range mais fraco que você quer ver pagando."
      },
      "check": {
        "label": "Passar",
        "feedback": "Passar garante o showdown, mas perde um pagamento lucrativo de vários pares mais fracos."
      },
      "small": {
        "label": "Apostar 10 big blinds",
        "feedback": "Um terço do pote dá aos pares mais fracos um preço realista enquanto ainda gera valor."
      }
    }
  },
  "math-reverse-flush": {
    "focus": "Odds inversas implícitas",
    "opponentAction": "Um range apertado de posição inicial aposta 8 big blinds em um pote de 16 em um board com dois naipes. Cartas mais fortes do mesmo naipe continuam prováveis.",
    "prompt": "Todos os nove outs aparentes de flush devem ser tratados como outs limpos para {{heroHand}}?",
    "reasoning": "O preço direto é {{requiredEquityPercent}}%, mas {{heroHand}} não tem nove ganhadores limpos contra um range apertado que contém cartas mais fortes do mesmo naipe. As odds inversas implícitas também tornam os pagamentos posteriores caros depois que o draw completa.",
    "takeaway": "Conte os outs ganhadores limpos, não cada carta que completa o draw em questão.",
    "choices": {
      "call": {
        "label": "Pagar 8 big blinds",
        "feedback": "Contar cada carta de flush como ganhadora limpa ignora os potes grandes perdidos para flushes mais altos."
      },
      "fold": {
        "label": "Desistir",
        "feedback": "Flushes mais altos e ação futura difícil reduzem a equidade limpa abaixo da estimativa básica de nove outs."
      },
      "raise": {
        "label": "Aumentar para 28 big blinds",
        "feedback": "O draw baixo tem potencial de nut fraco contra o range apertado e é um semi-blefe frágil."
      }
    }
  },
  "early-discipline": {
    "focus": "Disciplina na posição inicial",
    "opponentAction": "Você é o primeiro a agir. Cinco jogadores ainda têm cartas vivas atrás de você.",
    "prompt": "Qual é a referência mais clara com {{heroHand}}?",
    "reasoning": "A posição muda o limiar. {{heroHand}} precisa passar por cinco jogadores e depois jogar muitos flops fora de posição, então desistir preserva fichas para oportunidades mais fortes.",
    "takeaway": "Abra mais apertado da posição inicial porque mais jogadores podem acordar com uma mão forte.",
    "choices": {
      "raise": {
        "label": "Aumentar para 2.5 big blinds",
        "feedback": "Esta mão é fraca demais para um range de abertura simples de posição inicial em uma mesa de seis jogadores."
      },
      "limp": {
        "label": "Pagar 1 big blind",
        "feedback": "Entrar apenas pagando a blind convida um pote cheio com uma mão fraca e nenhuma vantagem posicional."
      },
      "fold": {
        "label": "Desistir",
        "feedback": "{{heroHand}} não tem força de carta alta nem jogabilidade, enquanto cinco ranges ainda podem aplicar pressão."
      }
    }
  },
  "math-semibluff-equity": {
    "focus": "Colchão de equidade do semi-blefe",
    "opponentAction": "O oponente passa com um range contendo mãos de um par. Uma aposta de 14 big blinds recebe algumas desistências, e o draw mantém equidade limpa no river quando pago.",
    "prompt": "Qual linha usa os dois caminhos de vitória com {{heroHand}}?",
    "reasoning": "Diferente de um blefe puro, {{heroHand}} não perde toda vez que é pago. Sua equidade limpa de draw reduz a exigência imediata de desistências, enquanto o tamanho medido ainda mira mãos de um par melhores.",
    "takeaway": "Semi-blefes precisam de menos desistências que blefes puros apenas quando a equidade deles quando pagos é limpa e realizável.",
    "choices": {
      "check": {
        "label": "Passar",
        "feedback": "Passar realiza a equidade do draw, mas abre mão de desistências imediatas contra mãos que lideram agora."
      },
      "all-in": {
        "label": "Ir all-in",
        "feedback": "O draw não precisa de um overbet extremo para combinar equidade e pressão de desistência."
      },
      "bet": {
        "label": "Apostar 14 big blinds",
        "feedback": "O semi-blefe controlado pode ganhar agora e mantém equidade limpa de melhora quando pago."
      }
    }
  },
  "overlimp-small-pair": {
    "focus": "Over-limp seletivo",
    "opponentAction": "Dois jogadores dão limp. Os stacks são fundos e as blinds raramente aumentam.",
    "prompt": "Qual entrada de baixa variância faz sentido com {{heroHand}}?",
    "reasoning": "{{heroHand}} com frequência precisa formar uma trinca para ganhar um pote grande. As condições fundas e passivas e a posição no botão tornam um pagamento de 1 big blind razoável.",
    "takeaway": "Pague atrás de forma seletiva quando a mão, a profundidade de stack, a posição e o comportamento da mesa favorecerem um pote multiway.",
    "choices": {
      "call": {
        "label": "Pagar 1 big blind",
        "feedback": "Stacks fundos, posição e um risco baixo de squeeze sustentam caçar a trinca barato."
      },
      "fold": {
        "label": "Desistir",
        "feedback": "Desistir é aceitável se a mesa for agressiva, mas as condições descritas sustentam um pagamento barato."
      },
      "raise": {
        "label": "Aumentar para 6 big blinds",
        "feedback": "Isolar pode funcionar, mas o par pequeno sofre com vários pagadores e pressão pós-flop."
      }
    }
  },
  "marginal-four-bet-fold": {
    "focus": "Enfrentando um 4-bet",
    "opponentAction": "Você deu 3-bet numa abertura inicial para 10 big blinds. O abridor dá 4-bet para 24 big blinds.",
    "prompt": "Qual é o plano base disciplinado com {{heroHand}}?",
    "reasoning": "A ação e as posições tornam o range de 4-bet muito forte. As fichas já investidas não justificam continuar com {{heroHand}} diante de uma equidade ruim.",
    "takeaway": "Planeje antes do 3-bet e solte as mãos marginais quando a ação posterior representar um range muito mais forte.",
    "choices": {
      "fold": {
        "label": "Desistir",
        "feedback": "Contra um range forte de 4-bet de posição inicial, esta mão não tem uma continuação robusta."
      },
      "all-in": {
        "label": "Ir all-in",
        "feedback": "Um shove normalmente é pago por mãos com equidade substancialmente melhor."
      },
      "call": {
        "label": "Pagar 14 big blinds",
        "feedback": "Pagar cria um pote grande fora de posição contra um range que domina você com muita frequência."
      }
    }
  },
  "multi-limper-isolate": {
    "focus": "Vários limpers",
    "opponentAction": "Dois jogadores dão limp pagando 1 big blind cada. As duas blinds seguem atrás de você.",
    "prompt": "Qual é o plano mais claro com {{heroHand}}?",
    "reasoning": "Dois limpers criam mais dinheiro morto e mais possíveis pagadores. {{heroHand}} deve usar um aumento de isolamento maior por valor.",
    "takeaway": "Adicione cerca de 1 big blind por limper ao isolar e depois ajuste pela posição e pelo comportamento do oponente.",
    "choices": {
      "call": {
        "label": "Pagar 1 big blind",
        "feedback": "Pagar convida as duas blinds e perde uma grande oportunidade de valor."
      },
      "fold": {
        "label": "Desistir",
        "feedback": "{{heroHand}} está muito à frente dos ranges típicos de limp."
      },
      "raise": {
        "label": "Aumentar para 6 big blinds",
        "feedback": "Adicione tamanho pelos dois limpers e tente estreitar o campo com uma mão premium."
      }
    }
  },
  "suited-connector-defense": {
    "focus": "Defesa de blinds jogáveis",
    "opponentAction": "O botão aumenta para 2.25 big blinds. O small blind desiste; você tem 1 big blind pago.",
    "prompt": "De que forma o preço e a jogabilidade devem influenciar a decisão com {{heroHand}}?",
    "reasoning": "{{heroHand}} recebe um preço favorável e pode formar sequências e flushes escondidos. Essas características ajudam a mão a realizar equidade apesar de agir primeiro após o flop.",
    "takeaway": "Contra aberturas pequenas de posição tardia, defenda mãos do mesmo naipe jogáveis mais amplamente do que mãos desconectadas de naipes diferentes.",
    "choices": {
      "raise": {
        "label": "Aumentar para 9 big blinds",
        "feedback": "Um re-aumento pode entrar em misturas, mas pagar é a forma mais simples de realizar a equidade jogável da mão."
      },
      "fold": {
        "label": "Desistir",
        "feedback": "Desistir evita uma posição difícil, mas é apertado demais para este preço pequeno contra um range amplo."
      },
      "call": {
        "label": "Pagar 1.25 big blinds",
        "feedback": "O desconto e a conectividade do mesmo naipe tornam este um pagamento prático no big blind."
      }
    }
  },
  "river-bluff-catch-fold": {
    "focus": "Largar o bluff-catcher para um overbet",
    "opponentAction": "Um big blind com range carregado de valor faz overbet de 30 big blinds em um pote de 24 em um river sem conexões.",
    "prompt": "Se {{heroHand}} com par superior vence apenas cerca de {{estimatedEquityPercent}}% das vezes, o que o novo preço exige?",
    "reasoning": "Pagar 30 para ganhar um pote final de 84 exige cerca de 36% de equidade. Uma taxa de vitória estimada de 20% fica muito aquém, então o mesmo bluff-catcher de par superior deve ser largado nesse preço maior.",
    "takeaway": "A mão pode continuar a mesma enquanto o tamanho da aposta transforma um pagamento em uma desistência.",
    "choices": {
      "raise": {
        "label": "Aumentar all-in",
        "feedback": "Um re-aumento de blefe arrisca o stack restante contra um range polarizado que já é carregado de valor demais."
      },
      "call": {
        "label": "Pagar 30 big blinds",
        "feedback": "O pagamento precisa de cerca de {{requiredEquityPercent}}% de equidade, muito acima da taxa de vitória estimada de apenas {{estimatedEquityPercent}}% para essa linha carregada de valor."
      },
      "fold": {
        "label": "Desistir",
        "feedback": "A desistência disciplinada evita pagar um limiar de {{requiredEquityPercent}}% com uma taxa de vitória estimada perto de {{estimatedEquityPercent}}%."
      }
    }
  },
  "out-of-position-three-bet-size": {
    "focus": "Tamanho de 3-bet fora de posição",
    "opponentAction": "O cutoff aumenta para 2.5 big blinds. Você estará fora de posição se for pago.",
    "prompt": "Qual tamanho melhor sustenta o plano de valor com {{heroHand}}?",
    "reasoning": "Fora de posição, {{heroHand}} se beneficia de um 3-bet maior. 11 big blinds criam valor e reduzem a capacidade do abridor de pagar barato com um range amplo.",
    "takeaway": "Use um 3-bet maior fora de posição do que em posição contra o mesmo tamanho de abertura.",
    "choices": {
      "raise": {
        "label": "Aumentar para 11 big blinds",
        "feedback": "O tamanho maior fora de posição constrói valor e cobra do abridor a vantagem posicional."
      },
      "call": {
        "label": "Pagar 2 big blinds",
        "feedback": "Pagar é jogável, mas convida o big blind e perde um re-aumento de valor claro."
      },
      "small-raise": {
        "label": "Aumentar para 6 big blinds",
        "feedback": "Esse tamanho pequeno dá ao abridor e ao big blind um preço atrativo para realizar equidade."
      }
    }
  },
  "blocker-three-bet-plan": {
    "focus": "3-bet com bloqueador",
    "opponentAction": "Um botão ativo aumenta para 2.5 big blinds e a small blind desiste.",
    "prompt": "Qual plano agressivo tem a melhor estrutura com {{heroHand}}?",
    "reasoning": "{{heroHand}} remove combinações de ases, ás-rei e ás-dama e mantém potencial de sequência e flush. Essas propriedades a tornam um 3-bet de blefe deliberado e ocasional.",
    "takeaway": "Escolha mãos de pressão por bloqueadores e jogabilidade, não simplesmente porque são fracas demais para pagar.",
    "choices": {
      "fold": {
        "label": "Desistir",
        "feedback": "Desistir é aceitável, mas abre mão do bloqueador de ás e do potencial de wheel do mesmo naipe."
      },
      "call": {
        "label": "Pagar 1.5 big blinds",
        "feedback": "Pagar usa o preço, embora não aplique pressão imediata à abertura ampla."
      },
      "raise": {
        "label": "Aumentar para 9 big blinds",
        "feedback": "O ás bloqueia as continuações premium e a carta baixa do mesmo naipe mantém várias formas de melhorar."
      }
    }
  },
  "read-patient-raise": {
    "focus": "Respeitar a agressividade rara",
    "opponentAction": "Depois de 17 mãos tranquilas com apenas um aumento anterior, o oponente dá check-raise all-in na sua aposta de 16 big blinds no river. Poucos draws naturais erraram.",
    "prompt": "De que forma a leitura estabelecida de agressividade rara deve influenciar sua decisão com {{heroHand}}?",
    "reasoning": "{{heroHand}} é forte em termos absolutos, mas a evidência relevante é um aumento grande no river vindo de um range consistentemente passivo com poucos blefes críveis. O ajuste adequado é uma desistência disciplinada.",
    "takeaway": "Contra paciência estabelecida, dê mais crédito à agressividade grande e rara quando a linha não tem blefes.",
    "choices": {
      "fold": {
        "label": "Desistir",
        "feedback": "O aumento grande e raro no river e a ausência de draws errados deixam o range de valor concentrado demais para este bluff catcher."
      },
      "call": {
        "label": "Pagar all-in",
        "feedback": "O valor absoluto forte não fornece blefes suficientes para uma linha que esse oponente quase nunca tomou."
      }
    }
  },
  "tournament-reshove-discipline": {
    "focus": "Disciplina de range no reshove",
    "opponentAction": "Um jogador disciplinado em UTG abre para 2.5 big blinds e todos os outros jogadores desistem.",
    "prompt": "Como a posição de abertura apertada deve afetar {{heroHand}}?",
    "reasoning": "O mesmo stack que sustenta um reshove contra uma abertura ampla do botão não justifica um contra um range inicial apertado. {{heroHand}} não tem equidade suficiente quando pago e recebe desistências imediatas insuficientes.",
    "takeaway": "Um reshove é uma interação de ranges, não um reflexo de tamanho de stack.",
    "choices": {
      "call": {
        "label": "Pagar 1.5 big blinds",
        "feedback": "Pagar consome uma parcela relevante do stack e deixa uma mão dominada fora de posição com pouco espaço pós-flop."
      },
      "fold": {
        "label": "Desistir",
        "feedback": "O range de abertura inicial e as continuações prováveis de all-in dominam boa parte demais da equidade desta mão."
      },
      "shove": {
        "label": "Aumentar all-in",
        "feedback": "O abridor apertado desiste com menos frequência e paga com um range que se sai muito bem contra {{heroHand}}."
      }
    }
  },
  "river-thin-value-target": {
    "focus": "Valor fino no river",
    "opponentAction": "O big blind pagou apostas modestas no flop e no turn, e depois dá check num river neutro.",
    "prompt": "Qual tamanho mantém mãos de um par mais fracas pagando contra {{heroHand}}?",
    "reasoning": "{{heroHand}} segue à frente de vários bluff catchers naturais num river neutro. Uma aposta de valor pequena tem o tamanho pensado para esses pagamentos piores, em vez de isolar contra o topo do range.",
    "takeaway": "O valor fino funciona ao dar às mãos mais fracas um preço que elas conseguem pagar de forma realista.",
    "choices": {
      "small": {
        "label": "Apostar 10 big blinds",
        "feedback": "O tamanho convidativo mira as mãos de um par mais fracas sem exigir que o range seja forte demais."
      },
      "check": {
        "label": "Passar",
        "feedback": "Passar garante o showdown, mas perde valor de pares superiores piores e de pares inferiores teimosos."
      },
      "overbet": {
        "label": "Apostar 48 big blinds",
        "feedback": "O overbet desiste muitas mãos que você vence e é mais provável de ser pago por um range mais forte."
      }
    }
  },
  "overpriced-flush": {
    "focus": "Draws com preço alto demais",
    "opponentAction": "O big blind aposta {{callAmountBb}} big blinds em um pote de {{callAmountBb}} big blinds. Nove outs de flush são cerca de {{estimatedEquityPercent}}% com uma carta por vir.",
    "prompt": "O que o preço diz sobre continuar?",
    "reasoning": "Pagar {{callAmountBb}} big blinds cria um pote final de {{finalPotBb}} big blinds, então o preço de equilíbrio é {{requiredEquityPercent}}%. A chance declarada de {{estimatedEquityPercent}}% de completar o draw não é suficiente.",
    "takeaway": "Draws de aparência forte ainda podem ser desistências quando uma aposta grande oferece o preço errado.",
    "choices": {
      "fold": {
        "label": "Desistir",
        "feedback": "O pagamento precisa de {{requiredEquityPercent}}% de equidade, bem acima da chance declarada de {{estimatedEquityPercent}}% de completar o flush."
      },
      "call": {
        "label": "Pagar 16 big blinds",
        "feedback": "Um draw de aparência forte continua sendo um pagamento perdedor quando sua equidade está abaixo do preço direto."
      },
      "raise": {
        "label": "Aumentar all-in",
        "feedback": "Um re-aumento de blefe precisa de fold equity crível; o draw sozinho não apaga o preço ruim."
      }
    }
  },
  "tournament-calloff-fold": {
    "focus": "Disciplina no call all-in",
    "opponentAction": "Um jogador disciplinado em UTG vai all-in e todos os outros jogadores desistem.",
    "prompt": "O big blind já pago torna {{heroHand}} um call lucrativo?",
    "reasoning": "O all-in veio da posição mais inicial, então o range de shove deve ser muito mais forte que um range de botão. {{heroHand}} é frequentemente dominada, e o preço um pouco melhor não conserta essa diferença de equidade.",
    "takeaway": "Um call all-in precisa de equidade direta; fichas já apostas não justificam pagar um range que domina você.",
    "choices": {
      "fold": {
        "label": "Desistir",
        "feedback": "O range de shove inicial domina combinações demais, e a blind já paga não fornece equidade suficiente."
      },
      "call": {
        "label": "Pagar all-in",
        "feedback": "Pagar não tem fold equity e coloca o stack restante contra um range muito mais forte que esta mão."
      }
    }
  },
  "bubble-short-stack-action": {
    "focus": "Iniciativa com o stack mais curto",
    "opponentAction": "Duas vagas avançam. Você tem o stack mais curto, a ação desiste até você e as duas blinds podem te eliminar.",
    "prompt": "O medo da bolha deve impedir a oportunidade de all-in em primeiro lugar com {{heroHand}}?",
    "reasoning": "Como você tem o stack mais curto, tem menos valor de sobrevivência a proteger e não pode contar com outro jogador quebrando antes. {{heroHand}} é forte o bastante para usar agora o fold equity de posição tardia.",
    "takeaway": "A pressão da bolha pode apertar os calls enquanto mantém intactos os bons shoves de primeiro a agir com stack curto.",
    "choices": {
      "shove": {
        "label": "Ir all-in",
        "feedback": "{{heroHand}} combina equidade útil com a chance de vencer as blinds imediatamente agindo primeiro."
      },
      "fold": {
        "label": "Desistir",
        "feedback": "Esperar dá às blinds uma fatia maior do stack restante e remove o fold equity de primeiro a agir desta mão."
      }
    }
  },
  "river-bluff-catch": {
    "focus": "Bluff catch",
    "opponentAction": "O big blind aposta {{callAmountBb}} big blinds no river. Você estima que este bluff catcher vence {{estimatedEquityPercent}}% das vezes.",
    "prompt": "O que o preço diz para você fazer?",
    "reasoning": "Pagar {{callAmountBb}} big blinds deixa o pote final em {{finalPotBb}} big blinds. A equidade necessária é {{callAmountBb}} ÷ {{finalPotBb}} ≈ {{requiredEquityPercent}}%, acima da estimativa declarada de {{estimatedEquityPercent}}% de vitória.",
    "takeaway": "Não deixe a força absoluta da mão sobrepor o preço e a sua estimativa baseada no range.",
    "choices": {
      "raise": {
        "label": "Aumentar all-in",
        "feedback": "Transformar valor de showdown em blefe exige evidências de blocker e de desistências que você não tem."
      },
      "call": {
        "label": "Pagar 20 big blinds",
        "feedback": "O par superior parece atraente, mas o call perde quando sua estimativa de equidade está abaixo do preço."
      },
      "fold": {
        "label": "Desistir",
        "feedback": "Você precisa de cerca de {{requiredEquityPercent}}% de equidade, então uma estimativa confiável de {{estimatedEquityPercent}}% não sustenta um call."
      }
    }
  },
  "bubble-medium-stack-calloff": {
    "focus": "Disciplina no call com stack coberto",
    "opponentAction": "Duas vagas avançam. O líder em fichas com 42 big blinds vai all-in do botão, você é o segundo em fichas e resta um stack de 6 big blinds.",
    "prompt": "Como o risco da bolha deve mudar o call marginal com {{heroHand}}?",
    "reasoning": "O líder te cobre e o stack mais curto está sob pressão imediata das blinds. {{heroHand}} não está à frente do range de shove o bastante para justificar arriscar a eliminação por um ganho marginal de fichas.",
    "takeaway": "Stacks médios cobertos devem apertar calls all-in disputados enquanto existir um stack muito mais curto.",
    "choices": {
      "fold": {
        "label": "Desistir",
        "feedback": "Preservar o segundo stack enquanto resta um jogador com 6 big blinds pesa mais do que um call apertado de equidade em fichas."
      },
      "call": {
        "label": "Pagar all-in",
        "feedback": "{{heroHand}} pode estar próximo em termos de fichas, mas pagar não tem fold equity e perder encerra o evento antes do stack mais curto."
      }
    }
  },
  "pot-control": {
    "focus": "Valor de showdown",
    "opponentAction": "O big blind paga no flop e depois dá check no turn.",
    "prompt": "Como você deve jogar o segundo par com kicker forte?",
    "reasoning": "O segundo par tem valor de showdown útil, mas não ganha claramente com uma aposta grande. A posição permite pegar uma carta grátis e tomar a decisão no river com mais informação.",
    "takeaway": "Um bom check pode proteger valor de showdown de força média; agressividade sempre precisa de um propósito.",
    "choices": {
      "check": {
        "label": "Passar",
        "feedback": "Passar realiza seu valor de showdown e evita construir um pote grande contra pares mais fortes."
      },
      "large": {
        "label": "Apostar 12 big blinds",
        "feedback": "Uma aposta do tamanho do pote isola esta mão de força média contra boa parte demais do range mais forte."
      },
      "small": {
        "label": "Apostar 4 big blinds",
        "feedback": "Uma aposta pequena de proteção pode entrar no mix, mas muitas mãos piores desistem enquanto as mãos mais fortes continuam."
      }
    }
  },
  "tournament-early-shove-fold": {
    "focus": "Disciplina de shove em posição inicial",
    "opponentAction": "Você age primeiro com cinco ranges vivos ainda atrás.",
    "prompt": "O stack curto torna {{heroHand}} um all-in automático?",
    "reasoning": "A urgência de stack curto não apaga a posição. {{heroHand}} precisa passar por cinco ranges e se sai mal quando pago, então preservar o stack restante é melhor do que forçar um all-in inicial.",
    "takeaway": "Mantenha um range de desistência em posição inicial mesmo com o stack curto.",
    "choices": {
      "fold": {
        "label": "Desistir",
        "feedback": "A mão é dominada ou paga por ranges mais fortes com frequência demais depois de passar por cinco jogadores."
      },
      "limp": {
        "label": "Pagar 1 big blind",
        "feedback": "O limp de abertura gasta fichas escassas sem criar pressão de desistência nem uma resposta clara a um aumento."
      },
      "shove": {
        "label": "Ir all-in",
        "feedback": "Cinco jogadores podem acordar com mãos mais fortes, tornando este shove amplo demais para um plano base prático."
      }
    }
  },
  "tournament-value-reshove": {
    "focus": "Reshove de valor",
    "opponentAction": "Um abridor amplo no botão aumenta para 2.2 big blinds e o small blind desiste.",
    "prompt": "Qual resposta extrai o valor mais claro de {{heroHand}}?",
    "reasoning": "{{heroHand}} se sai muito bem tanto contra uma abertura ampla de botão quanto contra um range de pagamento razoável. Com menos de 20 big blinds, o reshove direto evita um 3-bet pequeno desconfortável e captura o dinheiro morto.",
    "takeaway": "Mãos fortes podem dar reshove de valor contra aberturas amplas de posição tardia quando o stack já está compacto.",
    "choices": {
      "call": {
        "label": "Pagar 1.2 big blinds",
        "feedback": "Pagar mantém o range amplo, mas abre mão de valor imediato e deixa o abridor realizar equidade."
      },
      "fold": {
        "label": "Desistir",
        "feedback": "{{heroHand}} está muito à frente de um range amplo de abertura de botão e é forte demais para soltar."
      },
      "shove": {
        "label": "Aumentar all-in",
        "feedback": "O reshove vence o dinheiro morto agora ou entra no all-in com equidade forte contra o range de continuação do botão."
      }
    }
  },
  "set-mine-price": {
    "focus": "Condições para caçar a trinca",
    "opponentAction": "A posição inicial aumenta para 2.5 big blinds. Você tem 100 big blinds de profundidade e as blinds são passivas.",
    "prompt": "Qual resposta melhor aproveita {{heroHand}}?",
    "reasoning": "{{heroHand}} acerta a trinca no flop com pouca frequência, então precisa de stacks fundos, um preço administrável e uma boa chance de realizar seu valor implícito.",
    "takeaway": "Só cace a trinca quando o preço, a profundidade de stack, a posição e os jogadores atrás sustentarem o retorno futuro.",
    "choices": {
      "fold": {
        "label": "Desistir",
        "feedback": "Desistir evita variância, mas os stacks fundos e a posição tornam o pagamento viável."
      },
      "raise": {
        "label": "Aumentar para 8 big blinds",
        "feedback": "Um re-aumento pode entrar no mix, mas geralmente desiste as mãos piores e enfrenta continuações fortes."
      },
      "call": {
        "label": "Pagar 2.5 big blinds",
        "feedback": "Stacks fundos e posição oferecem potencial suficiente quando você acerta a trinca no flop."
      }
    }
  },
  "cutoff-open": {
    "focus": "Abertura no cutoff",
    "opponentAction": "A ação desiste até você. O botão e as duas blinds seguem na mão.",
    "prompt": "Qual é a ação mais limpa ao ser o primeiro a entrar com {{heroHand}}?",
    "reasoning": "{{heroHand}} combina qualidade de cartas e posição suficientes para abrir com lucro no cutoff. Um tamanho consistente de 2.5 big blinds mantém a estratégia clara.",
    "takeaway": "Abra mais mãos conforme restam menos jogadores, mas entre com um aumento em vez de um limp.",
    "choices": {
      "fold": {
        "label": "Desistir",
        "feedback": "{{heroHand}} é forte o suficiente para entrar pelo cutoff depois que os jogadores anteriores desistirem."
      },
      "limp": {
        "label": "Pagar 1 big blind",
        "feedback": "Abrir com limp entrega a pressão imediata e convida a um pote cheio."
      },
      "raise": {
        "label": "Aumentar para 2.5 big blinds",
        "feedback": "Um aumento pequeno e consistente constrói valor e pode ganhar as blinds."
      }
    }
  },
  "bubble-ladder-discipline": {
    "focus": "Disciplina sob pressão de ladder",
    "opponentAction": "Duas vagas avançam. O botão com 4 big blinds desistiu, e o líder com 45 big blinds espera no big blind.",
    "prompt": "Qual é o plano base mais limpo com {{heroHand}}, uma mão marginal?",
    "reasoning": "{{heroHand}} fica perto do limite normal de abertura, mas esta configuração específica de stacks adiciona um custo de sobrevivência relevante. O líder te cobre e o jogador com 4 big blinds pode ser forçado ao all-in em breve.",
    "takeaway": "Nomeie o stack mais curto e o stack que cobre antes de tomar uma desistência apertada de bolha.",
    "choices": {
      "shove": {
        "label": "Ir all-in",
        "feedback": "Arriscar todo o stack médio por cima do líder é desnecessário enquanto o stack mais curto está quase todo consumido pelas blinds."
      },
      "fold": {
        "label": "Desistir",
        "feedback": "A mão é marginal, o líder pode aplicar pressão máxima e resta um stack de 4 big blinds."
      },
      "raise": {
        "label": "Aumentar para 2.2 big blinds",
        "feedback": "A abertura convida a um re-shove do líder que cobre você, num spot em que seu range não consegue defender com conforto."
      }
    }
  },
  "river-blocker-bluff": {
    "focus": "Blefe no river liderado por bloqueador",
    "opponentAction": "O big blind pagou o flop, os dois jogadores passaram o turn, e o big blind passa quando a terceira carta do flush chega.",
    "prompt": "Qual tamanho de blefe melhor usa o bloqueador do naipe do nut flush carregado por {{heroHand}}?",
    "reasoning": "{{heroHand}} com o bloqueador do naipe do nut flush tem pouco valor de showdown, bloqueia o nut flush e não bloqueia muitas desistências de mãos de um par. Essas propriedades tornam essa mão um blefe grande mais crível do que uma mão perdida aleatória.",
    "takeaway": "Escolha blefes no river que bloqueiem pagamentos e deixem desistências prováveis no range do oponente.",
    "choices": {
      "large": {
        "label": "Apostar 36 big blinds",
        "feedback": "O tamanho polarizado pressiona as mãos de um par, enquanto o bloqueador do naipe do nut flush remove pagamentos fortes importantes."
      },
      "check": {
        "label": "Passar",
        "feedback": "Desistir é aceitável, mas não usa o bloqueador do naipe do nut flush contra um range de passagem limitado."
      },
      "small": {
        "label": "Apostar 8 big blinds",
        "feedback": "Uma aposta pequena dá a muitos pares e flushes baixos um preço fácil de bluff-catcher."
      }
    }
  },
  "no-equity-turn-give-up": {
    "focus": "Desistência no turn sem equidade",
    "opponentAction": "O big blind pagou sua aposta no flop e dá check depois de um turn que melhora as mãos conectadas de pagamento.",
    "prompt": "{{heroHand}} ainda tem equidade e pressão de desistência suficientes para apostar de novo?",
    "reasoning": "{{heroHand}} tem pouca equidade realista de melhora e o turn fortalece muitos pagamentos do flop. Sem blockers úteis ou desistências críveis, um segundo blefe gasta fichas sem um caminho forte para vencer.",
    "takeaway": "Desista quando o turn remove tanto a equidade de melhora quanto um fold equity crível.",
    "choices": {
      "check": {
        "label": "Passar",
        "feedback": "Passar desiste de forma limpa quando a mão tem pouca equidade de melhora e o range de quem pagou se fortalece."
      },
      "medium": {
        "label": "Apostar 9 big blinds",
        "feedback": "O flop pago e o turn que conecta deixam muito poucas mãos melhores propensas a desistir diante de mais uma aposta rotineira."
      },
      "overbet": {
        "label": "Apostar 27 big blinds",
        "feedback": "Aumentar o tamanho não conserta a equidade ruim, os blockers fracos e um turn que favorece quem pagou."
      }
    }
  },
  "tournament-call-short-shove": {
    "focus": "Pagar um shove de posição tardia",
    "opponentAction": "O botão curto vai all-in depois que o small blind desiste. Você já pagou o big blind.",
    "prompt": "O que um shove amplo de posição tardia sustenta com {{heroHand}}?",
    "reasoning": "O botão pode dar shove amplo com apenas dois oponentes e um stack muito curto. {{heroHand}} continua forte contra esse range, e o big blind já no pote melhora o preço do call.",
    "takeaway": "Pague shoves curtos de posição tardia com mais amplitude usando mãos que retêm equidade clara contra o range completo de shove.",
    "choices": {
      "fold": {
        "label": "Desistir",
        "feedback": "{{heroHand}} é forte demais contra um range amplo de shove de posição tardia para entregar a blind paga e o pote."
      },
      "call": {
        "label": "Pagar all-in",
        "feedback": "A mão tem equidade forte contra o range amplo de stack curto do botão e recebe um preço melhorado pela blind já paga."
      }
    }
  },
  "river-raise-discipline": {
    "focus": "Disciplina no aumento no river",
    "opponentAction": "O big blind aposta 8 big blinds num pote de 24 num river com três cartas do mesmo naipe. O nut flush continua possível.",
    "prompt": "Como {{heroHand}} com o flush já formado deve continuar sem tirar os blefes que ele vence?",
    "reasoning": "{{heroHand}} com o flush feito é forte o bastante para continuar, mas aumentar tem alvo de valor ruim: as mãos piores geralmente desistem e os flushes melhores continuam. Pagar preserva os blefes do oponente e controla o pote final.",
    "takeaway": "Antes de aumentar no river, nomeie as mãos piores que podem realmente pagar o aumento.",
    "choices": {
      "fold": {
        "label": "Desistir",
        "feedback": "Desistir é cauteloso, mas abre mão de demais contra uma aposta pequena que contém valor mais fraco e blefes."
      },
      "call": {
        "label": "Pagar 8 big blinds",
        "feedback": "Pagar mantém blefes e flushes mais fracos na mão enquanto limita as perdas à parte do range rica em nuts."
      },
      "raise": {
        "label": "Aumentar para 28 big blinds",
        "feedback": "Aumentar desiste muitas mãos piores e é mais provável de receber ação dos flushes mais altos."
      }
    }
  },
  "facing-three-bet-dominated-fold": {
    "focus": "Desistir de mãos dominadas diante de um 3-bet",
    "opponentAction": "Você abriu para 2.5 big blinds. O small blind dá 3-bet para 11 big blinds e o big blind desiste.",
    "prompt": "Como você deve responder com {{heroHand}}?",
    "reasoning": "{{heroHand}}, com cartas de naipes diferentes, é frequentemente dominada e enfrenta um re-aumento grande fora de posição. Os 2.5 big blinds já investidos não tornam correta uma continuação não lucrativa.",
    "takeaway": "Trate a abertura como custo afundado; continue apenas quando a mão sobreviver ao novo range e ao novo preço.",
    "choices": {
      "all-in": {
        "label": "Ir all-in",
        "feedback": "Um shove normalmente é pago por um range com equidade substancialmente melhor."
      },
      "fold": {
        "label": "Desistir",
        "feedback": "Solte a mão dominada de naipes diferentes em vez de defender o investimento da abertura anterior."
      },
      "call": {
        "label": "Pagar 8.5 big blinds",
        "feedback": "Esta mão forma pares segundos demais contra o range mais forte de 3-bet."
      }
    }
  },
  "small-blind-steal": {
    "focus": "Abertura na small blind",
    "opponentAction": "Todos desistem até você. Você já pagou 0.5 big blinds.",
    "prompt": "Qual é o plano mais simples priorizando valor com {{heroHand}}?",
    "reasoning": "{{heroHand}} está à frente de uma mão aleatória de big blind. Aumentar constrói valor mesmo que você aja primeiro após o flop.",
    "takeaway": "Quando todos desistem até a small blind, ataque com mãos sólidas respeitando a desvantagem posicional pós-flop.",
    "choices": {
      "call": {
        "label": "Pagar 0.5 big blinds",
        "feedback": "Algumas estratégias dão limp, mas aumentar é a base mais clara para iniciantes com esta mão."
      },
      "raise": {
        "label": "Aumentar para 3 big blinds",
        "feedback": "Aumente por valor e faça o big blind pagar para continuar em posição."
      },
      "fold": {
        "label": "Desistir",
        "feedback": "{{heroHand}} é forte demais para ser entregue contra um range aleatório de big blind."
      }
    }
  },
  "short-stack-three-bet-plan": {
    "focus": "Compromisso de 3-bet com stack curto",
    "opponentAction": "O botão aumenta para 2.5 big blinds e o small blind desiste. Os stacks efetivos são 30 big blinds.",
    "prompt": "Qual plano aproveita melhor o stack mais curto com {{heroHand}}?",
    "reasoning": "Com 30 big blinds, {{heroHand}} tem equidade forte tanto contra a abertura do botão quanto contra um range de continuação razoável. Um 3-bet compacto cria um SPR baixo e um plano de compromisso claro.",
    "takeaway": "Conforme os stacks encurtam, decida se o 3-bet de valor continuará contra um all-in antes de aumentar.",
    "choices": {
      "raise": {
        "label": "Aumentar para 8.5 big blinds",
        "feedback": "O tamanho eficiente constrói valor e prepara a continuação contra um shove nesta profundidade de stack."
      },
      "call": {
        "label": "Pagar 1.5 big blinds",
        "feedback": "Pagar é jogável, mas perde valor e deixa o botão realizar equidade barato."
      },
      "fold": {
        "label": "Desistir",
        "feedback": "{{heroHand}} é forte demais para desistir contra um range amplo de abertura de botão."
      }
    }
  },
  "three-bet-pot-connected-check": {
    "focus": "Contenção em pote de 3-bet com board conectado",
    "opponentAction": "Você deu 3-bet pré-flop, o cutoff pagou e agora dá check neste flop conectado.",
    "prompt": "Como a interação com o board deve mudar o plano com {{heroHand}}?",
    "reasoning": "O range condensado de quem pagou conecta fortemente com este flop baixo e coordenado. {{heroHand}} retém equidade futura, mas não tem a vantagem de nuts exigida para uma aposta de continuação grande e automática.",
    "takeaway": "Dar 3-bet pré-flop não garante controle de range pós-flop em boards conectados.",
    "choices": {
      "small": {
        "label": "Apostar 7 big blinds",
        "feedback": "Uma aposta pequena pode entrar no mix com blockers melhores, mas esta mão não precisa forçar pressão imediata."
      },
      "check": {
        "label": "Passar",
        "feedback": "Passar preserva a equidade de overcards e evita inflar o pote num board rico em pagamentos e aumentos fortes."
      },
      "large": {
        "label": "Apostar 21 big blinds",
        "feedback": "Quem pagou tem muitos pares, dois pares, trincas e draws que podem continuar ou aumentar contra uma aposta grande."
      }
    }
  },
  "river-bluff-catch-call": {
    "focus": "Bluff-catcher a um preço justo",
    "opponentAction": "O big blind aposta 8 big blinds em um pote de 24 em um river sem conexões depois que vários draws naturais perdem.",
    "prompt": "Se {{heroHand}} com par superior vence cerca de {{estimatedEquityPercent}}% das vezes, o que o preço sustenta?",
    "reasoning": "Pagar 8 para ganhar um pote final de 40 exige 20% de equidade. A taxa de vitória estimada de 28% supera esse limiar, então pagar é a referência consciente de preço sem exagerar o valor da mão.",
    "takeaway": "Apostas pequenas no river podem justificar bluff-catchers quando restam draws perdidos suficientes.",
    "choices": {
      "call": {
        "label": "Pagar 8 big blinds",
        "feedback": "O pagamento precisa de 20% de equidade, e os draws perdidos plausíveis sustentam uma estimativa acima desse preço."
      },
      "raise": {
        "label": "Aumentar para 28 big blinds",
        "feedback": "Transformar um bluff-catcher lucrativo em aumento faz os blefes desistirem e recebe ação de valor mais forte."
      },
      "fold": {
        "label": "Desistir",
        "feedback": "Desistir abre mão quando a taxa de vitória estimada supera o ponto de equilíbrio de 20%."
      }
    }
  },
  "multiway-range-discipline": {
    "focus": "Disciplina de range em potes multiway",
    "opponentAction": "Você aumentou no pré-flop e tanto o botão quanto o big blind pagaram. Os dois oponentes passam neste flop.",
    "prompt": "O que muda agora que dois ranges precisam continuar contra {{heroHand}}?",
    "reasoning": "Em potes multiway, cada oponente pode continuar de forma mais seletiva, enquanto o campo combinado conecta com mais frequência. {{heroHand}} tem overcards úteis, mas não tem suporte de range suficiente para pressão automática.",
    "takeaway": "Blefe menos em potes multiway, porque uma única aposta precisa atravessar vários ranges que continuam.",
    "choices": {
      "check": {
        "label": "Passar",
        "feedback": "Passar preserva a equidade das overcards e respeita que pelo menos um dos dois pagadores conecta com mais frequência."
      },
      "small": {
        "label": "Apostar 3 big blinds",
        "feedback": "Uma aposta pequena pode entrar em misturas seletivas, mas precisa de blockers mais fortes ou equidade backdoor contra dois ranges."
      },
      "large": {
        "label": "Apostar 9 big blinds",
        "feedback": "Um blefe do tamanho do pote precisa forçar desistências em dois ranges em um board coordenado, o que torna o risco alto demais."
      }
    }
  },
  "read-sticky-thin-value": {
    "focus": "Valor marginal contra pagadores",
    "opponentAction": "Em 16 mãos observadas, este oponente pagou seis de oito apostas de river pequenas e médias comparáveis, e agora passa para você.",
    "prompt": "Qual ajuste extrai valor de {{heroHand}} sem isolar demais contra mãos melhores?",
    "reasoning": "A amostra é estabelecida e diretamente relevante para pagamentos no river. {{heroHand}} tem alvos mais fracos identificáveis, então uma aposta de valor marginal moderada é uma exploração criteriosa.",
    "takeaway": "Contra pagadores frequentes, amplie o valor marginal antes de recorrer a tamanhos extremos.",
    "choices": {
      "check": {
        "label": "Passar",
        "feedback": "Passar protege o resultado, mas perde o valor sustentado por evidências de um range mais fraco que paga muito."
      },
      "all-in": {
        "label": "Ir all-in",
        "feedback": "O tamanho extremo ainda pode fazer as mãos fracas alvo desistirem e concentra a ação em torno de mãos mais fortes."
      },
      "small": {
        "label": "Apostar 7 big blinds",
        "feedback": "Um tamanho modesto dá aos pares mais fracos um pagamento realista e usa a evidência de pagamentos repetidos."
      }
    }
  },
  "read-small-sample": {
    "focus": "Contenção com amostra pequena",
    "opponentAction": "O oponente passa. Em apenas duas mãos observadas, ele pagou uma aposta no river e desistiu uma vez.",
    "prompt": "A amostra minúscula deve justificar uma exploração extrema com {{heroHand}}?",
    "reasoning": "A amostra contém resultados opostos e nenhuma decisão comparável repetida. Mantenha a base normal de range e propósito com {{heroHand}} em vez de inventar uma leitura.",
    "takeaway": "Duas mãos são uma pista, não uma licença para uma exploração grande.",
    "choices": {
      "large": {
        "label": "Apostar 24 big blinds",
        "feedback": "Um pagamento não é evidência de uma tendência estável, e {{heroHand}} não tem um alvo claro de mãos melhores que desistam."
      },
      "check": {
        "label": "Passar",
        "feedback": "A mão não tem um alvo de valor claro nem um blefe sustentado, e duas observações não justificam um ajuste extremo."
      }
    }
  },
  "release-three-bet-bluff": {
    "focus": "Largando um blefe de 3-bet",
    "opponentAction": "Você deu 3-bet na abertura do cutoff para 10 big blinds. Quem abriu deu 4-bet para 24 big blinds.",
    "prompt": "Qual era o plano original com {{heroHand}}?",
    "reasoning": "{{heroHand}} foi escolhida para gerar desistências antes do flop, não para continuar contra cada aumento posterior. O 4-bet estreita o oponente em um range que domina esta mão de pressão.",
    "takeaway": "Um bom blefe de 3-bet inclui um plano disciplinado de desistência quando o oponente aplica o aumento final.",
    "choices": {
      "fold": {
        "label": "Desistir",
        "feedback": "A mão de pressão cumpriu seu papel; largue-a quando o oponente representar um range muito mais forte."
      },
      "all-in": {
        "label": "Ir all-in",
        "feedback": "Transformar o blefe em um all-in de 5-bet arrisca o stack contra as mãos mais fortes do oponente."
      },
      "call": {
        "label": "Pagar 14 big blinds",
        "feedback": "O ás do mesmo naipe não tem equidade nem realização suficientes contra o range do 4-bet."
      }
    }
  },
  "late-open-value-three-bet": {
    "focus": "3-bet de valor contra abertura tardia",
    "opponentAction": "O botão aumenta para 2.5 big blinds e o small blind desiste.",
    "prompt": "Qual plano extrai o valor mais claro de {{heroHand}}?",
    "reasoning": "{{heroHand}} está muito à frente do range de abertura e continuação do botão. Um 3-bet de 9 big blinds fora de posição constrói valor sem forçar a saída de todas as mãos mais fracas.",
    "takeaway": "Construa o núcleo de valor de um range de 3-bet antes de adicionar mãos de pressão.",
    "choices": {
      "raise": {
        "label": "Aumentar para 9 big blinds",
        "feedback": "Este tamanho constrói valor, nega equidade e deixa espaço para mãos fortes piores continuarem."
      },
      "fold": {
        "label": "Desistir",
        "feedback": "{{heroHand}} está muito à frente de um range amplo de abertura do botão e não pode ser descartada."
      },
      "call": {
        "label": "Pagar 1.5 big blinds",
        "feedback": "Pagar mantém o botão amplo, mas perde valor e permite que ele realize equidade barato."
      }
    }
  },
  "flush-draw-price": {
    "focus": "Draws e odds do pote",
    "opponentAction": "O big blind apostou, e o preço para você pagar é {{callAmountBb}} big blinds.",
    "prompt": "Escolha a resposta mais limpa com o draw de nut flush.",
    "reasoning": "Depois do seu pagamento de {{callAmountBb}} big blinds, o pote final é {{finalPotBb}} big blinds: {{callAmountBb}} ÷ {{finalPotBb}} = {{requiredEquityPercent}}%. Nove outs limpos de flush dão cerca de {{estimatedEquityPercent}}% com duas cartas por vir.",
    "takeaway": "Compare a equidade do draw com o pote final depois do seu pagamento—não com o pote anterior a ele.",
    "choices": {
      "fold": {
        "label": "Desistir",
        "feedback": "Nove outs limpos de flush têm cerca de {{estimatedEquityPercent}}% de equidade até o river, confortavelmente acima deste preço de {{requiredEquityPercent}}%."
      },
      "call": {
        "label": "Pagar 7 big blinds",
        "feedback": "Pagar exige {{requiredEquityPercent}}% de equidade, enquanto nove outs limpos de flush completam cerca de {{estimatedEquityPercent}}% das vezes até o river."
      },
      "raise": {
        "label": "Aumentar para 24 big blinds",
        "feedback": "Um semi-blefe pode funcionar, mas adiciona suposições de fold equity. Pagar é a base matemática mais clara."
      }
    }
  },
  "river-bad-bluff-candidate": {
    "focus": "Mau candidato a blefe no river",
    "opponentAction": "Um oponente de bluff catch pagou no flop, os dois jogadores deram check no turn e o oponente dá check num river que completa o flush.",
    "prompt": "O draw errado com {{heroHand}} e sem blocker de flush deve virar blefe automaticamente?",
    "reasoning": "{{heroHand}} sem blocker de flush errou, mas esse fato sozinho não basta para um bom blefe. O oponente paga com frequência demais e a mão não tem um blocker útil contra as continuações mais fortes do river.",
    "takeaway": "Draws errados precisam de desistências críveis e blockers úteis antes de virarem blefes no river.",
    "choices": {
      "large": {
        "label": "Apostar 36 big blinds",
        "feedback": "Um blefe grande não se sustenta quando a mão bloqueia as desistências prováveis e deixa os pagamentos mais fortes disponíveis."
      },
      "small": {
        "label": "Apostar 8 big blinds",
        "feedback": "O tamanho pequeno oferece um pagamento atraente justamente ao range de um par que você precisa que desista."
      },
      "check": {
        "label": "Passar",
        "feedback": "Desistir evita atacar um range grudado com blockers ruins e sem valor de showdown."
      }
    }
  },
  "tournament-medium-open": {
    "focus": "Flexibilidade de stack médio",
    "opponentAction": "Todos antes de você desistem. As duas blinds têm fichas suficientes para re-shove.",
    "prompt": "Qual tamanho dá pressão com {{heroHand}} sem desperdiçar a flexibilidade de stack?",
    "reasoning": "Com mais de vinte big blinds e posição, {{heroHand}} pode usar uma abertura pequena. O tamanho arrisca pouco, mantém ranges mais fracos envolvidos e deixa espaço para avaliar um re-shove.",
    "takeaway": "Stacks médios devem usar aumentos eficientes e decidir a resposta a um all-in antes de abrir.",
    "choices": {
      "fold": {
        "label": "Desistir",
        "feedback": "A posição no botão e a qualidade sólida das cartas tornam desistir com {{heroHand}} apertado demais."
      },
      "shove": {
        "label": "Ir all-in",
        "feedback": "O all-in direto arrisca mais de vinte big blinds quando uma abertura pequena gera desistências semelhantes e mantém continuações mais fracas disponíveis."
      },
      "raise": {
        "label": "Aumentar para 2.2 big blinds",
        "feedback": "Uma abertura compacta aplica pressão e ainda deixa uma resposta deliberada ao all-in de qualquer blind."
      }
    }
  },
  "river-showdown-check": {
    "focus": "Check de valor de showdown no river",
    "opponentAction": "O big blind pagou uma aposta no flop e os dois jogadores deram check no turn. O big blind dá check no river.",
    "prompt": "{{heroHand}} tem um alvo claro de mãos piores dispostas a pagar?",
    "reasoning": "{{heroHand}} pode vencer no showdown, mas uma aposta grande no river não tem alvo estável: as mãos piores desistem enquanto os pares mais fortes continuam. Passar preserva o valor atual da mão.",
    "takeaway": "Mãos de força média no river pertencem ao range de check quando é difícil nomear pagamentos piores.",
    "choices": {
      "small": {
        "label": "Apostar 8 big blinds",
        "feedback": "Uma aposta muito pequena às vezes pode mirar um par inferior, mas a margem de valor é estreita."
      },
      "large": {
        "label": "Apostar 28 big blinds",
        "feedback": "Uma aposta do tamanho do pote desiste as mãos mais fracas e recebe ação de um range que normalmente já vence esta mão média."
      },
      "check": {
        "label": "Passar",
        "feedback": "A mão retém valor de showdown útil, mas não consegue nomear mãos piores suficientes que paguem uma aposta no river."
      }
    }
  },
  "facing-three-bet-position-call": {
    "focus": "Pagar um 3-bet em posição",
    "opponentAction": "Você abriu para 2.5 big blinds. O big blind deu 3-bet para 10 big blinds.",
    "prompt": "Qual é a base mais clara com {{heroHand}}?",
    "reasoning": "{{heroHand}} pode formar pares fortes, sequências e flushes enquanto age por último após o flop. Pagar mantém mãos dominadas no pote e evita isolar contra as continuações mais fortes.",
    "takeaway": "Posição e jogabilidade robusta podem transformar o pagamento de um 3-bet na melhor base.",
    "choices": {
      "fold": {
        "label": "Desistir",
        "feedback": "Desistir é conservador, mas abre mão de uma mão com equidade útil e realização posicional."
      },
      "raise": {
        "label": "Aumentar para 23 big blinds",
        "feedback": "Um 4-bet pode entrar em misturas seletivas, mas pagar é a base mais estável com esta mão jogável."
      },
      "call": {
        "label": "Pagar 7.5 big blinds",
        "feedback": "A posição e a conectividade do mesmo naipe permitem que esta mão realize equidade sem inflar o pote novamente."
      }
    }
  },
  "brick-turn-value-barrel": {
    "focus": "Barrel de valor em turn neutro",
    "opponentAction": "O big blind pagou sua aposta no flop e passa de novo após um turn baixo e neutro.",
    "prompt": "Qual plano continua extraindo de pares mais fracos e draws com {{heroHand}}?",
    "reasoning": "O turn neutro muda pouco e {{heroHand}} segue à frente de muitos pagamentos no flop. Um barrel de valor controlado cobra draws e pares mais fracos sem isolar contra apenas as mãos mais fortes.",
    "takeaway": "Em um turn realmente neutro, continue apostando por valor quando puder nomear várias mãos mais fracas que ainda pagam.",
    "choices": {
      "overbet": {
        "label": "Apostar 27 big blinds",
        "feedback": "A aposta grande demais faz uma parte do range mais fraco desistir, e o par superior forte quer manter esse range pagando."
      },
      "check": {
        "label": "Passar",
        "feedback": "Passar protege a mão, mas perde valor de pares superiores mais fracos, segundos pares e draws disponíveis."
      },
      "medium": {
        "label": "Apostar 10 big blinds",
        "feedback": "Um pouco acima de meio pote cobra draws enquanto mantém várias mãos feitas mais fracas no pote."
      }
    }
  },
  "blind-defense": {
    "focus": "Defesa das blinds",
    "opponentAction": "O botão aumentou e, com 1 big blind já investido, você precisa pagar {{callAmountBb}} big blinds.",
    "prompt": "Como você deve se defender?",
    "reasoning": "Pagar {{callAmountBb}} big blinds cria um pote final de {{finalPotBb}} big blinds, um preço de {{requiredEquityPercent}}%. {{heroHand}} segue sendo uma mão fraca e desconectada que precisa agir primeiro após o flop.",
    "takeaway": "Defenda mais amplo contra aberturas pequenas, mas largue as mãos mais fracas conforme o preço aumenta.",
    "choices": {
      "call": {
        "label": "Pagar 3 big blinds",
        "feedback": "O pagamento exige cerca de {{requiredEquityPercent}}% de equidade antes de considerar a jogabilidade ruim. Sua blind paga já faz parte do pote."
      },
      "raise": {
        "label": "Aumentar para 12 big blinds",
        "feedback": "Esta mão tem blockers e jogabilidade ruins, o que a torna um candidato fraco a blefe."
      },
      "fold": {
        "label": "Desistir",
        "feedback": "O tamanho grande piora o seu preço, e {{heroHand}} realiza equidade mal fora de posição."
      }
    }
  },
  "tournament-deep-open": {
    "focus": "Tamanho de abertura com stack fundo",
    "opponentAction": "A ação desiste até você enquanto todos os stacks restantes ainda podem jogar o flop, o turn e o river.",
    "prompt": "Qual plano de entrada preserva o valor de {{heroHand}}?",
    "reasoning": "Nesta profundidade de stack, {{heroHand}} se beneficia de uma abertura pequena normal e de um plano pós-flop flexível. Um all-in direto arrisca o stack inteiro sem ganhar desistências ou valor extras suficientes.",
    "takeaway": "Não use jogadas de stack curto enquanto o stack efetivo ainda deixa espaço pós-flop relevante.",
    "choices": {
      "fold": {
        "label": "Desistir",
        "feedback": "{{heroHand}} é confortavelmente forte o suficiente para abrir do cutoff depois que os jogadores anteriores desistirem."
      },
      "shove": {
        "label": "Ir all-in",
        "feedback": "Arriscar mais de 35 big blinds faz mãos mais fracas desistirem e recebe ação de um range desnecessariamente forte."
      },
      "raise": {
        "label": "Aumentar para 2.25 big blinds",
        "feedback": "A abertura eficiente constrói valor e preserva espaço para responder à ação posterior."
      }
    }
  },
  "four-bet-premium-value": {
    "focus": "Dar 4-bet por valor",
    "opponentAction": "Você abriu para 2.5 big blinds. O small blind dá 3-bet para 11 big blinds e o big blind desiste.",
    "prompt": "Qual linha constrói o valor mais claro com {{heroHand}}?",
    "reasoning": "{{heroHand}} quer um pote maior contra as mãos de continuação fortes do small blind. Um 4-bet controlado ganha valor sem usar um tamanho de all-in desnecessariamente grande.",
    "takeaway": "Dê 4-bet com o topo do range por valor e escolha um tamanho que ainda possa ser pago por mãos piores.",
    "choices": {
      "call": {
        "label": "Pagar 8.5 big blinds",
        "feedback": "Pagar pode montar uma armadilha, mas abre mão da oportunidade mais clara de construir o pote contra continuações fortes."
      },
      "fold": {
        "label": "Desistir",
        "feedback": "{{heroHand}} está no topo do range de abertura e é forte demais para desistir."
      },
      "raise": {
        "label": "Aumentar para 24 big blinds",
        "feedback": "Um 4-bet compacto constrói valor enquanto dá espaço a quem deu 3-bet para continuar com mãos piores."
      }
    }
  },
  "turn-value": {
    "focus": "Apostar por valor",
    "opponentAction": "O big blind passa pela segunda vez.",
    "prompt": "Como você continua com {{heroHand}}?",
    "reasoning": "Você pode nomear várias mãos piores que continuam. Uma aposta de meio pote captura valor sem isolar você apenas contra mãos muito fortes.",
    "takeaway": "Apostar por valor começa identificando mãos piores que podem realisticamente pagar o seu tamanho.",
    "choices": {
      "check": {
        "label": "Passar",
        "feedback": "Passar controla o pote, mas perde valor de pares mais fracos e draws."
      },
      "bet": {
        "label": "Apostar 10 big blinds",
        "feedback": "Uma aposta de meio pote mira várias mãos piores enquanto cobra os draws disponíveis."
      },
      "all-in": {
        "label": "Ir all-in",
        "feedback": "Um all-in grande demais faz desistir uma parte do range mais fraco que você quer manter pagando."
      }
    }
  },
  "read-pressure-bluff-catch": {
    "focus": "Defender contra pressão ampla",
    "opponentAction": "Ao longo de vinte mãos, o botão apostou ou aumentou em dez de treze oportunidades pós-flop. Vários draws perdem e ele aposta 14 em um pote de 40 no river.",
    "prompt": "A evidência de preço e de agressividade ampla sustenta defender {{heroHand}}?",
    "reasoning": "Pagar {{callAmountBb}} big blinds cria um pote final de {{finalPotBb}} big blinds e precisa de cerca de {{requiredEquityPercent}}% de equidade. A amostra agressiva relevante do oponente e os draws perdidos dão a {{heroHand}} suporte suficiente de bluff-catcher sem transformar a mão em um aumento.",
    "takeaway": "Amplie o bluff-catching apenas quando amostra, linha, bloqueadores e preço apontarem na mesma direção.",
    "choices": {
      "call": {
        "label": "Pagar 14 big blinds",
        "feedback": "O preço justo, os draws perdidos e a frequência agressiva estabelecida fazem deste um bluff catch sustentado."
      },
      "fold": {
        "label": "Desistir",
        "feedback": "Desistir tem menos variância, mas pode respeitar demais uma aposta pequena de um range observado aplicando pressão frequente."
      },
      "raise": {
        "label": "Aumentar para 45 big blinds",
        "feedback": "Pagar mantém os blefes no range; aumentar os faz desistir e recebe ação das mãos de valor mais fortes."
      }
    }
  },
  "read-frequent-folder-pressure": {
    "focus": "Pressão sustentada por evidências",
    "opponentAction": "Em 14 mãos, este oponente desistiu em cinco de sete potes comparáveis com um único aumento. Ele paga o flop e passa em um turn neutro.",
    "prompt": "Qual ajuste criterioso usa equidade e desistências observadas com {{heroHand}}?",
    "reasoning": "{{heroHand}} pode melhorar quando pago, e o oponente desistiu repetidamente em potes comparáveis. Um barrel controlado muda um único fator—a frequência—sem transformar a leitura em um overbet extremo.",
    "takeaway": "Use evidências confiáveis de desistências para adicionar pressão selecionada com equidade ou blockers úteis.",
    "choices": {
      "all-in": {
        "label": "Ir all-in",
        "feedback": "A amostra sustenta mais pressão, não arriscar o stack inteiro quando uma aposta menor pode produzir desistências."
      },
      "check": {
        "label": "Passar",
        "feedback": "Passar realiza a equidade do draw, mas abre mão de pressão de desistências sustentada por evidências."
      },
      "bet": {
        "label": "Apostar 11 big blinds",
        "feedback": "O barrel controlado combina equidade limpa de melhora com um histórico relevante de desistências."
      }
    }
  },
  "three-bet-pot-dry-range-bet": {
    "focus": "Aposta de range em pote de 3-bet seco",
    "opponentAction": "Você deu 3-bet no pré-flop, o cutoff pagou e agora passa neste flop seco.",
    "prompt": "Qual plano no flop melhor usa a vantagem de range com {{heroHand}}?",
    "reasoning": "Quem deu o 3-bet tem mais ases fortes, overpairs e combinações de ás-rei neste board seco com ás alto. Uma aposta pequena aplica essa vantagem de range de forma eficiente com {{heroHand}}.",
    "takeaway": "Em flops de pote de 3-bet secos e de carta alta, a vantagem de range com frequência sustenta uma aposta pequena e frequente.",
    "choices": {
      "check": {
        "label": "Passar",
        "feedback": "Passar pode proteger o range, mas abre mão de uma oportunidade de pressão de baixo risco neste board seco."
      },
      "large": {
        "label": "Apostar 21 big blinds",
        "feedback": "Uma aposta do tamanho do pote arrisca demais quando um tamanho pequeno pressiona as mesmas mãos sem par e de força média."
      },
      "small": {
        "label": "Apostar 7 big blinds",
        "feedback": "Uma aposta de um terço do pote usa o range carregado de mãos premium arriscando pouco contra o range mais fraco de quem pagou."
      }
    }
  },
  "caller-nut-advantage-restraint": {
    "focus": "Tamanho com vantagem de nuts",
    "opponentAction": "Você abriu pré-flop, o big blind pagou e agora dá check neste flop baixo e conectado.",
    "prompt": "Como a vantagem de nuts de quem pagou deve afetar {{heroHand}}?",
    "reasoning": "{{heroHand}} ainda pode extrair valor de pares e draws, mas o big blind tem mais das combinações mais fortes do board. Uma aposta controlada de meio pote respeita essa vantagem de nuts sem abrir mão do valor.",
    "takeaway": "A vantagem de nuts de quem pagou deve limitar o tamanho e a frequência das apostas, não apagar toda aposta de valor.",
    "choices": {
      "check": {
        "label": "Passar",
        "feedback": "Passar protege o overpair e mantém o pote administrável contra um range com mais mãos muito fortes."
      },
      "large": {
        "label": "Apostar 6.5 big blinds",
        "feedback": "Uma aposta do tamanho do pote constrói o maior pote justamente quando quem pagou tem mais combinações de sequências, trincas e dois pares."
      },
      "medium": {
        "label": "Apostar 3.5 big blinds",
        "feedback": "Uma aposta controlada de valor e proteção cobra pares e draws sem forçar o maior pote."
      }
    }
  },
  "equity-driven-turn-barrel": {
    "focus": "Barrel no turn guiado por equidade",
    "opponentAction": "O big blind pagou sua aposta no flop e passa no turn. Você mantém um draw de flush forte.",
    "prompt": "Qual plano no turn mantém vivos os dois caminhos de vitória com {{heroHand}}?",
    "reasoning": "{{heroHand}} pode melhorar para um flush forte e também fazer mãos melhores sem par ou de um par desistirem. Esses dois caminhos sustentam um segundo barrel controlado.",
    "takeaway": "Semi-blefes no turn funcionam melhor quando equidade relevante de melhora e fold equity crível se sobrepõem.",
    "choices": {
      "overbet": {
        "label": "Apostar 27 big blinds",
        "feedback": "O risco exagerado é desnecessário quando uma aposta menor faz o mesmo range de força média desistir."
      },
      "medium": {
        "label": "Apostar 12 big blinds",
        "feedback": "Um barrel controlado combina equidade de draw com pressão sobre mãos de um par e continuações sem par mais fracas."
      },
      "check": {
        "label": "Passar",
        "feedback": "Passar garante a realização do draw, mas abre mão de fold equity imediata contra mãos de força média."
      }
    }
  },
  "tournament-small-blind-shove": {
    "focus": "Pressão push-fold na small blind",
    "opponentAction": "O botão desiste. Resta apenas um range aleatório de big blind, e você age primeiro após o flop se for pago.",
    "prompt": "Qual plano usa {{heroHand}} e o stack efetivo curto da forma mais clara?",
    "reasoning": "Com apenas um oponente e menos de dez big blinds efetivos, {{heroHand}} tem equidade suficiente para aplicar pressão direta. O all-in evita um pote difícil de stack baixo fora de posição.",
    "takeaway": "Ranges de primeira entrada na small blind podem pressionar com amplitude quando resta apenas um oponente, mas a mão ainda precisa de equidade útil quando paga.",
    "choices": {
      "fold": {
        "label": "Desistir",
        "feedback": "{{heroHand}} é forte o suficiente para pressionar um range aleatório de blind em vez de entregar a small blind."
      },
      "limp": {
        "label": "Pagar 0.5 big blinds",
        "feedback": "Dar limp pode aparecer em uma estratégia desenvolvida, mas preserva uma decisão pós-flop fora de posição com muito pouco stack atrás."
      },
      "shove": {
        "label": "Ir all-in",
        "feedback": "O all-in maximiza a pressão de desistências contra um range e realiza toda a equidade da mão quando pago."
      }
    }
  },
  "turn-straight-price": {
    "focus": "Preço do draw de sequência",
    "opponentAction": "O big blind aposta {{callAmountBb}} big blinds no turn. Oito outs limpos de sequência valem cerca de {{estimatedEquityPercent}}% com uma carta por vir.",
    "prompt": "O preço direto sustenta um call?",
    "reasoning": "Pagar {{callAmountBb}} big blinds deixa o pote final em {{finalPotBb}} big blinds: {{callAmountBb}} ÷ {{finalPotBb}} ≈ {{requiredEquityPercent}}%. Esse preço está abaixo dos {{estimatedEquityPercent}}% de equidade declarados do draw.",
    "takeaway": "Uma aposta pequena pode oferecer um call de draw lucrativo mesmo com apenas uma carta por vir.",
    "choices": {
      "all-in": {
        "label": "Aumentar all-in",
        "feedback": "O call direto lucrativo não justifica arriscar o stack completo sem evidência de fold equity."
      },
      "call": {
        "label": "Pagar 3 big blinds",
        "feedback": "O call precisa de cerca de 13% de equidade, abaixo da chance declarada de 17% do draw."
      },
      "fold": {
        "label": "Desistir",
        "feedback": "Desistir abre mão de um draw estimado em 17% quando o call precisa de apenas cerca de 13%."
      }
    }
  },
  "tournament-button-shove": {
    "focus": "Pressão push-fold no botão",
    "opponentAction": "Todos desistem até você e restam apenas dois ranges aleatórios de blinds.",
    "prompt": "Qual é a referência mais limpa de stack curto com {{heroHand}}?",
    "reasoning": "Com cerca de 11 big blinds e apenas as blinds atrás, {{heroHand}} combina equidade útil com pressão de desistência imediata. O all-in direto evita comprometer uma grande fração e depois desistir.",
    "takeaway": "Posição tardia e stack curto podem simplificar mãos sólidas de primeira entrada para um all-in direto.",
    "choices": {
      "shove": {
        "label": "Ir all-in",
        "feedback": "O all-in pressiona dois ranges amplos e realiza toda a equidade de {{heroHand}} quando pago."
      },
      "raise": {
        "label": "Aumentar para 2 big blinds",
        "feedback": "Um aumento pequeno pode pertencer a uma estratégia desenvolvida, mas cria um ramo difícil de aumentar-desistir nessa profundidade de stack."
      },
      "fold": {
        "label": "Desistir",
        "feedback": "{{heroHand}} tem equidade e pressão de desistência de posição tardia suficientes para entrar em vez de entregar as blinds."
      }
    }
  },
  "bubble-covering-call": {
    "focus": "Call com stack que cobre",
    "opponentAction": "Duas posições avançam. O stack mais curto vai all-in no botão, o small blind desiste, e você continua líder em fichas mesmo perdendo.",
    "prompt": "Como cobrir o all-in afeta {{heroHand}}?",
    "reasoning": "O stack mais curto pode ir all-in com amplitude e não pode te eliminar. {{heroHand}} tem equidade direta suficiente, e seu custo de sobrevivência é menor que o de um stack do meio coberto.",
    "takeaway": "Cobrir o oponente pode sustentar um pagamento mais amplo quando a mão ainda vence parte suficiente do range de all-in.",
    "choices": {
      "call": {
        "label": "Pagar all-in",
        "feedback": "Você cobre o stack curto, mantém fichas depois de uma perda e tem equidade forte contra o range de posição tardia."
      },
      "fold": {
        "label": "Desistir",
        "feedback": "Desistir preserva a liderança, mas abre mão de um preço lucrativo contra um all-in amplo do stack mais curto."
      }
    }
  },
  "math-pot-bluff-fold": {
    "focus": "Limite do blefe do tamanho do pote",
    "opponentAction": "O oponente passa. Uma aposta do tamanho do pote arrisca 20 big blinds, mas a evidência de range sugere que apenas cerca de 35% das mãos melhores desistem.",
    "prompt": "Um blefe do tamanho do pote é lucrativo com {{heroHand}}?",
    "reasoning": "Um blefe puro do tamanho do pote precisa funcionar {{riskBb}} ÷ ({{riskBb}} + {{rewardBb}}), ou {{requiredFoldPercent}}%, das vezes. A estimativa de 35% deixa uma lacuna grande, e {{heroHand}} não tem equidade limpa quando pago para fechá-la.",
    "takeaway": "Blefes maiores exigem mais desistências; risco extra não as cria automaticamente.",
    "choices": {
      "check": {
        "label": "Passar",
        "feedback": "As desistências estimadas de 35% ficam bem abaixo dos 50% exigidos por um blefe do tamanho do pote sem equidade."
      },
      "bet": {
        "label": "Apostar 20 big blinds",
        "feedback": "Arriscar 20 para ganhar 20 exige que metade do range desista, o que a evidência não sustenta."
      }
    }
  },
  "bubble-premium-call": {
    "focus": "Mão premium sob pressão",
    "opponentAction": "Duas posições avançam. O líder vai all-in da small blind e um stack de 7 big blinds permanece.",
    "prompt": "O prêmio de risco torna {{heroHand}} uma desistência?",
    "reasoning": "O prêmio de risco é real, mas não é infinito. {{heroHand}} mantém uma vantagem decisiva de equidade contra um líder que pode pressionar com amplitude da small blind.",
    "takeaway": "Use o ICM para mover decisões de fronteira; não desista de mãos muito acima do limite ajustado.",
    "choices": {
      "call": {
        "label": "Pagar all-in",
        "feedback": "A mão premium ultrapassa o limite mais alto de torneio e pode pagar mesmo sendo coberta."
      },
      "fold": {
        "label": "Desistir",
        "feedback": "A pressão da bolha muda pagamentos marginais, mas {{heroHand}} está muito à frente de um all-in amplo da small blind para ser entregue."
      }
    }
  },
  "semi-bluff-size": {
    "focus": "Tamanho de semi-blefe",
    "opponentAction": "O big blind passa. Você tem um draw de sequência aberta e pouco valor em showdown.",
    "prompt": "Qual linha aplica pressão sem arriscar demais o draw?",
    "reasoning": "Apostar meio pote pode fazer com que mãos mais fortes sem par desistam, enquanto o draw aberto mantém oito cartas de melhora quando pago.",
    "takeaway": "Semi-blefes combinam fold equity e equidade de draw; eles não exigem o maior tamanho possível.",
    "choices": {
      "check": {
        "label": "Passar",
        "feedback": "Passar realiza a equidade do draw com segurança, mas abre mão da chance de fazer mãos melhores de carta alta desistirem."
      },
      "all-in": {
        "label": "Ir all-in",
        "feedback": "Um all-in enorme arrisca o stack inteiro quando uma aposta menor pode criar desistências semelhantes."
      },
      "half": {
        "label": "Apostar 5 big blinds",
        "feedback": "Meio pote combina fold equity com oito outs de sequência mantendo o risco controlado."
      }
    }
  },
  "tournament-avoid-deep-shove": {
    "focus": "Preserve espaço pós-flop",
    "opponentAction": "Você abre para 2.2 big blinds e o big blind re-aumenta para 7 big blinds. Mais de 25 big blinds permanecem atrás.",
    "prompt": "Qual resposta de valor mantém mãos mais fracas disponíveis com {{heroHand}}?",
    "reasoning": "O stack efetivo ainda não está na zona de push-fold. {{heroHand}} pode usar um 4-bet de valor compacto que mantém mãos fortes mais fracas envolvidas, em vez de forçar todo o stack imediatamente.",
    "takeaway": "As fichas de torneio não exigem all-in enquanto o stack efetivo ainda sustenta um aumento de valor menor.",
    "choices": {
      "raise": {
        "label": "Aumentar para 16 big blinds",
        "feedback": "O 4-bet controlado constrói valor e deixa espaço para continuações mais fracas e uma decisão final deliberada."
      },
      "fold": {
        "label": "Desistir",
        "feedback": "{{heroHand}} é forte demais para largar contra um re-aumento das blinds de três jogadores."
      },
      "shove": {
        "label": "Ir all-in",
        "feedback": "Um all-in por mais de 30 big blinds faz boa parte do range mais fraco desistir e é pago por uma seleção mais forte."
      }
    }
  }
};

export const portugueseScenarioVocab: ScenarioVocab = {
  "terms": {
    "Two limpers and both blinds": "Dois limpadores e as duas blinds",
    "Small blind and big blind": "Small blind e big blind",
    "Cutoff and button": "cutoff e botão",
    "Button and blinds behind": "Botão com blinds atrás",
    "Two covered blinds": "Duas blinds cobertas",
    "Two larger blinds": "Duas blinds maiores",
    "Middle position": "Posição intermediária",
    "Five players behind": "Cinco jogadores atrás",
    "Three players behind": "Três jogadores atrás",
    "two blinds behind": "duas blinds atrás",
    "Under the gun": "UTG",
    "Small blind": "small blind",
    "Big blind": "big blind",
    "Button": "Botão",
    "Cutoff": "cutoff",
    "chip leader": "líder em fichas",
    "shortest stack": "o stack mais curto",
    "frequent caller": "jogador que paga muito",
    "frequent folder": "jogador que desiste muito",
    "frequent aggressor": "agressor frequente",
    "strong range": "range forte",
    "six players": "seis jogadores",
    "three players": "três jogadores",
    "patient": "paciente"
  },
  "actions": [
    {
      "pattern": "^Check back$",
      "template": "Passar"
    },
    {
      "pattern": "^Check$",
      "template": "Passar"
    },
    {
      "pattern": "^Fold$",
      "template": "Desistir"
    },
    {
      "pattern": "^Call all-in$",
      "template": "Pagar all-in"
    },
    {
      "pattern": "^Move all-in$",
      "template": "Ir all-in"
    },
    {
      "pattern": "^Raise all-in$",
      "template": "Aumentar all-in"
    },
    {
      "pattern": "^Call 1 big blind$",
      "template": "Pagar 1 big blind"
    },
    {
      "pattern": "^Call (\\d+(?:\\.\\d+)?) big blinds?$",
      "template": "Pagar $1 big blinds"
    },
    {
      "pattern": "^Raise to (\\d+(?:\\.\\d+)?) big blinds?$",
      "template": "Aumentar para $1 big blinds"
    },
    {
      "pattern": "^Bet (\\d+(?:\\.\\d+)?) big blinds?$",
      "template": "Apostar $1 big blinds"
    }
  ],
  "handLabels": {
    "thisHand": "esta mão",
    "pair": "par na mão",
    "suited": "do mesmo naipe",
    "offsuit": "de naipes diferentes"
  },
  "mathSummaries": {
    "bluff": "Arrisca {{riskBb}} big blinds para ganhar {{rewardBb}} big blinds; um blefe puro precisa de pelo menos {{requiredFoldPercent}}% de desistências.",
    "impliedOdds": "Pelas pot odds diretas, o pagamento precisa de {{directRequiredEquityPercent}}% de equidade e uma melhora limpa de aproximadamente {{estimatedCleanEquityPercent}}%; depois de formar a mão ainda precisa ganhar, em estimativa, cerca de {{minimumFutureWinBb}} big blinds a mais.",
    "call": "Depois de pagar {{callAmountBb}} big blinds, o pote final é {{finalPotBb}} big blinds e são necessários {{requiredEquityPercent}}% de equidade.",
    "callWithEquity": "Depois de pagar {{callAmountBb}} big blinds, o pote final é {{finalPotBb}} big blinds, são necessários {{requiredEquityPercent}}% de equidade e a equidade estimada é {{estimatedEquityPercent}}%."
  }
};
